### ISSUE TITLE
[Bug]: 404 error at URL: /txns/tSqOuS4obED6hpJQ0ZaArhLsRRrjN__Mxkh1tt-SY7Q

### ISSUE THREAD

**Issue by Celizondoc99** [helium/explorer#1002]
### What happened?

A bug happened!

### URL

https://explorer.helium.com/txns/tSqOuS4obED6hpJQ0ZaArhLsRRrjN__Mxkh1tt-SY7Q

### What browsers are you seeing the problem on?

Safari

### Do you see the issue on Mobile or Desktop?

Mobile

**Comment by cokes518** [comment]
this transaction doesn't exist - please try submitting the transaction again and/or double check that the hash is meant for the helium blockchain.
