### ISSUE TITLE
[Bug]: 404 error at URL: /txns/81FJZDT30enbpy-MWmyX7m0bmfIMX8NipEm2djxxmlM

### ISSUE THREAD

**Issue by martinmosk3** [helium/explorer#1003]
### What happened?

A bug happened!

### URL

https://explorer.helium.com/txns/81FJZDT30enbpy-MWmyX7m0bmfIMX8NipEm2djxxmlM

### What browsers are you seeing the problem on?

Chrome

### Do you see the issue on Mobile or Desktop?

Mobile

**Comment by cokes518** [comment]
this isn't a valid transaction hash. can you double check where you got this from?

**Comment by cokes518** [comment]
closing as stale.
