### ISSUE TITLE
Show % Hotspots online excluding Denylisted Hotspots

### ISSUE THREAD

**Issue by cokes518** [helium/explorer#1013]
Our current % online looks low but that's because offline Hotspots include denylisted Hotspots. Propose we include a stat that says "% Online (Filtered)" or "% Online (excl Denylist)"

Denylist can be found here: 
https://github.com/helium/denylist/blob/main/denylist.csv

**Comment by waveform06** [comment]
Does "hotspots" include "data only hotspots"?
As they could be filtered out too, or is online % already considering % out of hotspots-DO hotspots?
