### ISSUE TITLE
[Bug]: 404 error at URL: /txns/E-MXRcBxMSq379IRtycaH9QSQPKSdZlgIUq1cabvjKU

### ISSUE THREAD

**Issue by yoranom2** [helium/explorer#1014]
### What happened?

A bug happened!

### URL

E-MXRcBxMSq379IRtycaH9QSQPKSdZlgIUq1cabvjKU

### What browsers are you seeing the problem on?

Chrome

### Do you see the issue on Mobile or Desktop?

Mobile

**Comment by cokes518** [comment]
looks like the transaction doesn't exist. please try submitting the transaction again and/or double check that the transaction has is for the helium blockchain.
