### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by saloh34** [helium/explorer#1015]
### What happened?

A bug happened!
![7339FF3C-8775-4915-A6DA-22FE48A84E1D](https://user-images.githubusercontent.com/86102461/184299907-eaea9c42-65e3-4692-89c1-24e15c29cc7d.jpeg)
![0162DCF8-952D-4DC9-89C0-46BD8A894E78](https://user-images.githubusercontent.com/86102461/184299917-bfacb65c-3d45-42d0-986c-eef1dd71cda1.png)

### URL

FxPXgufiSkEmFqNxF9TUNN2U9JGbWm8LEXOluXUqpYI

### What browsers are you seeing the problem on?

Safari

### Do you see the issue on Mobile or Desktop?

Desktop

### Relevant log output

```shell
Fix
```

**Comment by cokes518** [comment]
cannot debug with the information given. please provide your wallet address if you want additional help
