### ISSUE TITLE
[Bug]: 404 error at URL: /txns/Z16ITrXSPeHxGDns8e-5_IuKY_naVa_ZFXXf-_ZcUgk

### ISSUE THREAD

**Issue by xblacklight** [helium/explorer#1020]
### What happened?

A bug happened!

### URL

https://explorer.helium.com/txns/Z16ITrXSPeHxGDns8e-5_IuKY_naVa_ZFXXf-_ZcUgk

### What browsers are you seeing the problem on?

Firefox

**Comment by cokes518** [comment]
this transaction doesn't exist. please try resubmitting the transaction and/or double check that the hash is meant for the helium blockchain.
