### ISSUE TITLE
[Bug]: 404 error at URL: /hotspots/cities/bWlsaWxhbmloYXdhaWl1bml0ZWQgc3RhdGVz

### ISSUE THREAD

**Issue by Delitants** [helium/explorer#1021]
### What happened?

A bug happened!

### URL

https://explorer.helium.com/hotspots/cities/bWlsaWxhbmloYXdhaWl1bml0ZWQgc3RhdGVz

### What browsers are you seeing the problem on?

Chrome

### Do you see the issue on Mobile or Desktop?

Desktop

**Comment by cokes518** [comment]
city is loading for me right now. this can sometimes happen if the API hiccups at the time you're looking at it. 

<img width="431" alt="image" src="https://user-images.githubusercontent.com/19331274/195224216-88073009-1db7-4e4d-929c-11796fb00afe.png">
