### ISSUE TITLE
[Bug]: 404 error at URL: /txns/ady1Ty_2wNQ92N_smdnn8gtddumx7cGuxeeVzO6usMY

### ISSUE THREAD

**Issue by Myfatherthenudge** [helium/explorer#1022]
### What happened?

A bug happened!

### URL

Transaction keeps declining when I try to send helium out of the current wallet

13daZv3rHTa6c3QRojp5fLGVCEpTo6n6E5iSN42BMvVYFrQwrbo

### What browsers are you seeing the problem on?

Safari

### Do you see the issue on Mobile or Desktop?

Mobile

**Comment by cokes518** [comment]
did you resolve this? looks like there was a payment transaction on 8/18 that cleared.
