### ISSUE TITLE
[Bug]: 404 error at URL: /txns/AiMweh0eFZa5xoNqZ9oQtoSRRYDc33sz2wkf2HbrzPg

### ISSUE THREAD

**Issue by S0litaire** [helium/explorer#1024]
### What happened?

Issue viewing transaction in the explorer site & Also their is 3 blocks which I'm not able to view transactions details.

Getting a 404 error when looking for a Transaction I made on July 25th 18:54 BST. (URL1 in the list below) The transaction was included in block 1453922.

If I use the mobile app I get the basic transaction details (i.e.  Sent to / from, Transaction hash Block number) but can not view the block contents. The desktop version just gives me the "404 — Transaction Not Found" error with the option to file bug report.

1453922 and 2 other blocks are not loading transaction listings when viewed in the explorer page:

1453920
1453921

### URL

https://explorer.helium.com/txns/AiMweh0eFZa5xoNqZ9oQtoSRRYDc33sz2wkf2HbrzPg
https://explorer.helium.com/blocks/1453920
https://explorer.helium.com/blocks/1453921
https://explorer.helium.com/blocks/1453922

### What browsers are you seeing the problem on?

Chrome, Firefox

### Do you see the issue on Mobile or Desktop?

Mobile, Desktop

**Comment by cokes518** [comment]
what is your wallet address? looks like someone else is experiencing the same 404 error on a valid transaction hash.

**Comment by S0litaire** [comment]
My wallet address is : 14RvUh7f7wNKHGjuvoNuYw7RSgbXjnE4Un9jsXYTFKttJzJpawX

Note : I used the helium-wallet CLI version 1.7.4 running on ubuntu 22.04 to send the transaction.

**Comment by cokes518** [comment]
hey @S0litaire i took a look at this, and while the transaction did clear, the hash is not displaying on explorer as you correctly stated. Unfortunately, since this transaction happened over a month ago, there are no logs for us to look at so I cannot dig into this any further. 

if this happens again, please file another issue.
