### ISSUE TITLE
Add page-specific opengraph/sharing metadata

### ISSUE THREAD

**Issue by jamiew** [helium/explorer#103]
Currently, every explorer page has the same `og:description` and other opengraph metadata. So if I share a page like:

https://explorer.helium.com/accounts/144bdZPcErfZ4DTLboF4M1hMDmBdULVdznSwm7HohUQnF6zzkk7

You'll see the same share information as if I'd shared https://explorer.helium.com or any other URL

Example from a random hotspot – 

![Screen Shot 2020-11-30 at 11-30-37 Sharing Debugger - Facebook for Developers ](https://user-images.githubusercontent.com/1903/100636230-7b343380-32ff-11eb-9261-351511165ec0.png)

In FB Sharing Debugger: https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fexplorer.helium.com%2Faccounts%2F144bdZPcErfZ4DTLboF4M1hMDmBdULVdznSwm7HohUQnF6zzkk7

I would suggest varying title & description for the following pages:

* /hotspots/xyz123 – "Hotspot magic-animal-name (xyz123) • Helium Explorer"
* /accounts/xyz123 – "Account xyz123 • Helium Explorer"
* /txns/xyz123 – "Transaction xyz123 • Helium Explorer"
* /blocks/650123 – "Block #650123 • Helium Explorer"

This would also help with SEO, since right now all the pages appear the same

**Comment by Ehesp** [comment]
This should be totally possible now pages are unique. I guess just needs some data piping through the `Head` component.

**Comment by danielcolinjames** [comment]
this was closed by #107

**Comment by jamiew** [comment]
Long journey :) Kudos
