### ISSUE TITLE
[Bug]: Explorer shows "0" hotspots in IOT and MOBILE sections after loading.

### ISSUE THREAD

**Issue by Siegfried-B** [helium/explorer#1031]
### What happened?

Opened explorer.helium.com to check for current numbers of registered hotspots. Showed "0" in both subDAOs. After reloading the page, seemingly correct current numbers were shown as usual.

### URL

explorer.helium.com

### What browsers are you seeing the problem on?

Chrome

### Do you see the issue on Mobile or Desktop?

Mobile

**Comment by Siegfried-B** [comment]
Addendum:
Browsed a bit, after returning to the explorer window, the zeros reappeared. 
![Screenshot_20220823-135138](https://user-images.githubusercontent.com/99081089/186152097-f6adaf35-fb59-47d5-a667-1f8cda9181ee.png)

**Comment by cokes518** [comment]
this was a momentary blip involving our API provider and a subsequently a full database (which we're increased the memory of). apologies for the inconvenience!
