### ISSUE TITLE
[Bug]: 404 error at URL: /txns/jD9l06HT41olYjVU-_HJ4VIjdTMwFixOBxcpDcrkHdk

### ISSUE THREAD

**Issue by charles5991** [helium/explorer#1032]
### What happened?

A bug happened!

### URL

 URL: /txns/jD9l06HT41olYjVU-_HJ4VIjdTMwFixOBxcpDcrkHdk

### What browsers are you seeing the problem on?

Safari

### Do you see the issue on Mobile or Desktop?

Mobile

**Comment by cokes518** [comment]
the transaction exists. it just needed to clear before it appeared on explorer. https://explorer.helium.com/txns/jD9l06HT41olYjVU-_HJ4VIjdTMwFixOBxcpDcrkHdk
