### ISSUE TITLE
[Bug]: 404 error at URL: /hotspots/cities/dWViZXJzdG9yZmZyZWlidXJnc3dpdHplcmxhbmQ

### ISSUE THREAD

**Issue by rogeralthaus** [helium/explorer#1034]
### What happened?

A bug happened!

### URL

https://explorer.helium.com/hotspots/cities/dWViZXJzdG9yZmZyZWlidXJnc3dpdHplcmxhbmQ

### What browsers are you seeing the problem on?

Chrome

### Do you see the issue on Mobile or Desktop?

Desktop

**Comment by cokes518** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/19331274/188704665-29653298-59e2-4ebc-9672-024f23fa9798.png">

looks to be working now.
