### ISSUE TITLE
[Bug]: 404 error at URL: /txns/av7V_aeKpiI4ogLDKj764sQWh98cQxGLZXxhfhT9RUY

### ISSUE THREAD

**Issue by Koreleth** [helium/explorer#1035]
### What happened?

I cant set my antenna to 4,5 DB and 11 high meters

### URL

https://explorer.helium.com/txns/av7V_aeKpiI4ogLDKj764sQWh98cQxGLZXxhfhT9RUY

### What browsers are you seeing the problem on?

Chrome

**Comment by cokes518** [comment]
looks like the transaction cleared and displays correctly with 4.5 dbi and 11 meters. just took some time for the transaction to clear and show up.

<img width="424" alt="image" src="https://user-images.githubusercontent.com/19331274/195223887-dd0659e1-c08e-44d1-b614-50a597cbaf05.png">
