### ISSUE TITLE
[Bug]: 404 error at URL: /txns/JVYXBwr51SRTPT0V3vOWFXhg2nb684e0XR6ik6gZS58

### ISSUE THREAD

**Issue by robertrittmuller** [helium/explorer#1039]
### What happened?

Unable to view transaction. Helium tokens were lost in this event so it should be investigated!

### URL

https://explorer.helium.com/txns/JVYXBwr51SRTPT0V3vOWFXhg2nb684e0XR6ik6gZS58

### What browsers are you seeing the problem on?

Safari

### Do you see the issue on Mobile or Desktop?

Mobile

**Comment by cokes518** [comment]
where did you get this transaction hash? from an exchange?
