### ISSUE TITLE
Show MOBILE earnings per Radio in the Explorer

### ISSUE THREAD

**Issue by meowshka** [helium/explorer#1040]
**5G Statistics tab**

- Add Hotspot MOBILE Earnings card. It should include:

> - Total Mobile earnings per selected period.
> - % change compared to the preceding period of the same length.
> - Toggle to choose periods: Yesterday, 7D, 14D, 30D.
> - Chart with earnings breakdown and comparison to the network average for the same period. Granularity depends on the period chosen with toggle.
> - Hovering over earnings chart shows earnings per selected day, depending on chosen granularity.
> - Tooltip for Earnings with text: _Earned rewards will appear on the Blockchain in about 30 minutes after the Reward Period ends._

- Add to each Radio card:
>- Earnings section with the same information as the above.
>- Reward multiplier
>- Tooltip for Reward multiplier with text: _Radio Type multiplier is used together with Speed Test multiplier to scale the MOBILE rewards._

- Speed Test card:
>- In tooltip text for Speed Test multiplier change "Radio type multiplier" to "Radio Type multiplier".

**Activity tab**
- Add:
>- Expandable Mobile earnings entry
>- Expandable view should show text: _Earned MOBILE rewards will appear on the Blockchain in about 30 minutes after the Reward Period ends. Please refer to the Account Activity tab for information about MOBILE Reward transactions on the Blockchain._

Figma> Explorer App > Hotspot > 5G Stats - MOBILE Earnings
<img width="428" alt="5G Stats - MOBILE Earnings" src="https://user-images.githubusercontent.com/5078844/205745506-4a0ba74e-edc7-4441-a8eb-ea655f7b356a.png">
<img width="428" alt="5G Stats - MOBILE Earnings Activit" src="https://user-images.githubusercontent.com/5078844/199984991-db5ebc0d-5b65-4651-beea-290dcb8ec8fa.png">
<img width="428" alt="5G Stats - MOBILE Earnings Activity Expanded" src="https://user-images.githubusercontent.com/5078844/199984989-d3e61f68-aeb1-4418-98c5-5485ad918ba1.png">

**Comment by sabondano** [comment]
@tyler-whitman here are the cbsd-id-prefix to cell-type mappings, AND the cell-type to multiplier mappings for when we need them:

https://github.com/helium/oracles/blob/4a9fe4df23b51d9db35ff285b415fcd8d0874ab8/poc_mobile_verifier/src/cell_type.rs#L33

**Comment by meowshka** [comment]
Done! Thank you.
