### ISSUE TITLE
[update] community tools

### ISSUE THREAD

**Issue by HiGregory** [helium/explorer#1046]
### What happened?

DataGovs as a community tool was removed 

[update community js](https://github.com/helium/explorer/pull/1012) when we put the following [IOS Application](https://apps.apple.com/us/app/datagovsmonitor/id1631878976) link up for notice and sent an update to the Helium / Nova team. 

### URL

https://github.com/helium/explorer/pull/1012

### What browsers are you seeing the problem on?

Chrome

### Do you see the issue on Mobile or Desktop?

Mobile

**Comment by cokes518** [comment]
@waveform06 mind adding datagovs back? ios link <https://apps.apple.com/us/app/datagovsmonitor/id1631878976>

**Comment by HiGregory** [comment]
Hi, @waveform06 any updates here?

**Comment by waveform06** [comment]
I opened pull request 1049 10 days ago
