### ISSUE TITLE
[Bug]: 404 error at URL: /hotspots/112dAjrh1GQp8LvJ2DBajdegWSVtLFmqJYmMRSrKMj31QrNn4Z28

### ISSUE THREAD

**Issue by serkannecan** [helium/explorer#1050]
### What happened?

A bug happened! zero beacon zero witness

### URL

https://explorer.helium.com/hotspots/112dAjrh1GQp8LvJ2DBajdegWSVtLFmqJYmMRSrKMj31QrNn4Z28

### What browsers are you seeing the problem on?

Chrome

### Do you see the issue on Mobile or Desktop?

Mobile, Desktop

**Comment by cokes518** [comment]
i recommend you reach out to #hotspot-help on discord to understand why your hotspot does not have any beacons or witnesses. i'll have to close this since it isn't an explorer issue.

discord: discord.gg/helium
