### ISSUE TITLE
[Bug]: 404 error at URL: /hotspots/112dAjrh1GQXXXXXXX

### ISSUE THREAD

**Issue by serkannecan** [helium/explorer#1051]
### What happened?

A bug happened!

### URL

https://explorer.helium.com/hotspots/112dAjrh1GQXXXXXXX

### What browsers are you seeing the problem on?

Chrome

### Do you see the issue on Mobile or Desktop?

Mobile

**Comment by cokes518** [comment]
this isn't a valid hotspot b58 address, can you check the url?

**Comment by baynetwifi** [comment]
404 — Not Found
