### ISSUE TITLE
[Bug]: Amount Displayed on Max Payment is Confusing

### ISSUE THREAD

**Issue by lthiery** [helium/explorer#1053]
### What happened?

When displaying max payments, some other value is being displayed:
![image](https://user-images.githubusercontent.com/1606640/192155636-e628f5e2-a109-46ce-a5a2-d7ca347cf2aa.png)

It is probably a lot of work to actually derive the amount, but is it possible to replace `-0.04` with `max`?

### URL

https://testnet-explorer.helium.com/accounts/1bLRjBMvHwNW7RCvLyVDQEzRhEErsdCiaHdwXBWgdwYgbsenmot/activity

### What browsers are you seeing the problem on?

Chrome

### Do you see the issue on Mobile or Desktop?

Desktop

**Comment by lthiery** [comment]
@madninja you mentioned there's an ETL PR for this that actually would derive the amount?

**Comment by sunnya23** [comment]
@madninja Any news for this? Could it be modified to at least show "max" or something similar instead of negative numbers? It also wrong on the tx detailpage:
https://testnet-explorer.helium.com/txns/guqxtP26_3_GXSstlUhDGW-exbpQZ8_pa7ZRBq7-_os
