### ISSUE TITLE
[Bug]: 404 error at URL: /hotspots/cities/c2xpdmVuc2xpdmVuYnVsZ2FyaWE

### ISSUE THREAD

**Issue by haleksandrov** [helium/explorer#1056]
### What happened?

A bug happened!
When click on city get bug

### URL

https://explorer.helium.com/hotspots/cities/c2xpdmVuc2xpdmVuYnVsZ2FyaWE

### What browsers are you seeing the problem on?

Chrome

### Do you see the issue on Mobile or Desktop?

Mobile, Desktop

**Comment by cokes518** [comment]
city loads as expected. please see screenshot. might have been a hiccup with the API at the time.

<img width="433" alt="image" src="https://user-images.githubusercontent.com/19331274/195223660-0e5a08ad-24a4-4af9-b676-d3b254999aa0.png">
