### ISSUE TITLE
[Bug]: 404 error at URL: /txns/TveCieiCwE8ac9HPDv74dgzzqiHJZQ04MgAj8g51NEo

### ISSUE THREAD

**Issue by SpiralaS** [helium/explorer#1058]
### What happened?

A bug happened!

### URL

https://explorer.helium.com/txns/TveCieiCwE8ac9HPDv74dgzzqiHJZQ04MgAj8g51NEo

### What browsers are you seeing the problem on?

Chrome

### Do you see the issue on Mobile or Desktop?

Mobile

**Comment by cokes518** [comment]
this has cleared, sometimes a transaction has to clear the chain and show up in the database before it can load. 
<img width="431" alt="image" src="https://user-images.githubusercontent.com/19331274/195628674-b5d28adc-8db4-4495-ae6b-923c53b0371f.png">
