### ISSUE TITLE
Add support of 4 Speed Test tiers for info only

### ISSUE THREAD

**Issue by meowshka** [helium/explorer#1059]
Break down display of Speed Test results into 4 tiers:

- Acceptable (>100 Mbps download / >10 Mbps upload / <50 ms latency) - 1X reward
- Degraded (>50 Mbps download / >5 Mbps upload / <75 ms latency) - 0.5X reward
- Poor (>30 Mbps download / >2 Mbps upload / <100 ms latency) - 0.25X reward
- Fail (any of three values below Poor tier would make a Speed Test failed) - 0X rewards

Foundation announcement: https://discord.com/channels/404106811252408320/730418759298318346/1029483894023671870
<img width="428" alt="5G Stats - Speed DL Failed" src="https://user-images.githubusercontent.com/5078844/195934221-586f4dd3-06e9-4e53-85da-1e7c95159465.png">
<img width="428" alt="5G Stats - Speed Test Failed DL, UL, latency" src="https://user-images.githubusercontent.com/5078844/195934957-9c9cb9df-0525-4dff-80eb-34751c61abe7.png">
<img width="428" alt="5G Stats - Speed Test Failed DL, UL (1)" src="https://user-images.githubusercontent.com/5078844/195942756-18fe7d2f-65ac-4a51-ad42-c04ba6da0f18.png">
<img width="428" alt="5G Stats - Speed Test No Data" src="https://user-images.githubusercontent.com/5078844/195713161-7be08229-a790-4b06-a7a9-f38cba64c676.png">
<img width="428" alt="5G Stats - Speed Test Passed" src="https://user-images.githubusercontent.com/5078844/195713164-50040e92-def9-4fcc-88ca-1f3318c41fde.png">

**Comment by Ryan-Goldstein** [comment]
As some people in #5g-cbrs in the Helium Discord have pointed out, the second image conflicts with the Foundation announcement:

![image](https://user-images.githubusercontent.com/8300089/195718434-36f9cc1a-53f2-47c0-baae-1d92ef1cd9a5.png)

80ms would be considered Poor, not Degraded.

Additionally, the two 'greater than' symbols should be 'less than' symbols:

> Degraded: >75 ms
> Poor: >100 ms

Should be:

> Degraded: <75 ms
> Poor: <100 ms

**Comment by meowshka** [comment]
Than you @Ryan-Goldstein for bringing up the issues! We've re-worked UI to make the tiers more clear in general.
