### ISSUE TITLE
[Bug]: 404 error at URL: /txns/ShEv7_JAMt9EI8ZKQUL3t5K4yz677aAtL-u9IqGflxM

### ISSUE THREAD

**Issue by Mezedawi** [helium/explorer#1062]
### What happened?

Hi, 
why are the HNT tokens gone? The Transaction failed!!

### URL

https://explorer.helium.com/txns/ShEv7_JAMt9EI8ZKQUL3t5K4yz677aAtL-u9IqGflxM

### What browsers are you seeing the problem on?

Chrome

### Do you see the issue on Mobile or Desktop?

Desktop

**Comment by Saltyfly** [comment]
I had this happen to two brand new miners this week.
