### ISSUE TITLE
[Bug]: 404 error at URL: /txns/LfG7K3vGI3HJQ9rdvTS2pcNBu4STOwzGrX2KE0N5jbY

### ISSUE THREAD

**Issue by Saltyfly** [helium/explorer#1069]
### What happened?

A bug happened!

### URL

Why did the network onboard my miner charge the fee and not add it to the blockchain.

### What browsers are you seeing the problem on?

Chrome

### Do you see the issue on Mobile or Desktop?

Mobile, Desktop

**Comment by Ryan-Goldstein** [comment]
What is your hotspot's three word animal name?

**Comment by Saltyfly** [comment]
Recumbent Pecan Tadpole
