### ISSUE TITLE
[Bug]: 404 error at URL: /txns/0x4d473a7938e1517ea9a710a8604d00e94ea438caa46e1b8e5744de79608c040b

### ISSUE THREAD

**Issue by baytraderman** [helium/explorer#1073]
### What happened?

A bug happened! - I was trying to transfer LRC from crypto.com exchange directly to my Loopring wallet but they've not arrived and trasnaction is marked as complete on Crypto.com exchange, I realise i should have used layer swap as I have before. Is there any way to reverse the transaction ?

### URL

https://explorer.helium.com/txns/0x4d473a7938e1517ea9a710a8604d00e94ea438caa46e1b8e5744de79608c040b

### What browsers are you seeing the problem on?

Chrome

### Do you see the issue on Mobile or Desktop?

Desktop

**Comment by cokes518** [comment]
LRC is not a token on the Helium network. you're reporting a bug on the Helium blockchain.
