### ISSUE TITLE
[Bug]: 404 error at URL: /txns/g6ys2FrSNux2Y3qzPcENeHFXCDX702jO2TUGT5cEuVM

### ISSUE THREAD

**Issue by Houssamforhelium** [helium/explorer#1074]
### What happened?

A bug happened!

### URL

https://explorer.helium.com/txns/g6ys2FrSNux2Y3qzPcENeHFXCDX702jO2TUGT5cEuVM

### What browsers are you seeing the problem on?

Opera

### Do you see the issue on Mobile or Desktop?

Mobile

**Comment by cokes518** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/19331274/202536255-b33560c5-3160-42fb-8493-6356b93eae56.png">

looks like it finally loaded. there was an api outage when you reported this issue yesterday. it should be resolved now.

**Comment by Houssamforhelium** [comment]
Dear,

Please note that the activation is still 2 weeks ago as u can see in the
attached screenshot. Should I wait for some more time?

Best regards,
Houssam
