### ISSUE TITLE
[Bug]: 404 error at URL: /txns/WIm9tU2_Ru7ez576VNw2C2DV2TCzYAV4Jsa6EdqAwPI

### ISSUE THREAD

**Issue by charlesiury** [helium/explorer#1076]
### What happened?

A bug happened! I transfered my HNT cripto from Binance to HNT Helium Wallet (Beta) and when I access the Txid link in Binance It shows, in Helium Blockchain, that the transacional was not found :( I need to recover my HNT. Please, I need your help to understand where até my cripto and why It is not appearing in the Wallet. Thank you.

### URL

txns/WIm9tU2_Ru7ez576VNw2C2DV2TCzYAV4Jsa6EdqAwPI

### What browsers are you seeing the problem on?

Chrome

### Do you see the issue on Mobile or Desktop?

Mobile

**Comment by cokes518** [comment]
hi there, the API had a 24+ hour outage plus there was a chain halt last night that prevented any transactions from hitting the blockchain. This is why no HNT transferred from your binance account. Both the API and blockchain are currently recovering, so I would recommend you trying the transfer again tomorrow when it has stabilized. apologies.
