### ISSUE TITLE
[Bug]: 404 error at URL: /txns/vyOrtSGxVo_1ojqOBcE_ix1zaaTRkNVaPMvb9hWGqCk

### ISSUE THREAD

**Issue by Shrekis** [helium/explorer#1077]
### What happened?

A bug happened! No hnt transferred no transaction record found. Transferred from binance to hnt wallet

### URL

Binance to Helium Wallet

### What browsers are you seeing the problem on?

Safari

### Do you see the issue on Mobile or Desktop?

Mobile

**Comment by cokes518** [comment]
hi there, the API had a 24+ hour outage plus there was a chain halt last night that prevented any transactions from hitting the blockchain. This is why no HNT transferred from your binance account. Both the API and blockchain are currently recovering, so I would recommend you trying the transfer again tomorrow when it has stabilized. apologies.
