### ISSUE TITLE
Offline Hotspot Recognition

### ISSUE THREAD

**Issue by Vestibule22** [helium/explorer#109]
Update Explorer to identify "offline" hotspots to help others looking to place new hotspots and to help existing hotspots know this is likely the reason they are not witnessing these hotspots.  A few ideas of how this can happen.

1. Change the dot color of an offline hotspot to red on explore map (Possibly use additional colors to establish a length of time the hotspot has been offline.  Main reason is that some hotspots might go offline for a day or two but there are others offline for 2+ months
2. Possibility of remove of hotpots that have been offline after a certain period of time (Timeline would need to be discussed but 1 month might be a good start)
3. Change dot color next to hotspot name in "hotspots nearby" section to red from the yellow/orange color it currently is.

**Comment by cokes518** [comment]
1. Let's use red (#E86161) for offline hotspots. To keep the scope of this new feature small, we will forgo adding the logic to change colors if the Hotspot has been offline for a longer period of time.

2. Explorer is a view of the blockchain, taking those offline hotspots off the map would not be a true indication of what is part of the blockchain. I'd recommend not doing this.

3. no change required if we use red for offline hotspots.

**Comment by danielcolinjames** [comment]
(note for hackathon: if no one takes this by tomorrow I will probably remove the Hackathon label and take it on myself 🙂  )

**Comment by filoozom** [comment]
Wouldn't this require an update to the `/api/coverage` endpoint? Or how do you know if a given hotspot is having issues? Querying the `/hotspots/:address` surely isn't a viable option.

**Comment by danielcolinjames** [comment]
I haven't actually looked at the code very deeply but I think each hotspot should have a `hotspot.status.online` field we can use to conditionally change the dot colours

**Comment by filoozom** [comment]
I missed the fact that `/api/coverage` is in this codebase and not the actual blockchain API (and thus didn't find what I was looking for), so forget what I said haha.

I'll take this one too then 🙂

**Comment by danielcolinjames** [comment]
ahh yeah Next's `/pages/api` routes are pretty cool :) sweet! 🔥

**Comment by filoozom** [comment]
With offline hotspots prioritized:
![image](https://user-images.githubusercontent.com/6319092/108828163-cc825500-75c6-11eb-9235-34b0ccc22843.png)

With online ones:
![image](https://user-images.githubusercontent.com/6319092/108828334-02bfd480-75c7-11eb-9a94-d9ed6fba2614.png)

The latter looks quite a bit better, and the first one seems a bit exaggerated. But none of them give an accurate impression of how many nodes are online (14884) vs offline (3587). Maybe a bit of transparence should be added?

**Comment by danielcolinjames** [comment]
ahh sorry just saw this comment @filoozom . I think the second one is probably best, but yeah agree some transparency could help make it look a little nicer. was thinking it could even be nice to have a little bit of a blur around each one
