### ISSUE TITLE
Hi,my helium in  on denylist  my name helium is howling lime chinChilla

### ISSUE THREAD

**Issue by chinchila5353** [helium/explorer#1091]

**Comment by chinchila5353** [comment]
My address hotspot : 11S5wvSm6Lj3vYiJghQvDmJqrLW8RAsTjWQBpW2ZH7TdGWNkii1

**Comment by Ryan-Goldstein** [comment]
This is not the correct place for that. You can submit a denylist removal request at https://crowdspot.io/ by pressing `Submit Denylist Request`, specifying that it's a removal request. Make sure to provide sufficient evidence to prove that it's legitimately deployed.

**Comment by chinchila5353** [comment]
Hi dear I've already did that , didn't help can u help me to solve the issue

**Comment by Ryan-Goldstein** [comment]
You'll need to be patient - it may take a few days or weeks for the reviewers to go through the removal requests, and if the evidence indicates it's a legitimately deployed hotspot, they'll remove it from the denylist at that time. This is not the correct place for that request.
