### ISSUE TITLE
[Bug]: 404 error at URL: /hotspots/cities/cG9sdGF2YXBvbHRhdnMna2Egb2JsYXN0dWtyYWluZQ

### ISSUE THREAD

**Issue by P-A-R-U-S** [helium/explorer#1094]
### What happened?

A bug happened!

### URL

https://explorer.helium.com/hotspots/cities/a3JlbWVuY2h1a3BvbHRhdnMna2Egb2JsYXN0dWtyYWluZQ

### What browsers are you seeing the problem on?

Firefox

### Relevant log output

```shell
Not able to select hotspot by town name: https://explorer.helium.com/hotspots/cities/a3JlbWVuY2h1a3BvbHRhdnMna2Egb2JsYXN0dWtyYWluZQ
```

**Comment by samgutentag** [comment]
can you try: https://explorer.helium.com/iot/cities/a3JlbWVuY2h1a3BvbHRhdnMna2Egb2JsYXN0dWtyYWluZQ/hotspots

**Comment by P-A-R-U-S** [comment]
Yes, looks like URL are not correct. Here is what you have on web-site: **https://explorer.helium.com/hotspots/cities/**Y2hlcmthc3ljaGVya2FzJ2thIG9ibGFzdHVrcmFpbmU and it doesn't work, but if I change it to [https://explorer.helium.com/iot/cities](https://explorer.helium.com/iot/cities/Y2hlcmthc3ljaGVya2FzJ2thIG9ibGFzdHVrcmFpbmU/hotspots) - it works fine.
