### ISSUE TITLE
[Bug]: 404 error at URL: /txns/ICSRph6g5elC8fsqq8PcoVNut8M7TtbvnTOBxKBBNSU

### ISSUE THREAD

**Issue by CamiloAgc** [helium/explorer#1096]
### What happened?

A bug happened!

when you start a new hotspot, during the registration. The transaction fail.

### URL

Heliumexplorer

### What browsers are you seeing the problem on?

Safari

### Do you see the issue on Mobile or Desktop?

Mobile

**Comment by cokes518** [comment]
hi @CamiloAgc can you confirm which app you set the location from? Is it from the MNTD app? this is the error i'm seeing from the API side. the transaction failed because of a bad signature from MNTD:

```{
"updated_at": "2023-01-06T08:55:17.634578Z",
"type": "assert_location_v2",
"txn": {
"type": "assert_location_v2",
"staking_fee": 1000000,
"payer": "14h2zf1gEr9NmvDb2U53qucLN2jLrKU1ECBoxGnSnQ6tiT6V2kM",
"owner": "13poi1LkHXoYPoShvR1VeANXUh7pEbAjXakJSSoCWgNfDFuP7sW",
"nonce": 1,
"location": "8cbe6341492c9ff",
"hash": "ICSRph6g5elC8fsqq8PcoVNut8M7TtbvnTOBxKBBNSU",
"gateway": "11VQ2gv42pDiYuP77AgF7vYw3xjhoRebFJhyTyNxRzac7e7DoRJ",
"gain": 28,
"fee": 55000,
"elevation": 3
},
"status": "failed",
"hash": "ICSRph6g5elC8fsqq8PcoVNut8M7TtbvnTOBxKBBNSU",
"failed_reason": "{invalid,bad_payer_signature}",
"created_at": "2023-01-06T08:54:51.400574Z"
}```

**Comment by CamiloAgc** [comment]
Yea is a MNTD app in the iOS system

**Comment by illumina23** [comment]
I have never been able to assert a gain value above 15.  The transaction always fails when any higher value is used.
