### ISSUE TITLE
explorer shows wrong Hex and inaccurate (about 600m) location[Bug]: 

### ISSUE THREAD

**Issue by Donvito777** [helium/explorer#1102]
### What happened?

A bug happened!
PC explorer.
![image](https://user-images.githubusercontent.com/115641104/212587793-4bac1c5d-9836-4b51-96c1-bdf467d4b6e5.png)

Hotspotty Mobile App explorer
![image](https://user-images.githubusercontent.com/115641104/212587992-fbb44fe1-be8b-4d71-afab-b0c90f7dceba.png)

### URL

https://explorer.helium.com/hotspots/11bBcySTME8ArUxRH31BmctoWNjugN8eAp3KcDizddhh1VzDtcV

### What browsers are you seeing the problem on?

Chrome, Brave, Firefox

### Do you see the issue on Mobile or Desktop?

Desktop

### Relevant log output

```shell
No errors just inaccurate location that I suspect my be a reason to be placed on the denylist.
```

**Comment by Ryan-Goldstein** [comment]
Explorer just approximates the hex boundaries. The real boundaries are made up of resolution 12 hexes. You can see the actual hex boundaries on Hotspotty: https://app.hotspotty.net/hexes/881e21b30dfffff/transmit-scale/neighbor-hexes

As you can see, your hotspot is located in the correct resolution 8 hex based on the actual hex boundary:

![image](https://user-images.githubusercontent.com/8300089/212588597-78022a10-b377-44a1-a108-6423334143f5.png)
