### ISSUE TITLE
Old location showing hotspot even though asserted in New location and synced 2 weeks ago

### ISSUE THREAD

**Issue by waveform06** [helium/explorer#114]
Hotspot is Macho Wintergreen Jellyfish, if I open up the coverage map I can see a green dot at the old location (UK Postcode KT6 6DQ) if I click on it it shows me the correct info on the Hotspot selected. If I click on the name it highlights the old location. If I change the zoom scale and then search for the Hotspot it will locate it at the new location (UK Postcode KT6 5BZ - 1.3 miles south). Mappers.helium.com reports correct location.
There are currently 3 hotspots at the new location - till our covid lockdown is over.

![](https://cdn.discordapp.com/attachments/750533049623773304/785634801965203507/Screen_Shot_2020-12-07_at_2.31.41_PM.png)

![](https://cdn.discordapp.com/attachments/750533049623773304/785635970467889242/macho.JPG)

![](https://cdn.discordapp.com/attachments/750533049623773304/785636913805262848/mappers.JPG)

**Comment by cokes518** [comment]
this should be fixed now. PR#129
