### ISSUE TITLE
CSV export should be able to show all fees or expenses (e.g. location assert)

### ISSUE THREAD

**Issue by danielcolinjames** [helium/explorer#118]
Some users may be using CSV exports to hand off to their accounting department, and so the transactions that get included in the CSV should probably include anything that could be counted as an expense.

Relevant code in /components/ExportCSV/ExportModal:
```
const { address } = this.props
    const { startDate, endDate, txn, fee } = this.state

    const filterTypes = []
    if (txn.includes('payment')) filterTypes.push('payment_v1', 'payment_v2')
    if (txn.includes('reward')) filterTypes.push('rewards_v1')

    const list = await this.client.account(address).activity.list({
      filterTypes,
    })
```

Need to look into it more, but I think it could look something like adding a line like this:
```
    if (txn.includes('fee')) filterTypes.push('assert_location_v1', '...')
```
And it could potentially just be an option instead of the default behaviour.

Relevant conversation here: https://discord.com/channels/404106811252408320/750533049623773304/786412623377858560

**Comment by jiceorange** [comment]
My wish is for an option to include all transactions that affect the balance (positive or negative). These transactions seem to be visible in the UI, so would be great to include in the export csv file as well. Most likely use case is for accounting. If you think they should not be included by default, that is OK, as long as there is an option to include all.
