### ISSUE TITLE
Make assert location transaction detail page look nicer

### ISSUE THREAD

**Issue by danielcolinjames** [helium/explorer#121]
Right now it's just using the default fallback where it dumps the JSON in a table. Should be really easy to at least show a map of the asserted location and create links to the account and the hotspot page.

E.g.: https://explorer.helium.com/txns/rzZc7rLqqGlMwoHPquu7RQ3fSnCuZlVI85wOJvNrQTo

**Comment by Vagabond** [comment]
This would be very helpful, additionally if the hotspot is moving (ie. it's not the first assert) you could show where it moved from.
