### ISSUE TITLE
Add better and more helpful error pages

### ISSUE THREAD

**Issue by danielcolinjames** [helium/explorer#124]
The Explorer should have customized error pages, for example the generic 404 page with links to the most common pages, or when a 500 error happens we should probably catch it and display something a bit friendlier than the default Next.js error page. Next.js has an easy way to add a custom 404 page, and a custom page for 500 errors: https://nextjs.org/docs/advanced-features/custom-error-page

We can also use `notFound` in getStaticProps to display a custom 404 page for different types of pages. For example if someone went to /blocks/40000000, we could show a "This block doesn't exist yet. The newest block is block x." or something like that.

This functionality should be fairly straightforward to add, and nothing too special is required in terms of design—these error pages can reuse the layout components so that they will still have the nav bar and footer.

**Comment by cokes518** [comment]
Hackathon: when the error page work is done, let the Helium team know in discord and we'll generate a nice graphic to go on the page.

**Comment by Astrochamp** [comment]
Would be happy to give this one a try

**Comment by danielcolinjames** [comment]
@Astrochamp  amazing! assigned it to you :) feel free to reply here and let me know if you have any questions!

**Comment by SourishS17** [comment]
Hey, I know @Astrochamp and we have decided we can work together on this one - would that be ok?

**Comment by danielcolinjames** [comment]
totally! :D yeah this is probably a bit of a bigger one actually so I think you'll each be eligible for your own swag if you take this one on together. feel free to reach out if you're unsure about anything or have any questions or want any feedback! excited to have you both contributing 🔥

**Comment by DGKSK8LIFE** [comment]
Do you need another assignee for this issue? @danielcolinjames

**Comment by danielcolinjames** [comment]
hey @DGKSK8LIFE I think it seems like @Astrochamp and @SourishS17 have got a handle on it for now but you can reach out to them to see if they needed any help!

**Comment by DGKSK8LIFE** [comment]
@danielcolinjames Sure! @Astrochamp @SourishS17 would you be willing to allow me to assist you in development? My discord is: `DGK#5762`

**Comment by danielcolinjames** [comment]
hey @Astrochamp and @SourishS17 , any updates on the progress of this issue? :) if you haven't finished  or got busy with other projects you could always open a draft PR so someone else can pick up where you left off

**Comment by SourishS17** [comment]
Should be done by next week - we are now trying to get the 500 error page to integrate with the rest of the code and then customize some messages :)

**Comment by danielcolinjames** [comment]
awesome! great to hear. please let me know if you want any design input or anything! I think you could probably reuse the `<AppLayout>` component on the error page files so that they'll still have the nav bar and footer included

**Comment by cokes518** [comment]
hi @SourishS17 and @Astrochamp  ! Our hackathon has officially ended but we'd like to give you an opportunity to complete this open issue and receive credit for the work. 

Please make sure to submit the finished PR by March 8! Thank you for your contributions! 💪
