### ISSUE TITLE
CSV export is missing some columns

### ISSUE THREAD

**Issue by woodlandsquash** [helium/explorer#125]
CSV Export does not include the transaction HASH

**Comment by danielcolinjames** [comment]
would also be useful to include the then current oracle price in each line of the export, as requested here: https://discord.com/channels/404106811252408320/750533049623773304/798668544384434217

**Comment by timtamothee** [comment]
Would it be possible to add an export CSV feature for individual Hotspots? I've seen this requested a few times and think it would be useful, not sure how difficult it would be @danielcolinjames.

**Comment by jiceman** [comment]
Looking forward to the Oracle price column.

**Comment by filoozom** [comment]
I'll take a shot at this one. Is there an exhaustive list of missing fields? Should I only add hash and oracle price?

**Comment by nickhough** [comment]
> Would it be possible to add an export CSV feature for individual Hotspots? I've seen this requested a few times and think it would be useful, not sure how difficult it would be @danielcolinjames.

Addressed in PR-175: https://github.com/helium/explorer/pull/175

**Comment by danielcolinjames** [comment]
hash was added, and it was decided that we won't add oracle / market price for now
