### ISSUE TITLE
Difficult to get to specific hotspot's rewards

### ISSUE THREAD

**Issue by jamiew** [helium/explorer#13]
If I am a user interested in seeing the breakdown of a given hotspot's rewards, it is quite difficult to get from the hotspot's page to the actual reward entry inside the mining rewards txn.

e.g. for the hotspot `gorgeus-purple-fox`:

https://explorer.helium.com/hotspots/112STWVQvGHbSmPgc7J1f1dQ6ZqEtYScvHHdCFSXzXTvuoRxK2Vr

![Screen Shot 2020-09-01 at 3 36 03 PM](https://user-images.githubusercontent.com/1903/91897912-faff2300-ec68-11ea-9950-590d720a8f36.png)

There is a link to a recent mining reward txn:

https://explorer.helium.com/txns/j9VrzBSCWxctjEVS0KdyCa6TAZpLEM1jolrrMaVunKQ

![Screen Shot 2020-09-01 at 3 37 09 PM](https://user-images.githubusercontent.com/1903/91897966-0ce0c600-ec69-11ea-8486-538e44d75a7f.png)

But clicking that link takes you to the top of a massive, 30+ page list, rather than jumping you to this particular hotspot's rewards inside that txn:

![Screen Shot 2020-09-01 at 3 37 24 PM](https://user-images.githubusercontent.com/1903/91898002-1c600f00-ec69-11ea-819c-49489bbf7231.png)

Since this list is sorted by HNT quantity descending, I am able to find the specific hotspot's reward by taking the reward amount (`0.05 HNT`) and the owner address (`14Mjr...`), jumping randomly towards the end of the list since it's a small amount, then paging manually and using cmd-F/cmd-G until I found it

![Screen Shot 2020-09-01 at 3 39 43 PM](https://user-images.githubusercontent.com/1903/91898348-955f6680-ec69-11ea-9b46-99cb3e7e8090.png)

**Comment by fredev** [comment]
Hi, I ran into the same problem as you and the same thing happens on the `/accounts/:address` page

This is an example of the data structure of a reward

```json
{
  "account": "131uJzWiF6PFE2GiGTzwap3Ckos1W2SqtQHrkKLKGNx6PTgyXqr",
  "amount": 51545871,
  "gateway": "112NqzAsAFyrTzvKEAdo3GfR8crQHngpucULV47FbxVTt2NkCLKp",
  "type": "poc_witnesses"
}
```

Looking at the data we could think of filtering the detail page based on the url

In the `/hotspots/:address` page the link to the reward should be `/txns/:txns_address/hotspot/:hotspot_address`
In the `/accounts/:address` page the link to the reward should be `/txns/:txns_address/account/:account_address`

So we can filter the list and view only the rewards of a specific hotspot or account address.

In both situations we can provide an action to view all the rewards of the block.

**Comment by fredev** [comment]
I'm doing tests on how to view the rewards details of an hotspot coming from `/hotspots/:address`, below a screenshot.

![Schermata 2020-09-08 alle 06 52 33](https://user-images.githubusercontent.com/5547669/92434388-faeab000-f19f-11ea-8414-49574ec2cd8a.png)

**Comment by fredev** [comment]
A second option would be to make the rewards list in the `/hotspots/:address` page expandable

At the time of the expansion the details of the transaction are requested from the backend and after processing rewards are shown

**Comment by cokes518** [comment]
Hi @jamiew and @fredev. we'll be sunsetting the old explorer in the coming weeks and will be focusing new development efforts on explorer v2. If this is still an issue on explorer v2, do you mind filing another issue? thanks!

**Comment by jamiew** [comment]
Close close close

This one is ancient
