### ISSUE TITLE
Show consensus group on the landing page

### ISSUE THREAD

**Issue by vihu** [helium/explorer#138]
![image](https://user-images.githubusercontent.com/3199183/104232730-99fd0e00-5405-11eb-8f32-cb2ad40f0496.png)

Can we please add the number of consensus group (and potentially linking it to the current CG) right on the landing page? We do the same on the app (under the Network section) and it would be helpful to have it right there on the landing page. It basically is the number of DKGs we've run on the chain so far and that's an achievement we should flaunt ;)

**Comment by pauljohn1983** [comment]
My idea would be on the homescreen to turn the picture of the rak miner or original hotspot when you are part of the consensus group yellow and make everyone aware of there luck they have received it's a bit of fun and it would make you check your app daily. Good luck everyone we are on to something good here enjoy your journey everyone. Paul👍

**Comment by cokes518** [comment]
@danielcolinjames would be good to get this completed in the next week or so (I know there's a hackathon label on here, but it's a bit more urgent now). Once we remove consensus group details in the app, there will be no way for anyone to see current election times or group information.

**Comment by danielcolinjames** [comment]
@cokes518  awesome good to know thanks, that's definitely doable 👍   can even probably start on it tomorrow

**Comment by pauljohn1983** [comment]
👍 good job
