### ISSUE TITLE
View transmitting hotspots witnessed in addition to receiving witnessing hotspots

### ISSUE THREAD

**Issue by qwick745** [helium/explorer#143]
Currently witness list shows other hotspots that have received a beacon from the hotspot in question showing successful transmission from the hotspot (these hotspots can see me). As reception is just as important, it would be good to also have a second witness list/button to enable the user to view all the hotspots that the hotspot in question has been able to receive a beacon from (I can see these hotspots).

**Comment by cokes518** [comment]
dupe of #144
