### ISSUE TITLE
Inverse of witness list, enhanced

### ISSUE THREAD

**Issue by GP-Colorado** [helium/explorer#144]
A list of hotspots that have recently witnessed my hotspot might be even more useful than the current witness list.
What would be ideal would be a single list, combining both, including  % of beacons heard _over the past week_, in each direction.
_Updating daily_ would  suffice.

Here's a mockup:

Hotspot | Location | Distance | RSSI Local | RSSI Remote | %Heard Local | %Heard Remote
-- | -- | -- | -- | -- | -- | --
Straight   Pebble Mammoth | Denver,   CO, United States | 1.2   km | -86 dBm | -83 dBm | 18% | 23%
Cold Sky   Goblin | Denver,   CO, United States | 18   km |   | -86 dBm | 0% | 3%
Digital   Seaweed Fish | Denver,   CO, United States | 490   m | -93 dBm | -90 dBm | 89% | 75%
Stable Pebble   Dragonfly | Denver,   CO, United States | 2   km | -94 dBm |   | 14% | 0%
Slow Blonde   Beetle | Denver,   CO, United States | 1.9   km | -87 dBm | -87 dBm | 50% | 64%

**Comment by GP-Colorado** [comment]
To clarify terminology in mockup:  
My hotspot hears Straight Pebble Mammoth on 18% of its beacons, with RSSI of -86 dBm, while Straight Pebble Mammoth hears mine 23% of the time with RSSI of -83dBM.

**Comment by cvolkernick** [comment]
Full support for this, came to suggest the same and was glad to find that others shared in the desire for this. Thanks for suggesting @GP-Colorado!

It seems that if the network values receiving data more than transmitting data, visualizing only a hotspot's successfully witnessed beacons is leaving out more than half of the picture. Explorer as a tool is often used to visualize the performance of a given hotspot in the interest of optimization, so giving no clear aggregate indicators of who a given hotspot is witnessing is a bit like driving blind.

Thanks again for the suggestion, really hope this makes it in soon! :)

**Comment by GP-Colorado** [comment]
It's been almost seven months since I posted this. I had forgotten  about it.

**Comment by cvolkernick** [comment]
I had been wanting to submit the suggestion and was pointed here by the team so at least it's on their radar in some capacity. 👍

**Comment by GP-Colorado** [comment]
That's encouraging!

**Comment by cokes518** [comment]
just a matter of typing now. we have the data we need 🙌🏼

**Comment by waveform06** [comment]
> It's been almost seven months since I posted this. I had forgotten about it.

Since then have you also seen  https://helium.hiker.rocks/ and its challenge analysis which has more textual detail than I assume this will have at release

**Comment by cokes518** [comment]
this is now live as part of witnessed list.
