### ISSUE TITLE
There are two differently named UK province/region that are the same province/region

### ISSUE THREAD

**Issue by waveform06** [helium/explorer#146]
Explorer thinks that the UK has 5 province/regions or whatever subdivisions of a country outside the US are named in Helium. There are only 4 in the UK, England, Scotland, Northern Ireland and Wales.  Helium Explorer/Sitebot has an additional 7 hotspots residing in Cymru which is the welsh language name for Wales not a separate province/region
https://www.sitebot.com/helium/hotspots/?view=list&country=GB&state=Cymru
https://www.sitebot.com/helium/hotspots/?view=list&country=GB&state=Wales
6 of the 7 of are owned by an account with most in wales, looks like a selection error allowing Cymru in the past.
On the english language website they should all be assigned to the english identifier.

**Comment by waveform06** [comment]
And also to note your 2 letter abbreviation for the UK is GB (Great Britain) - but you also include Northern Ireland in that. Northern Ireland is not in GB but it is in the UK. As Britain is an Island next to the Island of Ireland

**Comment by cokes518** [comment]
This comes from google geocoding and we aren't able to fix this.
