### ISSUE TITLE
'Access-Control-Allow-Origin' header error on Helium API calls

### ISSUE THREAD

**Issue by anthonyra** [helium/explorer#154]
The following error exists when loading data from the Helium API.

`Access to XMLHttpRequest at 'https://api.helium.io/v1/*' from origin 'https://explorer.helium.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

A quick google search resulted in the following page: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin

With my community app (helium.watch) I was able to catch this error by running a Heroku server that caught those blocks and routed them with the header attached for my site. This is probably not ideal (costs me $8/mo with low site traffic) and maybe there could be a way to add new sites to the header during the API process? Or they just recommend using the wildcard `*` in the header for public APIs.

**Comment by cokes518** [comment]
This issue belongs to blockchain http: https://github.com/helium/blockchain-http/issues

Can you refile over there?
