### ISSUE TITLE
Explorer displays, "An unexpected error has occurred" when trying to visit the webapp

### ISSUE THREAD

**Issue by DGKSK8LIFE** [helium/explorer#156]
![image](https://user-images.githubusercontent.com/45473363/105849948-b1f89400-5fa6-11eb-9f21-6e78ad6d7130.png)

**Comment by danielcolinjames** [comment]
hey @DGKSK8LIFE , thanks for reporting. was this error persistent, or did it go away after a little bit?

and was it on a specific page or the whole site?

**Comment by DGKSK8LIFE** [comment]
@danielcolinjames At the time of visiting, it was on the whole site. Now it has gone away. Not sure what happened.

**Comment by cokes518** [comment]
Closing this.. looks like it doesn't happen anymore.
