### ISSUE TITLE
When an account has no hotspots, make the hotspots table look nicer

### ISSUE THREAD

**Issue by danielcolinjames** [helium/explorer#157]
Right now it looks like this when an account has no hotspots:

![Screen Shot 2021-01-26 at 1 04 02 PM](https://user-images.githubusercontent.com/10648471/105906310-5cd57600-5fd8-11eb-82af-6581f5e239e5.png)

We could probably do a logical check for how many hotspots there are and then show the table like it's shown now if hotspots.length !== 0, else show a message that says "Account has no hotspots" or something along those lines

**Comment by MohdImran001** [comment]
Hey @danielcolinjames. I would like to work on it. Please give me a dummy url which will give me an empty list so that I can test my changes.

**Comment by danielcolinjames** [comment]
@MohdImran001 awesome!

here's an example URL: https://explorer.helium.com/accounts/14Xe1o8fNHqGQii78AAG3tvv6gfqB2jdUG8dvHW8oZoTZrjF83H

just to make sure you're aware though, I didn't add the "Hackathon" label to this one because I think it'll only be a few lines of code to fix it

if you're okay with that and just wanted to contribute to the repo I'll go ahead and assign you anyway :) but if you were hoping to get some swag, take a look at [the issues with the hackathon label](https://github.com/helium/explorer/labels/Hackathon) on them and see which one you want to take on. let me know

**Comment by MohdImran001** [comment]
No worries @danielcolinjames. I just want to contribute. You guys already helped me  during Hacktoberfest. 😊

**Comment by danielcolinjames** [comment]
fantastic! 😄  well we're very excited to have you contributing! I've assigned you the issue—let me know if you have any questions at all and I'd be more than happy to help

**Comment by MohdImran001** [comment]
Hey @danielcolinjames, on my system even after a very small change, it takes a lot of time to build that page. It is taking around 10 seconds to build a single page. is there anything that I could do to speed up the process?
