### ISSUE TITLE
Add functionality to generate and save Payment QR codes as a file

### ISSUE THREAD

**Issue by cokes518** [helium/explorer#158]
As a user, allow me to generate and save a QR code that the Hotspot App can scan and populate for common and frequent payment transactions.

Scanning a QR code instead of typing can reduce errors. Adding a nickname to generated QR codes that can be saved as a file will enable those with frequent payments (i.e patrons, rev-share) allows users to identify recipients by a common name instead of a string of characters.

This is a good stop-gap for the address book feature requested for the Hotspot App, and starts the initial work to enable staking and delegating.

**Recipient**: this field will be b58-validated address. add a check to confirm this address is compatible with Helium. This is a required field.

**Nickname**: this field will be a user-supplied string. do not allow scripts or special characters. alphanumeric only. not required. Add a character limit of 120 chars.

**HNT amount**: this field will be user-supplied. numbers only, decimals allowed. not required.

Once these fields are populated, a user can click "Create QR code", with a QR code appearing in the right panel. The QR code will encode information entered on the left panel.

Save As .. will open a system dialog to save the QR code as an image file.

More details can be found in Figma.

<img width="655" alt="image" src="https://user-images.githubusercontent.com/19331274/106044830-1db92a80-6095-11eb-9cf2-8cbe1734981e.png">

**Comment by DGKSK8LIFE** [comment]
interesting idea. Would be willing to assist the development of this functionality, if anyone would like to assign me or collaborate with me to add this feature. l
