### ISSUE TITLE
Use Helium API Circulating Supply

### ISSUE THREAD

**Issue by madninja** [helium/explorer#180]
Currently the circulating supply tile on https://explorer.helium.com/market seems to imply it's being fetched from Coingecko. 

Can we get this fixed to use our API and have some indication that the Coingecko link is just a reference to another place to go check out for market data?

**Comment by MattCarlos96** [comment]
Hello! I would love to work on this one. In addition to changing to use Helium API, do you have any preference for an indication that the link is to another place? My first ideas are using "Other sources" or "More data" instead of "View more"?

**Comment by danielcolinjames** [comment]
@MattCarlos96  great! I've assigned it to you 😄 

I think "View external source" sounds good to me, maybe @cokes518  could chime in if she could think of something else in terms of wording, or other things that could be changed on that page
