### ISSUE TITLE
Total HNT for CSV period

### ISSUE THREAD

**Issue by timtamothee** [helium/explorer#182]
For $HNT rewards CSVs for individual Hotspots and whole wallets, some of the most common questions are the total $HNT for the CSV and the Oracle Price at the time of each reward transaction.

This issue is focused on the total $HNT for a rewards-focused CSV, displayed somewhere on the CSV.

**Comment by jiceorange** [comment]
Totals are easy enough to specify in a spread sheet program of your choice. But adding the Oracle price is interesting. It is already requested in https://github.com/helium/explorer/issues/125 if you would like to give it a thumbs up there.

**Comment by timtamothee** [comment]
> Totals are easy enough to specify in a spread sheet program of your choice. But adding the Oracle price is interesting. It is already requested in #125 if you would like to give it a thumbs up there.

Definitely like the addition of Oracle Price to CSVs, gave it a thumbs up.

**Comment by cokes518** [comment]
We'll be retiring csv export in explorer v2 and directing users to community created tools.
