### ISSUE TITLE
Mapbox distance indicator in bottom right seems to be off when zoomed out very far

### ISSUE THREAD

**Issue by danielcolinjames** [helium/explorer#185]
Spotted by @nickhough :

![image](https://user-images.githubusercontent.com/10648471/106970400-9fe2c800-6701-11eb-9e59-2b6569737cc8.png)
![image](https://user-images.githubusercontent.com/10648471/106970417-a4a77c00-6701-11eb-8f45-03d8e9817d16.png)

Seems to be showing 50km when the actual distance of that line would actually be much much larger than that

I'm not sure why, or how to fix it, and it's not super high priority because the scale is probably mostly useful at a very zoomed-in view, but wanted to document this anyway

**Comment by guiferrpereira** [comment]
@danielcolinjames it seems that is a known issue: https://github.com/alex3165/react-mapbox-gl/issues/720, apparently switching to `mapboxgl.ScaleControl` might fix this

**Comment by danielcolinjames** [comment]
there's also a z-index thing happening: ![Screen Shot 2021-02-16 at 9 43 43 AM](https://user-images.githubusercontent.com/10648471/108100977-7e57d980-703b-11eb-9180-9698d4944a99.png)
