### ISSUE TITLE
Show hotspot name in Mining Reward accordion on account page

### ISSUE THREAD

**Issue by philltran** [helium/explorer#19]
On https://explorer.helium.com/accounts/{account_address} page it would be nice to see the Hotspot associated with a reward when the "Mining Reward" accordion is expanded. 

![image](https://user-images.githubusercontent.com/812816/95200952-38e1f080-07ad-11eb-8849-9e040cb36131.png)

**Comment by danielcolinjames** [comment]
Fixed by #39
