### ISSUE TITLE
Add transaction summaries for transactions in block detail page

### ISSUE THREAD

**Issue by danielcolinjames** [helium/explorer#190]
It could be useful to have it so on the block detail page, instead of the transaction hash column, we could make that column called "Details" instead, and show a really short, 1-liner summary of the transaction.

What it looks like now:
![Screen Shot 2021-02-05 at 1 59 36 PM](https://user-images.githubusercontent.com/10648471/107093647-776ad480-67ba-11eb-8e6e-fddcac6b8bcb.png)

How it could look (made with inspect element):
![Screen Shot 2021-02-05 at 2 24 01 PM](https://user-images.githubusercontent.com/10648471/107095552-de3dbd00-67bd-11eb-86f2-d9f5fb876e6b.png)

The solution would need to account for all the most common transaction types and then a default output that would work well (e.g. something like: if the txn has an `.amount` field, show that, otherwise show `txn.hash`). I'm not sure what the best summary would be for each transaction type, but for example, I think something like this could work:

"A challenge constructed by Dapper Hickory Meerkat, witnessed by 24 Hotspots" for a beacon challenge (a txn with `txn.type === poc_receipts_v1` and `txn.path.length === 1`)

A really good place to start when thinking of how to summarize each transaction type could be looking at the `getMetaTagsForTransaction` function in `/components/Txns/utils.js`

And then the TxnTag on the left could become a clickable link like in the ActivityList component.

And the text in the details column could probably stay as a link to that transaction's detail page like the hash is now.

Feel free to reach out to me here (or on Discord in the #explorer-dev channel) if you want any copy suggestions or ideas of what to include in the summary text for the various transaction types!

Here's a list (not exhaustive) of some of the most common transaction types, as well as some example transactions of each type in case that's helpful (you'll have to go to the /blocks page of each):
Transaction type | Transaction page | Block page
--- | --- | ---
payment_v1 | localhost:3000/txns/6T-kEEiO0KmKQul4HFBHS98qdwXm1UrrQ3oL6x7mTM8 | localhost:3000/blocks/139992
payment_v2 | localhost:3000/txns/LmCnApgeKkpFLo2J3-FET0FysD6mAqY1Wr6EN5wOjXU | localhost:3000/blocks/621535
poc_request_v1 | localhost:3000/txns/IJvGDfbQGROJ2ycQwjTXaaGLXbHBEhQQDhaQHNTKkwk | localhost:3000/blocks/621540
poc_receipts_v1 with only 1 hotspot (beacon) | localhost:3000/txns/tI3XoWXEJTI0USEwugur8RNSUC2DOT0yLTc4gFz_P7k | localhost:3000/blocks/621540
poc_receipts_v1 with 4 hops | localhost:3000/txns/_nf-OOGiMM7fD_hR_1-xBmADPZNTNmQdByM50nEYMKc | localhost:3000/blocks/621537
rewards_v1 | localhost:3000/txns/HbmLoyZBGai7VsjotYOAP9KP-wrpmOfal8RYyKEMTew | localhost:3000/blocks/621538
state_channel_close_v1 | localhost:3000/txns/tj5HgInHASt-PUUO5NdniH-09b3BSe3xfzLbAiuEvzM | localhost:3000/blocks/621540
state_channel_open_v1 | localhost:3000/txns/EFE24whJnD5ThaawPpQxzP4dIECkBUB7KbQhxvIfDMM | localhost:3000/blocks/621540
assert_location_v1 | localhost:3000/txns/TlyotGbYrC7aB2-39weVcdPy10m6nQTUnxuleWF7a3s | localhost:3000/blocks/621532
consensus_group_v1 | localhost:3000/txns/bYLJnCHL2bH9eqhipwOE0EjJql_KV_AAJizlBdKQFO4 | localhost:3000/blocks/621538
add_gateway_v1 | localhost:3000/txns/JTTbEw2Ws9VS8rr9T7WDu93KW86YJGffXR7u16jJIyE | localhost:3000/blocks/615140
transfer_hotspot_v1 | localhost:3000/txns/LEPWBEFqzfclM5UAbQWwlEppZvh9cxo3j8vbUe2gmYI | localhost:3000/blocks/616843

**Comment by danielcolinjames** [comment]
@guiferrpereira  yes, definitely! 😄   just assigned it to you. sorry to take awhile to get back to you on this

**Comment by guiferrpereira** [comment]
i will work on it this weekend ;) thanks

**Comment by cokes518** [comment]
hi @guiferrpereira ! Our hackathon has officially ended but we'd like to give you an opportunity to complete this open issue and receive credit for the work. 

Please make sure to submit the finished PR by March 8! Thank you for your contribution! 💪
