### ISSUE TITLE
Fix "x / page" dropdown on tables of hotspots

### ISSUE THREAD

**Issue by danielcolinjames** [helium/explorer#191]
Currently the "5 / page" dropdown doesn't accept different values when you try to change it. I haven't looked into why that happens or how to make it work, but I believe it has to do with the way the Ant Design table is implemented, and maybe that value is supposed to be bound to a state variable or something. Documentation of the Table here: https://ant.design/components/table/

It would be good if the default was still 5, but if that number could be changed if desired.

This happens in the following places:
- Recent witnesses list on hotspot page
- Nearby hotspots list on hotspot page
- Hotpots list on account page

As always, if you want to take this on and have any questions, let me know here or in the #explorer-dev channel on Discord! :)

**Comment by MohdImran001** [comment]
Hey @danielcolinjames,

I would like to work on this issue. It would be great if you could share some screenshots and a URL. It will help me to understand the problem thoroughly.

**Comment by danielcolinjames** [comment]
@MohdImran001 awesome! assigning it to you :)

and yeah for sure, here is a screen capture of the issue:
![2021-02-08 13 46 43](https://user-images.githubusercontent.com/10648471/107288315-1c361d80-6a18-11eb-8c2b-3ed93d19c783.gif)

on this page: https://explorer.helium.com/accounts/146yE8AatTo5oKjanEEbDePciqdRs4kQ35dcTMAkstx67sLNUqZ

**Comment by filoozom** [comment]
I think there needs to be an `onChange` on the `Table`, check this out: https://codesandbox.io/s/8js74?file=/index.js (from the documentation: https://ant.design/components/table/)

**Comment by MohdImran001** [comment]
Thanks @filoozom , I will definitely look into it.

**Comment by danielcolinjames** [comment]
closed by #207 :)
