### ISSUE TITLE
Pie chart transaction type names become unreadable

### ISSUE THREAD

**Issue by danielcolinjames** [helium/explorer#200]
The names of the transaction types in the pie chart on the block detail page (`/pages/blocks/[blockid].js`) become unreadable with some colours.

E.g.:

![Screen Shot 2021-02-09 at 11 04 32 AM](https://user-images.githubusercontent.com/10648471/107414299-a9d04680-6ac6-11eb-8431-748782056e48.png)

on: https://explorer.helium.com/blocks/712479

Perhaps they should all be white for now, or we can take another look at the colour palette. The names should also probably be converted to their "human-readable" format instead of just returning the way they look in the JSON for `txn.type`. There's a utility function to do that in one of the files (I believe in the TxnTag component maybe? But not 100% sure without checking.)

**Comment by guiferrpereira** [comment]
<img width="530" alt="Screenshot 2021-02-11 at 02 29 40" src="https://user-images.githubusercontent.com/756762/107596874-00499c00-6c11-11eb-8c9b-6bd329ca4dcc.png">

**Comment by filoozom** [comment]
> The names should also probably be converted to their "human-readable" format instead of just returning the way they look in the JSON for `txn.type`. There's a utility function to do that in one of the files (I believe in the TxnTag component maybe? But not 100% sure without checking.)

I was actually going to do this at some point, but I guess I forgot! Yes, it's the `getName` function in `TxnTag`.

@guiferrpereira has it all figured out though!

**Comment by danielcolinjames** [comment]
fixed by #205 :)
