### ISSUE TITLE
Seeing the Closest Hotspots to a Location

### ISSUE THREAD

**Issue by timtamothee** [helium/explorer#203]
I think an option to search for a location or address and see the list of closest Hotspots to that location would be useful to those who are looking to order a Hotspot. This will help see the distance of any other Hotspots nearby for Proof of Coverage before getting started.

I'm picturing the view for this could be similar to how it currently is for searching for a Hotspot and seeing nearby Hotspots on the map and in the chart below the map, except searching for a specific address or location instead of for a Hotspot. Not sure if the code from "Nearby Hotspots" would be able to be repurposed for this.

**Comment by cokes518** [comment]
related to #274
