### ISSUE TITLE
Fix docs link post docs.helium.com switchover 

### ISSUE THREAD

**Issue by PharkMillups** [helium/explorer#209]
We have some links 404'ing from the old dev docs url. 

https://explorer.helium.com/market

Oracle, DC Price, and HNT / DC links need fixing. New links are:

- https://docs.helium.com/blockchain/oracles
- https://docs.helium.com/blockchain/helium-token/#data-credits-and-burn-and-mint-economics

**Comment by danielcolinjames** [comment]
fixed by #208 :)
