### ISSUE TITLE
Make witnesses list in the explorer collapsible

### ISSUE THREAD

**Issue by Oektann** [helium/explorer#21]
On the explorer page make the witnesses list collapsible and remember the choice:

-Witnesses shown:
![image](https://user-images.githubusercontent.com/19311031/95223239-59b73f80-07c7-11eb-9cbb-24dfe3da40f7.png)

-Witnesses collapsed:
![image](https://user-images.githubusercontent.com/19311031/95223648-d518f100-07c7-11eb-8072-d598942060ed.png)

**Comment by cokes518** [comment]
For the hackathon: do not remember whether the witness table was expanded or collapsed. the default should be expanded.

**Comment by danielcolinjames** [comment]
Notes for hackathon:
- You might want to take a look at the [Collapse component](https://ant.design/components/collapse/) in the Ant Design library. It's not really intended to be layered around a table, so it might not be the most elegant solution. You can look at one implementation of it in the following file: `/components/Txns/PocReceiptsV1.js`

**Comment by cokes518** [comment]
Hi @Oektann . we'll be sunsetting the old explorer in the coming weeks and will be focusing new development efforts on explorer v2. If this is still an issue on explorer v2, do you mind filing another issue? thanks!
