### ISSUE TITLE
Payments missing from owner page csv report

### ISSUE THREAD

**Issue by Faeskee** [helium/explorer#212]
Hello,

Sending over a heads up that I pulled a csv report for 2020 from my owner page on explorer and it was missing payments sent. I double checked my filters and everything looks good so I believe it may be a bug. 

thanks for looking!

**Comment by PharkMillups** [comment]
Thanks for the issue. Can you give us the inputs we can reproduce?

**Comment by Faeskee** [comment]
Hello,

I was attempting to run a csv for all rewards and payments for this wallet 

https://explorer.helium.com/accounts/13va5CLgoZkP17fawQTHmVYG7esbMfgWty4LEa8MPkz96zYBvGu

Dates were 8/1/2020 - 12/31/2020

Thanks!

**Comment by Faeskee** [comment]
I see the csv issue ended up on the hackathon list. Thanks yo!

**Comment by danielcolinjames** [comment]
hmm @Faeskee I just tried exporting a CSV with that time range and I'm seeing all 5 payment transactions from 2020 showing up correctly in the generated CSV: 
![Screen Shot 2021-02-25 at 2 07 55 PM](https://user-images.githubusercontent.com/10648471/109226077-085a1d80-7773-11eb-8031-91a2045a7052.png)
![Screen Shot 2021-02-25 at 2 08 38 PM](https://user-images.githubusercontent.com/10648471/109226080-08f2b400-7773-11eb-9ddb-da11b9ff9d15.png)

closing for now, but happy to re-open if I'm missing something!

thanks for reporting, and please let me know if you're still experiencing this issue or if I'm misunderstanding the issue and I'll investigate further 🙂
