### ISSUE TITLE
Improve zoom controls on Mapbox on /consensus and /coverage pages

### ISSUE THREAD

**Issue by danielcolinjames** [helium/explorer#217]
You can see the default styled `<ZoomControl />` on http://explorer.helium.com/consensus : 
![Screen Shot 2021-02-17 at 11 11 44 AM](https://user-images.githubusercontent.com/10648471/108255442-2390b180-7111-11eb-8577-e46f16e8294e.png)

Obviously they don't look the nicest. On the coverage map https://explorer.helium.com/coverage
, the ones we have in the bottom right are a bit nicer: 
![Screen Shot 2021-02-17 at 11 13 54 AM](https://user-images.githubusercontent.com/10648471/108255530-402ce980-7111-11eb-9f8a-3b2523e281b8.png): 

but when I built those, I didn't realize there was already a built-in way (the `<ZoomControl />` component) to add +/- zoom buttons to a Mapbox. (Which might also be the cause of issue #69.)

And when I was building the /consensus page, I couldn't figure out how to style the ZoomControl component, and didn't want to go down a rabbit hole. There's the `style` prop, but it doesn't really give you granular styling control over each button, so we'd probably have to manually override the class names in the `explorer.css` file at the root of the project.

And one last thing, the zoom controls (and the reset button) on the consensus Mapbox could probably be moved to the bottom right to match the ones on the coverage map.

**Comment by MohdImran001** [comment]
@danielcolinjames. I would like to work on it.

**Comment by danielcolinjames** [comment]
@MohdImran001  awesome! assigning you to the issue. 

and good question, I think using`<ZoomControl />` is probably better since it's built in and will generally be more performant than my manual solution. I'm just not sure the best way to approach styling it, but feel free to take a stab at the styling in whatever way you can get working and looking nicer than the default styling :) I think ideally it would look something like the current coverage map buttons but not sure how hard that'll be

**Comment by cokes518** [comment]
hi @MohdImran001 ! Our hackathon has officially ended but we'd like to give you an opportunity to complete this open issue and receive credit for the work. 

Please make sure to submit the finished PR by March 8! Thank you for your contributions! 💪

**Comment by MohdImran001** [comment]
Thank you @cokes518. I really appreciate it. I will try my best to complete it before 8th March
