### ISSUE TITLE
Change default zoom when challenge doesn't have any witnesses

### ISSUE THREAD

**Issue by danielcolinjames** [helium/explorer#219]
After I changed the challenge Mapbox to take in an array of lat/lons and centre the map around them, a case I didn't account for is when there is only one pair of lat/lon values. When there's only 1 (the hotspot being challenged), the map zooms in all the way, making it nearly impossible to get any sense of where it is or the surrounding space.

To be clear I'm talking about the file: `/components/Txns/PoCMapbox.js` and here's an example: https://explorer.helium.com/txns/1s8mitHjZvAwOvp4Xd737yQVhLiNGzFF9MGLrqILjCY

I think we could use a similar strategy to lines 70 – 97 of the file `/components/Hotspots/HotspotMapbox.js` where you would conditionally add the appropriate props to a props object and then add that props object to the Mapbox component.

Can probably use the same zoom level as is used in the Assert Location transaction Mapbox. Example here: https://explorer.helium.com/txns/7LGuYuiJNwtjc7bUdbCnbnEbmBCI4rJd5VkYvSJRaFw

**Comment by MohdImran001** [comment]
Hey @danielcolinjames, I'd like to give it a try.

**Comment by danielcolinjames** [comment]
@MohdImran001 you got it! 😄
