### ISSUE TITLE
Filter / hide hotspots at 0,0 lat/lon

### ISSUE THREAD

**Issue by danielcolinjames** [helium/explorer#221]
Right now, there is a cluster of hotspots showing up at 0,0 lat/lon on the map:
![Screen Shot 2021-02-17 at 2 02 36 PM](https://user-images.githubusercontent.com/10648471/108273727-d15b8a80-7128-11eb-93cd-9d79d410a651.png)

Those are hotspots that haven't had their location set yet. We should filter those and not display them on the map instead of showing them at 0,0.

**Comment by filoozom** [comment]
I'll take this one!

**Comment by danielcolinjames** [comment]
@filoozom nice 😄
