### ISSUE TITLE
Make "Include offline hotspots" option on coverage map

### ISSUE THREAD

**Issue by danielcolinjames** [helium/explorer#228]
Not too sure about the design of this, but @filoozom and I talked about it as something that can be built on top of #225 

It could probably be a simple check box underneath the number of hotspots with the text "Include offline hotspots", that would be checked by default, and when unchecked would update the big total number as well as make the map stop showing the offline hotspots.

**Comment by filoozom** [comment]
I'll take this one too while I'm at it.

**Comment by danielcolinjames** [comment]
closing because fixed by #229 :)
