### ISSUE TITLE
Changing Red dots to Orange in maps for hotspot offline for less then 10000 blocks

### ISSUE THREAD

**Issue by wishplorer** [helium/explorer#234]
It would be beneficial to show hotspot that are offline for smaller period of time in a different color on map. 

May be an orange dots for offline for 1 week (approx. 10000 blocks). That can guide users to make a decision around hotspot placement. Hotspot owners don't want to be surrounded by bunch of red ones but orange ones may be temporary so that could help in decision making.

Also, some hotspot are dead and will never come online. Is it possible to not shot them at all on map?

**Comment by danielcolinjames** [comment]
note to self, and/or whoever takes on this issue, but I think the colour could be `#FCC945` to match other parts of the Explorer and app. but it might be confusing to reuse the colour that is sometimes used for witnesses...

**Comment by Astrochamp** [comment]
I might give this a go today / tomorrow

**Comment by Astrochamp** [comment]
If #FCC945 is also used for witnesses, maybe #FCAA45 might be better?

**Comment by danielcolinjames** [comment]
@Astrochamp yeah good call, we can try a few different ones and see what feels right :)  could also try this one: `#EB9C53` which I found in the Figma files
