### ISSUE TITLE
Online/Offline icon on Nearby Hotspots incorrect

### ISSUE THREAD

**Issue by heliumredbeard** [helium/explorer#235]
It shows 'offline' for all hotspots regardless of actual status
<img width="662" alt="Screen Shot 2021-02-25 at 5 11 03 PM" src="https://user-images.githubusercontent.com/56279372/109240645-b3c39c00-778c-11eb-97d2-13c35c205b2b.png">

**Comment by danielcolinjames** [comment]
@allenan was just looking into this a bit, looks like it's because the temp wallet API for distance doesn't return a status field for the hotspots. we can probably just hide the status icon until we have a better API for distance if it's not an easy change on the API side
