### ISSUE TITLE
The letters "Ț" and "Ș" missing from Romania cities

### ISSUE THREAD

**Issue by Tripadus** [helium/explorer#237]
Hello!
After the last update, the map have some issue with Romanian cities/zones names, that includes special letters like "Ț" and "Ș".
I've check other cities from Cyprus (for example) that have the same special letters in name, but they are displayed right on the Explorer map.
Romania (few Examples):
Bucure(ș)ti
Domne(ș)ti
Pope(ș)ti-Leordeni
Dobroe(ș)ti
Ro(ș)u
Dragomire(ș)ti Vale
Eroii Revolu(ț)iei

Cyprus (few Examples):
Taşkınköy
Lefkoșa

You'll find attachments below
Have a nice day/night!

![Cyprus Cities](https://user-images.githubusercontent.com/79708529/109315940-bfc66100-7853-11eb-9054-15a236346015.png)
![Romania Cities](https://user-images.githubusercontent.com/79708529/109315943-c05ef780-7853-11eb-8e69-60c3d337cb7e.png)

**Comment by PeterMain** [comment]
Thanks!

Our Mapbox map used Lato, which didn't seem to support those characters, and so missed them off (!). I have changed the style over to a typeface with a larger range of glyphs.
