### ISSUE TITLE
Update assert_location details page

### ISSUE THREAD

**Issue by cokes518** [helium/explorer#249]
https://explorer.helium.com/txns/-kstkxCrVE8c4aoBNtWvDdV8QyhmAym8ZV4aY6gqLmM

The payer is actually CalChip, not (staking server). 
<img width="564" alt="image" src="https://user-images.githubusercontent.com/19331274/109837952-8c405980-7bfa-11eb-9308-0f2bf80e9c4d.png">

**Comment by danielcolinjames** [comment]
hey @allenan, working on this and it seems like the onboarding.dewi.org API isn't allowing any non-dewi.org requests... or maybe I'm misunderstanding. but I'm getting this:

![Screen Shot 2021-03-09 at 3 20 29 PM](https://user-images.githubusercontent.com/10648471/110533923-7c3de380-80ec-11eb-8348-112d27c15ea0.png)


where we get something similar but seemingly less restrictive (still gives the data in the response) when using the wallet API for the temp nearby hotspots fetch:

![Screen Shot 2021-03-09 at 3 20 17 PM](https://user-images.githubusercontent.com/10648471/110533998-937cd100-80ec-11eb-9671-f3939bd0a0ea.png)

it was failing on the second line here:
```js
const url = `https://onboarding.dewi.org/api/v2/makers`
const response = await fetch(url)
```

any suggestions on how to proceed?

**Comment by allenan** [comment]
I added a cors policy to the onboarding server
