### ISSUE TITLE
Hotspot maximum distance cap on map view

### ISSUE THREAD

**Issue by grantmoore3d** [helium/explorer#250]
I've seen a number of users on the /r/HeliumNetwork subreddit getting confused when a miner has been moved to a new location, but it still displays a connection thousands of KM away.

https://www.reddit.com/r/HeliumNetwork/comments/lx16om/how_is_this_possible_witnessing_hotspots_2500/

https://www.reddit.com/r/HeliumNetwork/comments/lwikn5/this_confused_medoes_this_person_own_a_device_in/

It would be helpful to cull connections from being displayed if they go beyond the theoretical maximum distance possible between miners (with some safety buffer, 2-3x theoretical). Would cut down on confusion with new miners.

**Comment by Astrochamp** [comment]
Hello from Reddit 🙂
What kind of distance do you have in mind for a cap?
