### ISSUE TITLE
Flags on consensus page missing and just showing shortcode country in black

### ISSUE THREAD

**Issue by BFGNeil** [helium/explorer#251]
![image](https://user-images.githubusercontent.com/79230094/109949863-cb8ea900-7cd3-11eb-91d2-feb26c7f9d28.png)
 
as shown the flags have gone leaving shortcode country codes in their place in black

**Comment by cokes518** [comment]
thanks for catching this!

**Comment by danielcolinjames** [comment]
looks like we can either add the svg prop to use svgs instead of emojis, or use this library to conditionally hide it if emojis aren't supported: https://github.com/danalloway/detect-emoji-support
