### ISSUE TITLE
Hiding "Load More" button when there are few txns also hides Add/Assert txns

### ISSUE THREAD

**Issue by heliumredbeard** [helium/explorer#255]
As these are valid (and useful) txns, they should still be shown along with other network activity
<img width="991" alt="Screen Shot 2021-03-04 at 3 49 23 PM" src="https://user-images.githubusercontent.com/56279372/110049583-f514f800-7d06-11eb-867c-fcaf12003a34.png">

**Comment by danielcolinjames** [comment]
fixed by #257
