### ISSUE TITLE
Disparity between CSV exported totals and current balance in wallet

### ISSUE THREAD

**Issue by danielcolinjames** [helium/explorer#259]
When exporting a CSV from an account and then doing:
`sum(all received amounts) - sum(all sent amounts) - sum(fees)`
in a spreadsheet program, the final number you get is slightly different than the account balance.

Reported on Discord here: https://discord.com/channels/404106811252408320/750533049623773304/817516968654405674

**Comment by Rafikiwi** [comment]
Here is a video showing the issue: https://youtu.be/bH4SH1anjPE

**Comment by cokes518** [comment]
related to #267 and #328
