### ISSUE TITLE
Transaction descriptions for each type

### ISSUE THREAD

**Issue by allenan** [helium/explorer#26]
There's a nice blurb on the reward transaction details view that describes what it is:

![image](https://user-images.githubusercontent.com/792845/95227126-bb79a880-07cb-11eb-8216-8b5e70fc2166.png)

All transaction types should have a similar blurb

**Comment by cokes518** [comment]
For Hackathon: when you submit the PR, Helium can provide guidance on copy.

**Comment by danielcolinjames** [comment]
note for hackathon: documenting a tentative yes from @PharkMillups on this one if no one else picks it up. or he could probably help with the copy if someone wants to collab on this with him :)
