### ISSUE TITLE
Validator version numbers

### ISSUE THREAD

**Issue by jdgemm** [helium/explorer#263]
In explorer provide:

* the latest validator version number
* the version number of individual validator nodes

Perhaps provide some visual indicator of validator nodes that are outdated.

This will allow stakers to clearly see if nodes are current or not. 

Dependencies:
https://github.com/helium/blockchain-http/issues/197
https://github.com/helium/miner/issues/683

**Comment by PeterMain** [comment]
what do you think @allenan ? We could add a column (though it is getting somewhat unwieldy) for version and have the latest version display in header block or stat box?

**Comment by cokes518** [comment]
this is done
