### ISSUE TITLE
New Hotspot Growth Metrics

### ISSUE THREAD

**Issue by timtamothee** [helium/explorer#270]
Some new metrics to show the Hotspot growth in different ways (day over day growth), charts of total monthly growth for previous months and the current month, or similar metrics could be a cool addition to Helium Explorer to show the growth progress of the network on the Hotspots page: https://explorer.helium.com/hotspots.

**Comment by cokes518** [comment]
is there anything more specific you'd like to see here @timtamothee?

**Comment by timtamothee** [comment]
@cokes518 here are some other ideas from the current stats:
1. A historical graph of total unique devices that have used the network
2. A historical graph of the total $HNT burned over time
3. A historical graph of total hexes with coverage over time

Also - for the "+19,xxx" Hotspots, "+8 countries," and similar stats addition and percentage stats shown, would it be useful for the timeframe to be added after each number? I've wondered what timeframe the changes are based on but haven't been sure. Thanks for considering.
