### ISSUE TITLE
Show all hotspots on Challengee maps, not just witnesses. 

### ISSUE THREAD

**Issue by PeterMain** [helium/explorer#272]
If a hotspot is surrounded by 20 close hotspots, and none are witnesses, it is clear to the user that placement needs fixing. This pressure to change positioning doesn't exist if the user can't see the other hotspots on the map to aim towards.

example:
https://explorer.helium.com/txns/IK1HAkCjGgIgJsYgfzbUQWWxoRlkXJyI47N7waYGQt8

there are 3 other hotspots hidden on this map, that this hotspot should be aiming to hit.

I'd probably extend this even further to say, that EVERY map we show always shows every hotspot.

**Comment by allenan** [comment]
We should unify the data that populates the coverage map as an optional layer for all of our mapbox instances. might also want use the new geospatial bounding box api
