### ISSUE TITLE
unstaked validators: display a countdown to let users know when original stake available

### ISSUE THREAD

**Issue by jdgemm** [helium/explorer#275]
For unstaked validators there is an unbonding period, currently approximately 5 months (250,000 blocks). During this period validator nodes do not earn rewards and the stake amount is inaccessible.

If a user unstakes a validator node display a countdown (time/blocks) that will let them know when their original stake will become available.

**Comment by cokes518** [comment]
This validator is in cool down, and there's no way for us to know when they entered cooldown/when it will be released:
https://api.helium.io/v1/validators/112PvBWVx1xE1zcSagAw1wcRDBxDE71qfjezkh8iryWyxZmQSfiM

this will need to be added to the API for explorer to know.
