### ISSUE TITLE
Tooltip for green vs cyan 'Payment' in account activity

### ISSUE THREAD

**Issue by davetapley** [helium/explorer#278]
I had to dig in to code to find out what green vs cyan is here:

<img width="290" alt="Screen Shot 2021-03-19 at 1 26 39 PM" src="https://user-images.githubusercontent.com/48232/111838600-cbd39a80-88b6-11eb-92d6-43d24a8a12b2.png">

https://github.com/helium/explorer/blob/a7f1b330d30ba15bfab8aeb3f38bfc86860a23a7/components/Txns/TxnTag.js#L6-L7

---

I'd open a PR, but I don't know what `payment_v1` vs `payment_v2` is 😁

**Comment by cokes518** [comment]
@PharkMillups I didn't find anything on payment_v1 or payment_v2 in dev docs. Maybe we can clarify there? Not sure if there's anything worth fixing in explorer at this time.

**Comment by davetapley** [comment]
I'm not a UX guy, but I'd also suggest just making them the same color if it's not something the the typical user would need to know about?
