### ISSUE TITLE
Show total HNT rewarded on reward txn view

### ISSUE THREAD

**Issue by allenan** [helium/explorer#28]
We should show the total amount rewarded in a reward txn as an attribute in the top section of the page.
<img width="944" alt="Screen Shot 2020-10-06 at 12 04 26 PM" src="https://user-images.githubusercontent.com/792845/95227513-317e0f80-07cc-11eb-8845-4d705a6f30c9.png">

**Comment by MohdImran001** [comment]
Hii @allenan, I'd love to work on this.

**Comment by allenan** [comment]
It's yours @MohdImran001. I was imagining some kind of icon and then the total next to it, like we show block height there as an attribute.

**Comment by MohdImran001** [comment]
Hii @allenan, do have any suggestions that what icon I should use from `ant-design` and It would be great if you could share a link to a sample reward transaction, it will help me to test my changes easily.

**Comment by MohdImran001** [comment]
Hey @allenan, sorry to press you and sorry for already sending you a message, but Hacktoberfest is ending soon and I need to make 2 more PR's to qualify. I am learning a lot from this project and I'd really appreciate it if you could share a link to a reward transaction and your suggestion about the icon.

**Comment by allenan** [comment]
Hey @MohdImran001 sorry missed your first message. Let's just use the `WalletOutlined` icon from ant for now. it'll be easy to swap out later

![image](https://user-images.githubusercontent.com/792845/96780469-c4b56880-13ba-11eb-8508-9c7ef5703466.png)

**Comment by MohdImran001** [comment]
Hii @allenan, It would be great if you could share a link to a reward transaction. it would help me to test my changes easily.

**Comment by allenan** [comment]
@MohdImran001 that would certainly be helpful :)

https://explorer.helium.com/txns/wIBfrVocgH97Y1jFBctmzntP50hdWx8h-gW7fu7p2qo

**Comment by allenan** [comment]
resolved by #59
