### ISSUE TITLE
Router device registration (xor filter update) transaction not displayed

### ISSUE THREAD

**Issue by disk91** [helium/explorer#289]
The explorer does not report this transaction. It would be important for statistic usage . It's not only a DC display issue but the whole transaction is not in the transaction history.

**Comment by cokes518** [comment]
@disk91 can you give us an example transaction so we can develop around it?

**Comment by cokes518** [comment]
Anything here @disk91 ?

**Comment by disk91** [comment]
Hi, 
My issue is not really clear out of context.
When you look at the activity of a router wallet, this history does not contains all the transaction burning DCs. As a consequence, it is difficult to know how the DCs has been consumed and what are your average cost for Device assertion as an example. Explorer should display the exhaustive list of DCs consumed.
Is that better like this ?

**Comment by cokes518** [comment]
ah ok. do you have a link for a router wallet?

**Comment by disk91** [comment]
Look at this wallet - https://explorer.helium.com/accounts/13HWrdkMoooYJEYz8LjKWzfK1oZifCzwxPaCnV9XDJbC5Gso1ic/activity
There is nothing about the DC consumption in explorer. Previously in explorer v1 we had some of the activity visible but not all activities. Now we have nothing. So it would be great to get some information about DC consumption. As indicated, the main reason are:
- Ability to predict when the DC balance needs to refund
- Ability to determine the DC consumption model in a given router between the different transactions. This is needed to build a pricing model.
- Transparency for customer on the way the Router are setup (state channel duration, device registration rate ...)
- Monitoring the Data Volume (through DC consumption on state channel) over the global Helium network or each of the Routers.

**Comment by cokes518** [comment]
no problem. all reasonable requests. just needed an example.
