### ISSUE TITLE
Challenge transaction uses default view

### ISSUE THREAD

**Issue by allenan** [helium/explorer#29]
The challenge txn page uses the default view: https://explorer.helium.com/txns/05VTgihGyUWI9CJdoZxx235MRpGIeip6B3XQe6bJXjg

Any addresses should be clickable at the very least.

**Comment by MohdImran001** [comment]
@allenan, I'd like to work on it. please suggest to me that to which page `secretHash `and `onionKeyHash `will point.

**Comment by Astrochamp** [comment]
I'm getting close to finishing the "nicer error pages" work with @SourishS17 , could we do this one too?

**Comment by danielcolinjames** [comment]
@Astrochamp awesome! excited to see your work 😄  and yeah you definitely can. I think this one will just count as 1 swag item though since it's a bit smaller :)

**Comment by cokes518** [comment]
hi @Astrochamp ! Our hackathon has officially ended but we'd like to give you an opportunity to complete this open issue and receive credit for the work. 

Please make sure to submit the finished PR by March 8! Thank you for your contributions! 💪
