### ISSUE TITLE
Map mobile issue

### ISSUE THREAD

**Issue by javina89** [helium/explorer#291]
When looking at the map on mobile, the hotspot lookup window on bottom takes half the screen. Are we able to pull it down to show more of the map?

![image0](https://user-images.githubusercontent.com/13725042/112913176-cf3d0200-90be-11eb-92e5-194d35cf4156.png)

**Comment by cokes518** [comment]
Thanks for the feedback. we're redoing the explorer app to be more mobile friendly and will be taking this into account in the redesign.
