### ISSUE TITLE
Individual validator node page

### ISSUE THREAD

**Issue by jdgemm** [helium/explorer#293]
Similar to individual page for Hotspots, provide an individual page for validator nodes:

Validator name

- software version:
- score
- Status: online/offline/relay
- Staked status: staked/unstaked  (if unstaked: unbonding period countdown)
- Peer address: 
- IP address: 
- Location:
- Amount staked and time of initial stake
- Rewards (24, 30, 1 year)
- Owner wallet address- clicks shows individual wallet page with list of validators tied to wallet:
     - validator name,
     - software version
     - score
     - status (online/offline/relay), 
     - staked status, 
     - rewards (24, 7, 1 yr)

Activity (time, block):

- Staked
- Unstaked
- Transferred stake
- Consensus Election

**Comment by rootulp** [comment]
The BeaconScan [individual validator page](https://beaconscan.com/validator/19030) may be helpful inspiration here.

Similar to BeaconScan, I think it would be super cool to have the ability to add a particular validator to a watchlist and get email notifications if the validator misbehaves or goes offline.

**Comment by cokes518** [comment]
This is done.
