### ISSUE TITLE
Can't access hotspots (500 error)

### ISSUE THREAD

**Issue by matthewj301** [helium/explorer#297]
Can't view hotspots 'dandy syrup leopard' or 'cheesy brunette beaver', getting a 500 error

**Comment by matthewj301** [comment]
OS: Android
Browser: Chrome

**Comment by matthewj301** [comment]
Sample url: https://explorer.helium.com/hotspots/11Ju6CmxT8AiHZCs3fvNpGN6yADkfxPLxxkjcoMEDU8upuDgZbk

**Comment by matthewj301** [comment]
Can access other hotspots

**Comment by matthewj301** [comment]
I can now access them, were there some API issues yesterday?

**Comment by cokes518** [comment]
yes there were.
