### ISSUE TITLE
Unused variables and other console warnings should be tidied up

### ISSUE THREAD

**Issue by danielcolinjames** [helium/explorer#30]
There are lots of console / terminal warnings when you run the project locally. Even if most of it gets fixed / ignored at build time, we should still clean it up for a better developer experience. Some of the warnings are things like adding `alt` tags for `<img>`s and things like `<div> can't be a child of <p>`

Should be pretty straightforward to tidy these up.

**Comment by MykolaKolotylo** [comment]
hey @danielcolinjames, can I try to do it?

**Comment by danielcolinjames** [comment]
Absolutely, please do! 😄   

No worries if you don't get all of them too, but even just deleting any unused imports from the top of each JS file would be helpful.

Thanks!

**Comment by MykolaKolotylo** [comment]
@danielcolinjames please take a look https://github.com/helium/explorer/pull/36

**Comment by danielcolinjames** [comment]
Fixed by #36
