### ISSUE TITLE
Inconsistency in filtering options for "account" endpoint

### ISSUE THREAD

**Issue by mfalkvidd** [helium/explorer#305]
For the account page/endpoint https://explorer.helium.com/accounts/<account>
csv export has the following checkboxes:
* Payments
* Rewards
* Hotspot Transfers
* Add Hotspots
* Location Asserts

while the activity filter has the following checkboxes:
* Mining Rewards
* Payment (v1)
* Payment (v2)
* Add Hotspot
* Assert Location
* Packets Transferred
* Transfer Hotspot
* Token Burn

It would be nice if the naming was consistent (ex: "Assert Location" vs "Location Asserts")
It would also be nice if the same options were available (csv export is currently lacking "Token burn", "Packets transferred")

**Comment by PeterMain** [comment]
likely causing the 30% difference from csv export/reality 
https://discord.com/channels/404106811252408320/730272677104713791/829626355255607306

**Comment by mfalkvidd** [comment]
Maybe the best way is to simply get rid of the csv export checkboxes, and always apply the settings selected in the activity filter? Less code, easier to maintain, less work for the user.

**Comment by mfalkvidd** [comment]
Note: The oui transaction is missing in both filters.

**Comment by cokes518** [comment]
We'll be retiring csv export in explorer v2 and directing users to community created tools.
