### ISSUE TITLE
Reroute requests to helium-js

### ISSUE THREAD

**Issue by cokes518** [helium/explorer#307]
There are a few instances where explorer talks to the API directly instead of helium-js. this makes it hard for us to switch between wtf and production.

**Comment by MohdImran001** [comment]
@danielcolinjames I would like to work on it.

**Comment by danielcolinjames** [comment]
@MohdImran001 awesome :) this task would mostly involve adding functionality to [helium-js](https://github.com/helium/helium-js) so let me know if you have any questions on how to get that project up and running locally or anything!

**Comment by MohdImran001** [comment]
Thank you @danielcolinjames. How I can test my changes done in helium.js? The task is to find where the explorer talks to the API directly and add that API into helium.js. is it correct ?

**Comment by danielcolinjames** [comment]
yup that's right regarding the task @MohdImran001 👍    you can just search the code for "api.helium" and that should help you find them. then it's just a matter of replicating the fields that are returned by the API directly

and this issue will be broken up into many different PRs for helium-js based on each different endpoint Explorer calls directly, so don't feel like you have to do it all in one go. for example I added this one recently: https://github.com/helium/helium-js/commit/e1e547f64d8efa892d29313ebb172c734b20ed9e

and to test helium-js locally there are some instructions on how to get it up and running and run the existing tests in the repo here: https://github.com/helium/helium-js/blob/master/CONTRIBUTING.md#running-helium-js-locally

and you can look at one of the existing test files to get a sense of the syntax they use and create new functions within those test files or create new test files :) but feel free to message me if you have more questions that this response doesn't answer!

**Comment by MohdImran001** [comment]
Hi @danielcolinjames, 

I found out that `withBlockHeight.js` component in explorer is talking to the API directly in `loadBlockHeight` function instead of helium.js. 

```
import React from 'react'
import Client from '@helium/http'

const withBlockHeight = (WrappedComponent) => {
  class BlockHeight extends React.Component {
    state = {
      height: 0,
      heightLoading: true,
    }

    componentDidMount() {
      this.client = new Client()
      this.loadBlockHeight()
      window.setInterval(this.loadBlockHeight, 5000)
    }

    loadBlockHeight = async () => {
      await fetch('https://api.helium.io/v1/blocks/height')
        .then((res) => res.json())
        .then((res) =>
          this.setState({ height: res.data.height, heightLoading: false }),
        )
        .catch((error) => console.log(error))
    }

    render() {
      const { height, heightLoading } = this.state

      return (
        <WrappedComponent
          {...this.props}
          height={height}
          heightLoading={heightLoading}
        />
      )
    }
  }
  return BlockHeight
}

export default withBlockHeight

```

There is already a function in `helium.js` to fetch the current block height. i.e. `await client.blocks.getHeight()`. 

Instead of using `this.fetch(api)` , I will replace it with `this.client.blocks.getHeight()`. I just want confirm whether it is the right approach or not.  I also would like to know whether `this.client` method uses `v1` or `v2` API by default.

**Comment by danielcolinjames** [comment]
that should work yeah! good find, I think that might be a recent addition to helium-js but can't remember offhand. but yeah that should work nicely, and that's basically what the process will be like for replacing these fetches on the Explorer side:
1. using `client.[whatever]` instead of `fetch([API URL])`
2. making sure any Explorer code that uses the response is refactored to expect the correct format when necessary (it might be formatted slightly differently in the response, e.g. any helium-js fields will be in `camelCase` while the API returns `snake_case` fields when they're >1 word)

hope that helps!

**Comment by danielcolinjames** [comment]
keeping this open since there are still some other direct API queries in Explorer :)

**Comment by MohdImran001** [comment]
Hi @danielcolinjames, 

I am working on `[hotspotid].js` page. I am facing a weird problem 😅. I am trying refactor the following snippet for fetching `Witnesses`.

```
      const witnesses = await fetch(
        `https://api.helium.io/v1/hotspots/${hotspotid}/witnesses`,
      )
        .then((res) => res.json())
        .then((json) => json.data.filter((w) => !(w.address === hotspotid)))

```
It gives the following response - 
```
	address: "11V3LT4FQo8GRKNUZrEHUJ57EQgHE6JA3ZWM6Q6y2mytwZSFefw"
	block: 835882
	block_added: 751954
	elevation: 0
	gain: 12
	geocode: {short_street: "121st Ave SE", short_state: "WA", short_country: "US", short_city: "Bellevue", long_street: "121st Avenue Southeast", …}
	last_change_block: 835834
	last_poc_challenge: 835643
	lat: 47.562378672749986
	lng: -122.17767445604963
	location: "8c28d551e4d2bff"
	name: "amateur-laurel-cobra"
	nonce: 1
	owner: "148f6FrFVro4Yoc9FBoWRPVrEMusDGWZew2zgeSWBybK2CHmNKW"
	reward_scale: 1
	status: {online: "online", listen_addrs: Array(1), height: 835754}
	timestamp_added: "2021-03-09T15:47:45.000000Z"
	witness_for: "112aRgPxohcf5K2c8dSPekTxvR7jfWsSd1miA9rGtWymSKmgqQ5w"
	witness_info: {recent_time: "1620452374927924918", histogram: {…}, first_time: "1620115755856241161"}
```

But the response from `helium/http` client is missing the following fields : - `witness_for` and `witness_info`.

`helium/http` snippet - 

```
      const client = new Client()
      let witnessesList = await client.hotspot(hotspotid).witnesses().list()
      console.log(witnessesList);
      let wit = []
      for await (const w of witnessesList) {
        wit.push(JSON.parse(JSON.stringify(w)))
      }
      console.log(wit)
```

Response Object - 
```
	address: "11V3LT4FQo8GRKNUZrEHUJ57EQgHE6JA3ZWM6Q6y2mytwZSFefw"
	block: 835882
	blockAdded: 751954
	client: {network: {…}, retry: 5}
	elevation: 0
	gain: 12
	geocode: {shortStreet: "121st Ave SE", shortState: "WA", shortCountry: "US", shortCity: 		"Bellevue", longStreet: "121st Avenue Southeast", …}
	lastChangeBlock: 835834
	lastPocChallenge: 835643
	lat: 47.562378672749986
	lng: -122.17767445604963
	location: "8c28d551e4d2bff"
	name: "amateur-laurel-cobra"
	nonce: 1
	owner: "148f6FrFVro4Yoc9FBoWRPVrEMusDGWZew2zgeSWBybK2CHmNKW"
	rewardScale: 1
	status: {online: "online", listen_addrs: Array(1), height: 835754}
	timestampAdded: "2021-03-09T15:47:45.000000Z"
```


Whereas both fields are present in Data Model of Witness in `helium/http` .

**Comment by MohdImran001** [comment]
> Hi @danielcolinjames,
> 
> I am working on `[hotspotid].js` page. I am facing a weird problem . I am trying refactor the following snippet for fetching `Witnesses`.
> 
> ```
>       const witnesses = await fetch(
>         `https://api.helium.io/v1/hotspots/${hotspotid}/witnesses`,
>       )
>         .then((res) => res.json())
>         .then((json) => json.data.filter((w) => !(w.address === hotspotid)))
> ```
> 
> It gives the following response -
> 
> ```
> 	address: "11V3LT4FQo8GRKNUZrEHUJ57EQgHE6JA3ZWM6Q6y2mytwZSFefw"
> 	block: 835882
> 	block_added: 751954
> 	elevation: 0
> 	gain: 12
> 	geocode: {short_street: "121st Ave SE", short_state: "WA", short_country: "US", short_city: "Bellevue", long_street: "121st Avenue Southeast", …}
> 	last_change_block: 835834
> 	last_poc_challenge: 835643
> 	lat: 47.562378672749986
> 	lng: -122.17767445604963
> 	location: "8c28d551e4d2bff"
> 	name: "amateur-laurel-cobra"
> 	nonce: 1
> 	owner: "148f6FrFVro4Yoc9FBoWRPVrEMusDGWZew2zgeSWBybK2CHmNKW"
> 	reward_scale: 1
> 	status: {online: "online", listen_addrs: Array(1), height: 835754}
> 	timestamp_added: "2021-03-09T15:47:45.000000Z"
> 	witness_for: "112aRgPxohcf5K2c8dSPekTxvR7jfWsSd1miA9rGtWymSKmgqQ5w"
> 	witness_info: {recent_time: "1620452374927924918", histogram: {…}, first_time: "1620115755856241161"}
> ```
> 
> But the response from `helium/http` client is missing the following fields : - `witness_for` and `witness_info`.
> 
> `helium/http` snippet -
> 
> ```
>       const client = new Client()
>       let witnessesList = await client.hotspot(hotspotid).witnesses().list()
>       console.log(witnessesList);
>       let wit = []
>       for await (const w of witnessesList) {
>         wit.push(JSON.parse(JSON.stringify(w)))
>       }
>       console.log(wit)
> ```
> 
> Response Object -
> 
> ```
> 	address: "11V3LT4FQo8GRKNUZrEHUJ57EQgHE6JA3ZWM6Q6y2mytwZSFefw"
> 	block: 835882
> 	blockAdded: 751954
> 	client: {network: {…}, retry: 5}
> 	elevation: 0
> 	gain: 12
> 	geocode: {shortStreet: "121st Ave SE", shortState: "WA", shortCountry: "US", shortCity: 		"Bellevue", longStreet: "121st Avenue Southeast", …}
> 	lastChangeBlock: 835834
> 	lastPocChallenge: 835643
> 	lat: 47.562378672749986
> 	lng: -122.17767445604963
> 	location: "8c28d551e4d2bff"
> 	name: "amateur-laurel-cobra"
> 	nonce: 1
> 	owner: "148f6FrFVro4Yoc9FBoWRPVrEMusDGWZew2zgeSWBybK2CHmNKW"
> 	rewardScale: 1
> 	status: {online: "online", listen_addrs: Array(1), height: 835754}
> 	timestampAdded: "2021-03-09T15:47:45.000000Z"
> ```
> 
> Whereas both fields are present in Data Model of Witness in `helium/http` .

@danielcolinjame. A gentle reminder for the above comment. 😄

**Comment by danielcolinjames** [comment]
@MohdImran001 hey, just wanted to apologize that I haven't answered you yet. I started looking into this but haven't had a chance to focus on it, I'll try to take a look and give you a proper response tomorrow! appreciate your patience :)

**Comment by danielcolinjames** [comment]
hey @MohdImran001 , so I've looked into it and I believe the problem here is that the `client.hotspot(hotspotid).witnesses().list()` function in helium-js is using the `HTTPHotspotObject` interface to construct its response, which doesn't include those fields

I started hacking away at something that I think could be a good fix and I'm going to push up some code to a branch on helium-js so you can run with it :)

**Comment by danielcolinjames** [comment]
@MohdImran001  here's the branch 🙂 

https://github.com/helium/helium-js/tree/add-witness-info-to-hotspot

this is the test I was running:
`yarn test /http/src/resources/__tests__/Hotspots.spec.ts`

feel free to DM me on Discord if you have any questions about the state I left that branch in too, hope that helps!

**Comment by MohdImran001** [comment]
Thank you @danielcolinjames. The issue was resolved after upgrading `@helium/http` to version 3.35.
