### ISSUE TITLE
Unexpected 404 error

### ISSUE THREAD

**Issue by hessel-crypto** [helium/explorer#313]
Hello,

I have a pretty unpleasant problem. I recently tried to withdraw HNT tokens from my binance account to my ledger wallet.

It has now been almost 48 hours since I made this withdrawal. The status on binance is still "processing" and the withdrawal has still not been confirmed.

When I navigate to the explorer to view the status of the transaction, "404, Sorry that page does seem to excist" appears.

So something is going very wrong with the transaction that I have absolutely no control over. At the same time, my coins are no longer accessible in binance.

I cannot trade or sell them, probably because they are "stuck" in a withdrawal.

This obviously worries me deeply as I currently do not have access to the tokens and their value. I worry I will never have acces to  my tokens again if this withdrawal keeps being "stuck".

It concerns an amount of 123.9322 helium tokens. I bought this a while ago with my savings...

Can you guys please help me here. I am very worried about this

txID: WgIAjVEGkCb7BLKBRoEcfIJPPWVsZO8HWLL6IsaK8Lg

the adress it was supposed to go to: 14msiZCWKgT5GhK9x5E6Z48Q7Huk4TjUqTRTiDDTX9wZXAd7vGD

![image](https://user-images.githubusercontent.com/82131320/114009479-79591e80-9863-11eb-907e-139befd939f8.png)

![image](https://user-images.githubusercontent.com/82131320/114009980-f1274900-9863-11eb-82ea-11d9bd5a1f9c.png)

**Comment by danielcolinjames** [comment]
Hi @hessel-crypto, I understand your concern but you'll have to contact Binance directly for any support with transactions on their platform. Sorry about that, and I hope they're able to help you get it resolved.
