### ISSUE TITLE
Unexpected  error [Failed to initialize WebGL]

### ISSUE THREAD

**Issue by ohm89** [helium/explorer#323]
Explorer website cannot load maps on date 2021-04-15

**Comment by cokes518** [comment]
Can you provide more information? URL, browser type, OS, etc.
Works fine over here.

**Comment by ohm89** [comment]
Yes, I use this url 

https://explorer.helium.com/coverage

Google Chrome Version 89.0.4389.128 (Official Build) (x86_64)

OS: Mac OS Big sur v11.2.3

![20210415-helium-explorer-error-2](https://user-images.githubusercontent.com/4131826/114819817-3a3d4700-9de8-11eb-9208-bdcdd704d79a.png)

![20210415-helium-explorer-error](https://user-images.githubusercontent.com/4131826/114819808-37425680-9de8-11eb-844c-2d8f662ea575.png)

**Comment by ohm89** [comment]
I also tested on firefox version 87.0 (64-bit), MAC OS Big sur v11.2.3 work fine. 

After remove react dev tools extension on chrome it work fine for now so may be its has to be the reason for react web
