### ISSUE TITLE
Show h3 string on the hotspot page

### ISSUE THREAD

**Issue by vihu** [helium/explorer#326]
It would be nice to have the hotspot's h3 location (as a string, maybe with a little clipboard icon next to it) on the `hotspots/<addr>` page.

![image](https://user-images.githubusercontent.com/3199183/114937216-61007b00-9df2-11eb-9ba4-8ae041b88ebf.png)

**Comment by rootulp** [comment]
Thanks for creating an issue @vihu ! I'd like to help implement this. For the example in your screenshot, would you like to see "Gillette, WY, United States" in an `<h3>` header where your red circle is? 

Do you think displaying the location twice (once under the map and once below the hotspot network address) is duplicative?

**Comment by vihu** [comment]
> Thanks for creating an issue @vihu ! I'd like to help implement this. For the example in your screenshot, would you like to see "Gillette, WY, United States" in an `<h3>` header where your red circle is?
> 
> Do you think displaying the location twice (once under the map and once below the hotspot network address) is duplicative?

Thank you for looking into this @rootulp.

That's not the `h3` I was looking for heh. Each hotspot in the network has a [h3](https://github.com/uber/h3) index (this is what the blockchain uses as the hotspot's location). So for example:

```
$ http --body https://api.helium.io/v1/hotspots/1125qwEBcFL6sZDtZHaHMVNEeaw4wMqAos5GYA75d9z2pmcxsY6E | jq .data.location
"8c262cd26c0a3ff"
```

So each hotspot will have this "h3 string" and I'd like that to get displayed in that red circle above :)

**Comment by rootulp** [comment]
Thanks for explaining this to me @vihu ! I put up a PR and would love to hear if you have any feedback regarding UI / UX to improve it.
