### ISSUE TITLE
Assert Location Fees exported incorrectly.

### ISSUE THREAD

**Issue by jiceman** [helium/explorer#328]
There are some bugs with the export if it includes Assert Location fees (perhaps some others as well).  I have spotted two bugs:
1) If I choose to export with the fees displayed in HNT, then the assert location fee shows up a 0.
2) if I choose to export with the fees displayed as DC, they are exported as: 1,000,000 DC
That is, with the commas and no quotes around the number of the DC; this messes up any parsing if I try to import into a spreadsheet, etc. These are in the "sent" columns. The "fee" columns look fine. 
Let me know if you need more details.

**Comment by cokes518** [comment]
related to #267
