### ISSUE TITLE
Unexpected 404 error

### ISSUE THREAD

**Issue by edoedo123** [helium/explorer#341]
Stuck at processing was trying to move helium from Binance to Binance.US

**Comment by danielcolinjames** [comment]
Hi @edoedo123, I understand your concern but you'll have to contact Binance directly for any support with transactions on their platform. Sorry about that, and I hope they're able to help you get it resolved.

**Comment by edoedo123** [comment]
Hi thank you for the reply I’m sure you know how hard it is to contact somebody at Binance 
Is there anything else I can do or you guys can do ?
