### ISSUE TITLE
Unexpected  error

### ISSUE THREAD

**Issue by Y0ngg4n** [helium/explorer#349]
Cant open coverage map.
Always getting this:
![image](https://user-images.githubusercontent.com/30302975/116075080-cd9d3480-a692-11eb-9019-9f305af02cd1.png)

**Comment by danielcolinjames** [comment]
hi @Y0ngg4n, thanks for reporting this. could you give us a little more info to help us figure out what caused this? for example:
- browser
- OS
- if this only started happening recently

or anything else you think might be helpful

thanks!

**Comment by Y0ngg4n** [comment]
OS: Manjaro Linux
Browser:  Firefox

Cant say anything about this, because was first time today on the website.

**Comment by danielcolinjames** [comment]
thanks! one other request: could you go into the console (right click anywhere on the page, click Inspect Element, then go to the console tab of the window that pops up), and then screenshot and share any errors you see there? I have a feeling it's a WebGL error of some sort, as we've had someone else on Linux & Firefox with a similar issue

**Comment by Y0ngg4n** [comment]
@danielcolinjames I dont know what you did XD but cant reproduce it now :/
