### ISSUE TITLE
Unexpected 404 error

### ISSUE THREAD

**Issue by Jetguy77** [helium/explorer#358]
https://explorer.helium.com/txns/Z83OtZCmALL37GyT_3G6NKUELIf-GwQdU8ukB3itQew
176.95 HNT to 14JE7CTzWFnccdHcaoTC5strj4JaSqVMabnQhqag9QzDbPmTVvZ never made it.  still showing "processing" after 5 hours

**Comment by danielcolinjames** [comment]
Hi @Jetguy77, this sounds like an exchange issue. You'll have to contact the exchange directly for any support with transactions on their platform. Sorry about that, and I hope they're able to help you get it resolved.

**Comment by Jetguy77** [comment]
Thanks
