### ISSUE TITLE
Pie chart colors should match TxnTag colors

### ISSUE THREAD

**Issue by danielcolinjames** [helium/explorer#37]
https://explorer.helium.com/blocks/533089

The colours in the pie chart should match the ones in the TxnTag component (based on transaction type)

**Comment by cokes518** [comment]
Hackathon: the colors used in the pie chart should match the pill color in the table.

**Comment by GrogHog** [comment]
I'd like to take a crack at this one. Do we just post our findings here? If not, how do we submit this for the contest?
Thanks,

**Comment by danielcolinjames** [comment]
@GrogHog awesome! I've assigned it to you 😄  let me know if you have any questions or anything!

in terms of submitting, the best way is if you can push your local branch up and open up a PR against master. let me know if I can help you with that

**Comment by danielcolinjames** [comment]
to any hackathon participants looking for an issue to tackle, this one is still open :)
