### ISSUE TITLE
Remove user-friendly formatting from CSV export

### ISSUE THREAD

**Issue by mfalkvidd** [helium/explorer#378]
The CSV export currently formats values in "Received Quantity" and "Sent Quantity" in human-friendly/display format (example: a value of `1337.00` is formatted as `1,337.00`. The human-friendly delimiter makes it hard to process the number in external tools.

Note: the "Fee Amount" column does not have this problem. A fee of 35000 DC is displayed as `35000`, as expected.

**Comment by cokes518** [comment]
We'll be retiring csv export in explorer v2 and directing users to community created tools.
