### ISSUE TITLE
Add links to next transaction and previous transaction buttons

### ISSUE THREAD

**Issue by danielcolinjames** [helium/explorer#38]
These buttons didn't have hrefs assigned to them, so for now I figured it's better if the buttons don't show up, since it can be confusing (or dare I say annoying) for users to see buttons that seem like they'll do something and then have them not actually do that thing :)

I took a quick look at how to actually find the next and previous transactions given only the transaction hash, but I'm not sure how to do it (let alone efficiently, with as few API calls as possible), so it'll require a bit deeper look at some point.

I commented them out of the JSX for now.

![Screen Shot 2020-10-06 at 5 30 03 PM](https://user-images.githubusercontent.com/10648471/95274110-c9deb900-07f9-11eb-8589-10316d2ffe28.png)

**Comment by iampankajgupta** [comment]
what is the issue then ??

**Comment by danielcolinjames** [comment]
The buttons didn't do anything, so I've taken them out temporarily until we can add functionality to make them do something

**Comment by filoozom** [comment]
@danielcolinjames Do you have a suggestion as to how to fetch the previous and next transactions?

The only thing I can think of with the current API is to query `/v1/blocks/:height` and then search for the transaction ID in the list, but that doesn't sound that great.

**Comment by danielcolinjames** [comment]
@filoozom yeah I wasn't quite sure either actually, good question. nothing obvious comes to mind other than that. I think the only way to do it is something like that... unless there's some other way to use the API to get "next" / "previous" transactions that I don't know about (@madninja ?)

**Comment by danielcolinjames** [comment]
unless we refactor the whole layout of that page / blocks / transaction detail pages somehow. for example, I built this awhile ago to try out a 3-panel type layout, and it makes it much easier to click through different transactions within a block: https://explorer-playground.vercel.app/txns/DzdoVikM91vUqJwdA0xONS7aNrt1IgE3CjEmwXdwK1A

**Comment by filoozom** [comment]
> unless we refactor the whole layout of that page / blocks / transaction detail pages somehow. for example, I built this awhile ago to try out a 3-panel type layout, and it makes it much easier to click through different transactions within a block: https://explorer-playground.vercel.app/txns/DzdoVikM91vUqJwdA0xONS7aNrt1IgE3CjEmwXdwK1A

Well, I'll leave that one to you then haha.

Or I guess we could still implement the first solution in the meantime? Is it really that useful of a feature though?

**Comment by danielcolinjames** [comment]
yeah good question, I think the intended purpose is to make it easier to scan through a bunch of transactions, but I have another idea for how to tackle the same problem in a slightly more helpful way... but yeah in this form it's probably not useful enough to warrant adding extra API calls to every transaction page, so I think I'll take off the hackathon label for now

but thank you for looking into it! 😄

**Comment by madninja** [comment]
> @filoozom yeah I wasn't quite sure either actually, good question. nothing obvious comes to mind other than that. I think the only way to do it is something like that... unless there's some other way to use the API to get "next" / "previous" transactions that I don't know about (@madninja ?)

I actually think that using the list of transaction hashes in a block to go to next/prev is just fine, and declares the _exact order_ of the transactions in the block

**Comment by filoozom** [comment]
In that case I can implement it that way.

**Comment by danielcolinjames** [comment]
@filoozom sure! I certainly don't see any harm in adding it 😄   some people will probably find it useful. I'll add the hackathon label back haha
