### ISSUE TITLE
missing hotspot address in new beta

### ISSUE THREAD

**Issue by cokes518** [helium/explorer#392]
on old explorer, you can view and copy the hotspot's address. this doesn't exist in new explorer and we'll need to port that over.

<img width="512" alt="image" src="https://user-images.githubusercontent.com/19331274/119543819-f114d700-bd45-11eb-9694-181cca38e801.png">

**Comment by danielcolinjames** [comment]
hotspot address is still not displayed anywhere, but it is now copyable in beta by tapping/clicking on the animal name, added in #381

we can revisit and make it better in the future, with more options (like show / show truncated / hide) but for now I think this is "MVP-solved" for users who need to get the address from a hotspot page
