### ISSUE TITLE
Checklist not updated although some of them are completed

### ISSUE THREAD

**Issue by KiDU911** [helium/explorer#398]
Withess a challenge not checked although is in present in activity list.
Also the earnings is very low and different in last week.
My rak v2 miner.
https://explorer.helium.com/hotspots/11A42Tq5PpmB1vP74wW5tp7QtedRsMgG3krEvhngpeBi43bQxsU
Thanks.

**Comment by cokes518** [comment]
looks like a valid issue @danielcolinjames can you take a look?

**Comment by cokes518** [comment]
this should be fixed. root cause is that we weren't looking for older transaction type.
