### ISSUE TITLE
Activity display

### ISSUE THREAD

**Issue by disk91** [helium/explorer#399]
the activity display is buggy, apparently not for every one and every hotspot.
As an example: https://explorer.helium.com/hotspots/11y9MT9qaLSYZnbG9VT2V8JWVBCnEifw5tRFJkpNLxpCd6qDuQZ
Activity only shows 2 activities: Assert Location and Add Hotspot.

When you click on filters and check all boxes you see you activities
Packet transferred, Mining Rewards...

But activities like Witnesses are still not visible.

For another hotspot : https://explorer.helium.com/hotspots/11etKgw9Lb6FndJnU17pKQVtsgbPJRvzE8eHny4J5f78NFvEXUD by default the activity is correctly displayed.

I had the same behavior on my desktop and smartphone. But some people I discussed with did not had this issues on the same Hotspot.. Like a caching issue ?!?

**Comment by cokes518** [comment]
is this still happening? could be related to caching, temporary api issues.

**Comment by disk91** [comment]
Not sure.

**Comment by BRB2000** [comment]
This is indeed happening again. See for example [https://explorer.helium.com/hotspots/112ejcZQQVyyahsDVcabExMPcUCJchRPVQn87ApHvqP7s25EoN53/activity](https://explorer.helium.com/hotspots/112ejcZQQVyyahsDVcabExMPcUCJchRPVQn87ApHvqP7s25EoN53/activity) .

**Comment by dobrevg** [comment]
I suppose it is Cache/Offline Data related. This happened to me also but after deleting (on Firefox) Cache and Offline Website Data, the activity was ok.

**Comment by BRB2000** [comment]
That's indeed the solution. I didn't think that would do the trick, as is was happening on multiple devices, but clearing all chached website data resolved it. That is very weird though. Maybe there can be something done to handle that scenario (e.g. review the cache headers or handle it from JavaScript).
