### ISSUE TITLE
I don’t see my witnesses anymore and RAK V2 doesn’t witness beacons lately

### ISSUE THREAD

**Issue by lfjBerlin** [helium/explorer#400]
For a couple of days now my RAK won’t receive rewards for beacons and is only making very little rewards. I switched the antenna yesterday and now all the witnesses I used to see in explorer are gone. 
any ideas what to do?

**Comment by cokes518** [comment]
Hi there,

By updating the antenna, the witness list refreshes. It will rebuild over time. 

The matter of your Hotspot not receiving rewards is outside the scope of this issue. I recommend you reach out to folks in discord to further debug why you're not receiving rewards.

**Comment by lfjBerlin** [comment]
Hey,
Unfortunately on discord no one has an indes what caused the issue. But I
am not the only one having it.

Thanks for your help!
