### ISSUE TITLE
Unexpected 404 error

### ISSUE THREAD

**Issue by bigmikeoline** [helium/explorer#408]
Hello team, 

I made a withdrawal on Binance but the transition was never completed, However my HNT's are still showing in my balance but I can't cancel the withdrawal which like I said it still pending. This the wallet I send it to: 13Myt9Hu73ytZ9ZiyevLoRBg5v4uadtXUk8WC2fmLWh7KNJnvn3

Tx ID:WKjudS4WLlfvFccY_TwyG2PvBYcsyNz22JiF8dRJfYQ

I really hope you can help me. I don't want to loose my HNT.

**Comment by abhay** [comment]
Unfortunately the core devs can’t help with a wallet they don’t control. Please contact Binance.
