### ISSUE TITLE
Humanize transaction names

### ISSUE THREAD

**Issue by cokes518** [helium/explorer#411]
hotspot transactions
* add_gateway_v1
* activity > state_channel_close_v1
<img width="529" alt="image" src="https://user-images.githubusercontent.com/19331274/120568298-747a9c00-c3c8-11eb-83f3-07292a3172ec.png">

account transactions
* assert_location_v2
* add_gateway_v1
* payment_v2
* token_burn_v1

**Comment by danielcolinjames** [comment]
closed by #466
