### ISSUE TITLE
DC Spent and Burned

### ISSUE THREAD

**Issue by cokes518** [helium/explorer#418]
old explorer has data credit spent for devices transferring data (this is missing in new explorer, we can add it in the market tab)
<img width="250" alt="image" src="https://user-images.githubusercontent.com/19331274/120524741-3cedfe80-c38c-11eb-9381-bd5a345e4a7b.png">

Something new that Marc is adding to etl is DC burned (for state channels, buying OUIs, onboarding). we should reserve space for the Market info box for "DC Burned", and equate it to a dollar amount.

API route will be here (when completed): https://api.helium.wtf/v1/dc_burns/stats

**Comment by cokes518** [comment]
new endpoint shows all DC Spent: 
<img width="346" alt="image" src="https://user-images.githubusercontent.com/19331274/121065664-de56c500-c77d-11eb-81cf-e3eeb976a4c1.png">

**Comment by adamsoffer** [comment]
Is there a way to view usage stats for days in the past? For example, I'd to know what the network usage looks like over time (dc spent each day in the past). This stats response just shows data for last_day.

**Comment by adamsoffer** [comment]
After speaking with @madninja best bet is to introduce a `stats/sum` endpoint similar to what exists for rewards. Will file.
