### ISSUE TITLE
Account beacons view is reported multiple times same beacon

### ISSUE THREAD

**Issue by snip** [helium/explorer#428]
Example of multiple times report of same beacon:
![image](https://user-images.githubusercontent.com/466133/120696672-1bd0ff00-c4ad-11eb-8a00-155149e2c1d1.png)
...
(from: https://explorer.helium.com/accounts/136CYuq3zzWW6yme4VB7F558fasBvBb3f75Bpjgisuu3UnZKNFN)

I think we expect to see only one line per beacon.

**Comment by cokes518** [comment]
it looks like something's wrong with how we fetch the API data for this page @danielcolinjames

**Comment by cokes518** [comment]
closing this issue as it's become stale (and looks like it's from explorer v1). if it's still a problem, please file a new issue. thanks!
