### ISSUE TITLE
Show HNT Emissions on homepage info box

### ISSUE THREAD

**Issue by cokes518** [helium/explorer#438]
Show HNT Emissions (last 24h) and compare to expected emissions per 24h

**Comment by allenan** [comment]
do we have an api stat for this?

**Comment by cokes518** [comment]
https://api.helium.io/v1/rewards/sum?min_time=-7%20day&bucket=day

**Comment by allenan** [comment]
should this be a trend line widget, or a single value widget? and how do we want to define "expected emissions per 24h"?

**Comment by cokes518** [comment]
trendline widget, last 30 days.

Expected emissions per 24h will be (5000000*12)/365 = 164383.56

Will adjust to (2500000*12)/365 = 82,191.7808219178 after halving.
