### ISSUE TITLE
Witness Hexes should be shaded yellow

### ISSUE THREAD

**Issue by PeterMain** [helium/explorer#459]
<img width="984" alt="Screenshot 2021-06-09 at 19 29 54" src="https://user-images.githubusercontent.com/3613880/121409294-3ac20c00-c959-11eb-9760-75ded08e7ae7.png">

This may make more sense to do when we eliminate 'hotspot dots' from the map

**Comment by cokes518** [comment]
may have to punt on this as we'll have witness color collisions (yellow shade) when the transmit scale layer is visible (Also has yellow hexes).

**Comment by cokes518** [comment]
Going to close this as won't fix. There is color collision if the transmit scale layer is visible.
<img width="988" alt="image" src="https://user-images.githubusercontent.com/19331274/131711358-fa1f3339-3ab7-4430-8f65-c4365f86683e.png">
