### ISSUE TITLE
Data Credits stat on homepage might need reconsidering

### ISSUE THREAD

**Issue by danielcolinjames** [helium/explorer#46]
Right now the "Data Credits spent (30d)" stat on the home page isn't including transactions and staking fees. Those fees are now being returned by the `/stats` endpoint, under `fees`, and broken down over day, week, month.

We should figure out the best way to approach showing these fees, as we could technically add it to the existing field, but it should probably be possible to break down that number in some way, to see the different split (staking, transactions, data transfer).

For now it might be okay to just combine the numbers into the current field, but some people might assume that number represents data credits spent on data transfer, or might be confused by the number getting quite a bit larger as soon as the change is implemented. But it also might be a bit unwieldy to add 2 new fields.

I'm thinking maybe something like this could be the best interim approach—3 different stats:
- "Data Credits spent on data transfer"
- "Data Credits spent on staking" (or maybe different wording)
- "Data Credits spent on transactions"

**Comment by anthonyra** [comment]
You could have it as a total like now but provide a drop-down button to then show them broken into the different categories
