### ISSUE TITLE
can't tell what hex a hotspot occupies in witness list

### ISSUE THREAD

**Issue by cokes518** [helium/explorer#463]
in beta explorer, there's no way to tell what hex the hotspot is in:

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/19331274/121446086-9e433e00-c947-11eb-8fb4-bbe07d2b792f.png">

**Comment by PeterMain** [comment]
It's listed above the hotspot name, but maybe you mean the map? in which case its just missing it's white stroke
