### ISSUE TITLE
Unexpected  error attempting to view activity page for specific hotspot

### ISSUE THREAD

**Issue by ke6jjj** [helium/explorer#468]
I receive a persistent "Unexpected Error" when attempting to visit the Hotspot page for hotspot
`11svDnXQeiEQSQJCMV39hAupYzCxownAurJcZFsXzYW2K2ru7pM` a.k.a. "Long Felt Cyborg".

Explorer URL:

https://explorer.helium.com/hotspots/11svDnXQeiEQSQJCMV39hAupYzCxownAurJcZFsXzYW2K2ru7pM

**Comment by ke6jjj** [comment]
The beta version has no problem with this hotspot, FWIW.

**Comment by cokes518** [comment]
https://github.com/helium/explorer/commit/c885c2e95f1b4eb778e05963b2450d4846025ca2

we're also fixing up witnesses appearing multiple times and the missing RSSI value.
