### ISSUE TITLE
cannot read property 'histogram' of undefined on page https://explorer.helium.com/hotspots/{id}

### ISSUE THREAD

**Issue by cconcannon** [helium/explorer#469]
**Describe the bug**
I'm getting an error when trying to view any hotspot details. I'm experiencing the error on multiple devices, both with and without routing through my VPN, so I'm thinking it's a problem with the page source

**To Reproduce**
1. Go to any hotspot details page, i.e. https://explorer.helium.com/hotspots/112gALom1etncjNzVk1xPMt9QLJXnJ6YyU4tbvX2isX6hcAFEYwr
2. Click on "View Hotspot Details"
3. See error

**Expected behavior**
The page loads without an error

**Screenshots**
<img width="1792" alt="Screen Shot 2021-06-10 at 12 49 26 PM" src="https://user-images.githubusercontent.com/16453494/121588059-4f9ab000-c9ea-11eb-9e26-111ec979eb50.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome and Safari
 - Version Safari 14.1.1 and Chrome 91.0.4472.101

**Additional context**
Tried request from multiple IP's (i.e. from my residential ISP and from my personal VPN running in AWS US-West-2 region). Got same error

**Comment by cokes518** [comment]
related to #468
