### ISSUE TITLE
Incorrect res8 location displayed in Beta

### ISSUE THREAD

**Issue by radrob1** [helium/explorer#472]
**Describe the bug**
Some hotspot locations are displayed in the incorrect res8 hex.

**To Reproduce**
1. Go to https://explorer-beta.helium.com/hotspots/111JUVKK9vkdLS4ZiMryYjLTjaaNmkhGT8e9E9sXtJnEC7PRyx9
2. The hotspot Chilly Rainbow Stork is displayed in the wrong res8 hex.

**Expected behavior**
This hotspot should be displayed in the neighbor res8 hex to the NE of what is currently displayed. See screenshot.

**Screenshots**
<img width="699" alt="Screen Shot 2021-06-10 at 5 59 18 PM" src="https://user-images.githubusercontent.com/78358412/121603669-1fb5d180-ca17-11eb-8c0d-43b714659be4.png">

**Comment by radrob1** [comment]
Closing this. I was incorrectly getting the resolution 8 hex via GPS coord vs parent of the res12.

**Comment by kent-williams** [comment]
Hi @radrob1,

Thanks for reporting this, we are looking into a possible discrepancy between the lat/lng and res12 index with [ETL](https://github.com/helium/blockchain-etl/issues/189).

**Comment by kent-williams** [comment]
@radrob1 This has now been fixed. A new field was `location_hex` introduced to the [ETL](https://github.com/helium/blockchain-etl/pull/190)/[API](https://github.com/helium/blockchain-http/issues/269). The beta explorer should now show the correct res8 hex.
