### ISSUE TITLE
Multipayment Details in Export

### ISSUE THREAD

**Issue by 1SenTh** [helium/explorer#486]
Currently the multipayments in explorer exports seem to show the total amount sent in the 'Sent Quantity' column and all the addresses that the amounts were sent to in the 'Sent to' column. All of this is currently in one row so you can't determine how much was sent to each wallet address.

Using the multipayment tutorial youtube video as an example (https://explorer.helium.com/accounts/13bfNdE7fA9KGHbnhAWojXrtbr5AMuFwZ91kEY9bCwUTeLiYnVF). The export looks like this:
![image](https://user-images.githubusercontent.com/80449418/122690659-bdf82300-d1df-11eb-93f8-d7f2755ae98f.png)

I feel like the best solution would be to break it into multiple lines as follows:
![image](https://user-images.githubusercontent.com/80449418/122690792-5393b280-d1e0-11eb-8c52-d1fdd48bce9a.png)

If this approach is taken however, it will need to be determined how the fee is broken out. Perhaps divided evenly between the multiple lines? Or only shown against the first line only?

**Comment by cokes518** [comment]
CSV export in explorer v1 is no longer being supported and is only available as-is. We recommend checking out community tools: https://explorer.helium.com/tools to further service your exporting needs.
