### ISSUE TITLE
Loading state for Blockchain stats

### ISSUE THREAD

**Issue by abhay** [helium/explorer#49]
Sometimes the API takes a little longer than expected and the explorer makes me nervous with all the zeroes. 

![image](https://user-images.githubusercontent.com/75/95783443-b06cbf80-0c86-11eb-9012-335a412e120b.png)

Would love to add some loader states for those values as they are coming back.

**Comment by danielcolinjames** [comment]
This should be fixed by #70  once it gets merged in 🙂 

You can try it here: https://helium-explorer-pr-70.herokuapp.com/
