### ISSUE TITLE
Display Data Credits Spent (last 30 days) By Type

### ISSUE THREAD

**Issue by woodlandsquash** [helium/explorer#496]
There is currently no simple way to isolate the data credits spent in the last 30 days on New hotspot and location asserts vs Data Transfer.  

This would be an incredibly helpful statistic for the community to be able to understand the market growth of network usage.  Currently it would be a several step process (downloading CSV’s per manufacturer) to figure out this number.  Although hotspot and location asserts will always be a portion of Data Credits burned they currently represent a disproportionally large percentage compared to where they will likely be in the future, so it makes it difficult to really understand the network’s usage growth based on the last 30 Days Data Credits used.

**Comment by cokes518** [comment]
Hi @woodlandsquash. the request makes sense. You'll want to file an issue with https://github.com/helium/blockchain-http/issues. this is a front-end repo.
