### ISSUE TITLE
Maximize InfoBox state

### ISSUE THREAD

**Issue by allenan** [helium/explorer#498]
On desktop, it would be useful in some scenarios to be able to "maximize" the InfoBox when you want to focus more on the data and less on the map. We'll have some design considerations with this where widgets might end up looking sparse.

**Comment by ericjohncarlson** [comment]
Seconded!  For the amount of data around validators specifically, a full-width view to this information is imperative.

**Comment by PeterMain** [comment]
Do you guys have specific examples of data that would utilise this extra space, or how widgets would respond to having more space? I'm not sure I'm seeing the need right now.

**Comment by cokes518** [comment]
we're going to try this out with full height infobox first (PR #613). we want to maintain a mobile-first mindset for explorer and going full-width is contrary to that.

**Comment by cokes518** [comment]
closing this as won't-do. the new expanded side panel should suffice and we want to maintain a mobile-first approach.
