### ISSUE TITLE
State channel close transations no longer show all the participating hotspots on the map

### ISSUE THREAD

**Issue by Vagabond** [helium/explorer#50]
https://explorer.helium.com/txns/OozTMXtt_w1J6nSsbPZnX2WF5yrxGl0Io07EKyptvU4

the map here used to show all the participating hotspots on the map but it no longer seems to.

**Comment by cokes518** [comment]
Hackathon: reference the code to get hotspots in a consensus group and do the same for state_channel closes, find their location, and plot them on a map

**Comment by danielcolinjames** [comment]
note for hackathon participants: you can probably borrow most of the code you would need from this component: https://github.com/helium/explorer/blob/master/components/Txns/ConsensusGroupV1.js

**Comment by MattCarlos96** [comment]
I can work on this one!
