### ISSUE TITLE
Withdrawl from Binance stuck pending

### ISSUE THREAD

**Issue by JNoel1234** [helium/explorer#503]
Address:14gNSZcpgHXRpFnUGbduCV6RZuyixD12SsYwVGzXqPVf8HLdoPM	
Txid:LOQ5rhkY_edeUY4aEkJstO9QCVy0vvexaYjG3-RnCbY

The withdrawal has been stuck for 24 hours and I can't find any way to cancel the transaction. I reached out to Binance but have yet to hear back.

**Comment by danielcolinjames** [comment]
Hi @JNoel1234, unfortunately we can't help with this and you'll have to wait to hear back from Binance support
