### ISSUE TITLE
Community Tools Page

### ISSUE THREAD

**Issue by cokes518** [helium/explorer#504]
Allow community app developers to submit their project to the community tools page. This is the catchall for all community apps and does not replace helium.com/ecosystem (which is a subset of all available tools).

Community developers should be able to edit one file, submit a PR, and have their project listed on the community tools page.
This file should ask devs for:
1. Project/App name
2. Project/App url
3. brief description of what it does
4. icon
5. tag (Hotspot Management, Data Export, Hosting, VaaS etc)

Each tag will then be a category on the tools page.

**Comment by PeterMain** [comment]
<img width="1440" alt="CommTools" src="https://user-images.githubusercontent.com/3613880/124134196-7fcdef80-da7a-11eb-9b95-fb24698f9d13.png">


Preliminary Design

Essentially, this is aa series of cards that can be added to, searched, filtered by 'type', that can also link through to the service. New submissions could be via modal or via pull request.

**Comment by PeterMain** [comment]
@cokes518 if we have a list of existing, I can actually get started on this, but it would be its own kind of page, and separate from the other pages on explorer, since there just isn't really a great way of integrating with the map.

**Comment by cokes518** [comment]
We can start with the transaction export set of tools:

URL: Minertax.com
Description: Export CSV for mining and staking rewards
Tag: Data Export

URL: https://hotspotty.net
Description: Hotspot Monitoring and Dashboard solution
Tag: Monitoring, Data Export

URL: https://helisum.com
Description: Hotspot Monitoring and Dashboard solution
Tag: Monitoring, Data Export

URL: https://davetapley.com/helium-tax/
Description: Export CSV for mining and staking rewards
Tag: Data Export

Once those are up in a skeleton format, we can bring in their icons and a proper project description.

**Comment by PeterMain** [comment]
![CommuntiyTools](https://user-images.githubusercontent.com/3613880/125417788-5591ab94-8d7d-4a99-b242-2c3bdb150c52.jpg)

initial thoughts @cokes518 ?

**Comment by cokes518** [comment]
looks good. how does one get to community tools? is there a top level nav menu?

**Comment by cokes518** [comment]
This is done, except the expanded view. That's now tracked as #575
