### ISSUE TITLE
Payments tab in beta vs old shows discrepency

### ISSUE THREAD

**Issue by jadeallenx** [helium/explorer#513]
**Describe the bug**
Browsing a wallet in old explorer shows all of the payments into or out of the wallet correctly, but in beta explorer, the payments tab only shows 3 payments (the first few) and then no more - it doesn't seem to update either, even after a hard refresh of the page.

**To Reproduce**
Look at the same wallet in old explorer payments and beta explorer on the payments tab

**Expected behavior**
Payments tab on beta should align with the payment info from old explorer

**Screenshots**
See [discord](https://discord.com/channels/404106811252408320/733699201887764511/859898123068375041) for context

**Desktop (please complete the following information):**
OS: Linux (ubuntu 20)
Browser: edge-dev (chromium build) 93.x , also used firefox 67.x and saw same result

**Comment by cokes518** [comment]
Can you try loading payments again, but let it load completely on the first tab (all activity) before selecting the Payments filter?

**Comment by cokes518** [comment]
Still an issue @jadeallenx ? I have a feeling the bug was API or caching related.
