### ISSUE TITLE
Unexpected 404 error

### ISSUE THREAD

**Issue by tcm9886** [helium/explorer#519]
I'm not sure if anyone can help.  I was re-directed here.  I have had a withdrawal from Binance to my wallet "processing" for 6 days.  I did another transfer two days ago as a test and it went right through.  How can I get this initial transaction to close?  It seems like it left binance but did not get fully closed to my wallet.

**Comment by abhay** [comment]
You'll need to contact binance support for support of their transactions. explorer will show transactions that are on chain.
