### ISSUE TITLE
Explorer reports outdated validator release as latest 

### ISSUE THREAD

**Issue by rootulp** [helium/explorer#528]
**Describe the bug**
https://explorer-beta.helium.com/validators incorrectly reports that the latest validator version is `1.0.6`. `1.0.7` was cut 41 minutes ago: https://quay.io/repository/team-helium/validator?tag=latest&tab=tags

**To Reproduce**
1. Go to https://explorer-beta.helium.com/validators
2. Observe the section at the bottom

**Expected behavior**
Latest Version: 1.0.7

**Screenshots**
<img width="447" alt="Screen Shot 2021-07-07 at 9 33 21 PM" src="https://user-images.githubusercontent.com/3699047/124848615-39412f00-df6b-11eb-9bf7-004e41dbfa1a.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Firefox
 - Version 89.0.2 (64-bit)

**Additional context**
Is there a propagation delay between the docker container registry and the explorer? For situations where there is an urgent validator release, I think this propagation delay may cause confusion.

**Comment by rootulp** [comment]
It's possible there is a considerable delay between when a release is cut and when that release number is reflected in the explorer. I checked back a little while later and confirmed that the explorer indeed did update to `1.0.7`.

<img width="429" alt="Screen Shot 2021-07-07 at 10 11 21 PM" src="https://user-images.githubusercontent.com/3699047/124851320-52001380-df70-11eb-94a4-9721203d8f9e.png">

**Comment by abhay** [comment]
Versions described here are self reported by validators via their heartbeat transactions. Explorer won't update until the validator submits these transactions, they're accepted on chain, they are absorbed by ETL, and they are available via the API.
