### ISSUE TITLE
Show Penalty score on Owner > Validators list

### ISSUE THREAD

**Issue by cokes518** [helium/explorer#532]
Users can see an account's list of validators, and in that list, we show the name, location, HNT earned, and consensus status.

It'd be nice to add the penalty score in this quick view so users don't have to click through into each validator detail.

<img width="857" alt="image" src="https://user-images.githubusercontent.com/19331274/125116495-a5be4a00-e0a1-11eb-85c1-ce11d59e930f.png">

something like this - @PeterMain can you supply an icon for "penalty"?

**Comment by PeterMain** [comment]
[penalty icon.zip](https://github.com/helium/explorer/files/6807110/penalty.icon.zip)
