### ISSUE TITLE
Unexpected  error - Sorry about that. An unexpected error occurred in your browser.

### ISSUE THREAD

**Issue by lmirsky1** [helium/explorer#533]
After installing Helium wallet on Windows 10 computer, I received this error on Chrome. 
https://explorer-beta.helium.com/validators/11iEAPDceT4t3ZwUowtkL5GsAXWXzA5GArBZiLXcTkxBCH6Ljrf

**Comment by cokes518** [comment]
that doesn't look to be a valid validator, which is why it exploded.

https://api.helium.io/v1/validators/11iEAPDceT4t3ZwUowtkL5GsAXWXzA5GArBZiLXcTkxBCH6Ljrf
```  "error": "Not Found"```

How did you get to that link?
