### ISSUE TITLE
Entering a validator address into the explorer-beta search bar brings up an account and not a validator

### ISSUE THREAD

**Issue by kellybyrd** [helium/explorer#536]
**Describe the bug**
*Explorer-beta only*
Entering a validator peer address like `112Z3Q1gBvheEdAhUBwdpPbrJ3hNqMWqKb4rd5fVYb8V9ABXGtXo` into the main search bar finds an account but doesn't recognize it as a validator.

**Expected behavior**
I expect it to return the same result as "smooth gingerbread koala" (which matches the addr above) 

**Screenshots**
![image](https://user-images.githubusercontent.com/3513964/125174075-a5907e00-e177-11eb-98c7-2121df3a8ed4.png)

**Comment by cokes518** [comment]
we'll be adding validators to helium-js which will resolve this issue.
