### ISSUE TITLE
Beta Explorer wallet balance includes staked funds

### ISSUE THREAD

**Issue by jas-williams** [helium/explorer#537]
**Describe the bug**
In explorer beta open a wallet containing a staked validator (this wallet includes a transferred wallet if that is important I don't know 
**To Reproduce**
1. Go to https://explorer-beta.helium.com/accounts/14EgEcypvKZGeEzEasVzCdAZsBByGmDDFstTuiTrLvm4Y3LVapo

**Expected behavior**
Wallet balance should be 10,000 HNT lower

**Screenshots**

**Desktop (please complete the following information):**
 - OS: IPAD chrome![image](https://user-images.githubusercontent.com/73598288/125261786-83266e00-e2f9-11eb-8595-9996b41e942a.png)

**Comment by cokes518** [comment]
Looks like we should just use `balance` from the accounts/data endpoint for "HNT Balance" which will give us the liquid value of HNT in the account.

**Comment by cokes518** [comment]
After speaking with the core devs, we've decided to add subtext to the "Total HNT Balance" called "Liquid HNT". The reasoning is that we need to show the total HNT balance of a wallet, including staked, for the rich list.
