### ISSUE TITLE
"30 Day Trend" overlaps tooltip

### ISSUE THREAD

**Issue by danielcolinjames** [helium/explorer#554]
**Describe the bug**
On some charts (the ones on /market), the chart period label in the bottom right overlaps the tooltip on the z-index

**To Reproduce**
1. Go to https://explorer.helium.com/market
2. Hover over one of the trendline charts
3. See label overlapping tooltip

**Expected behavior**
The label should go under the tooltip

**Screenshots**
![Screen Shot 2021-07-14 at 5 29 58 PM](https://user-images.githubusercontent.com/10648471/125709599-1ce93a8a-d0b8-49fd-9b8c-62d5050f1034.png)

**Comment by rdmcolorz** [comment]
Hi @danielcolinjames I think this issue is fixed, I don't see this problem in my chrome browser
