### ISSUE TITLE
Make date listing consitent on Activity Table

### ISSUE THREAD

**Issue by philltran** [helium/explorer#56]
Depending on the length of data, the data listing on Activity table sometimes wraps. I propose we choose a fontsize that works without wrapping for the maxium possible date width.

![image](https://user-images.githubusercontent.com/812816/96915353-22f25200-1474-11eb-9096-c9ef52a21043.png)

**Comment by cokes518** [comment]
Hi @philltran  we'll be sunsetting the old explorer in the coming weeks and will be focusing new development efforts on explorer v2. If this is still an issue on explorer v2, do you mind filing another issue? thanks!
