### ISSUE TITLE
Issue with syncing status getting stuck

### ISSUE THREAD

**Issue by shawaj** [helium/explorer#563]
The sync status seems to get stuck

Explorer reports 923,727 for over 12 hours...
![Screenshot_20210717-113337_Chrome](https://user-images.githubusercontent.com/3359418/126034301-c6b2733a-b895-48ee-ae10-577397fd3c92.jpg)

In reality it's fully synced...
![Screenshot_20210717-113325_Chrome](https://user-images.githubusercontent.com/3359418/126034311-f00b03eb-1c57-4aa7-9558-c93f7c83dfb4.jpg)

**Comment by cokes518** [comment]
gossip was largely responsible for the stale status. we've since changed how we calculate sync across explorer and app (As of 3.4.3). closing this, since we no longer report block height.
