### ISSUE TITLE
Failed loading state for unknown transaction

### ISSUE THREAD

**Issue by abhay** [helium/explorer#570]
![image](https://user-images.githubusercontent.com/75/126241880-659856a0-90d8-489c-9a63-718082c9b0a3.png)

https://explorer.helium.com/txns/-garbage-

Expected:

Catch 404 and show error page / failed to load state

**Comment by MohdImran001** [comment]
@danielcolinjames I'd like to work on it.

**Comment by danielcolinjames** [comment]
hey @MohdImran001, sorry for the late reply! I've assigned you to it, let me know if I can help at all or if you have any questions :)
