### ISSUE TITLE
Unexpected 404 error

### ISSUE THREAD

**Issue by Australian-Hnt-collectors** [helium/explorer#602]
helium explorer page has issues on and says does not exist error 404. 

Log onto helium explorer on main page

this happens on firefox, edge, chrome and all browsers currently when accessing from Australia
![Capture4](https://user-images.githubusercontent.com/84670450/127735614-3027e9bf-c5a0-404a-a718-0880a85be755.JPG)

**Comment by cokes518** [comment]
What url is that?

**Comment by Oceania-clean-energy** [comment]
https://explorer.helium.com/coverage

**Comment by Australian-Hnt-collectors** [comment]
> 
> 
> What url is that?

https://explorer.helium.com/coverage

**Comment by cokes518** [comment]
The entire explorer website is a coverage map. Explorer.helium.con/coverage doesn’t need to exist anymore.
