### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by jkboscolo** [helium/explorer#608]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by danielcolinjames** [comment]
hey @jkboscolo, thanks for reporting this, but could you please fill out the template to give us a bit more information on how you ran into this error?
