### ISSUE TITLE
Geolocate/zoom in on address or zip code

### ISSUE THREAD

**Issue by bschreck** [helium/explorer#627]
I've always wondered why we can search by an address or zip code in the explorer to find hotspots in a geographic region. I've wanted to check if a particular address is located in a filled/existing hexagon, and to do this I've had to pull up google maps in a separate tab and eyeball it.

This would not violate anyone's privacy, as it does not actually show where any particular hotspot is, just zooms in on a particular address provided. It would also help hotspot hosts plan where to install hotspots, i.e. make it easier to isolate geographically desirable areas.

**Comment by cokes518** [comment]
Hi, thanks for the request! We're adding city search to explorer but not address search. We'll keep this in our backlog.

**Comment by bschreck** [comment]
Why not address search? If I built it would you merge it in?

**Comment by cokes518** [comment]
we'd love nothing more. please build!
