### ISSUE TITLE
[Bug]: 500 error at URL: /hotspots/11aU6hZ5Y7xLMPNwUZdkd61Zn7vXHjMaWyz4UaxCsxtu9qaSTkr

### ISSUE THREAD

**Issue by MaDjiDoU0911** [helium/explorer#628]
### What happened?

A bug happened!

### URL

https://explorer.helium.com/hotspots/11aU6hZ5Y7xLMPNwUZdkd61Zn7vXHjMaWyz4UaxCsxtu9qaSTkr

### What browsers are you seeing the problem on?

Chrome

### Do you see the issue on Mobile or Desktop?

Desktop

**Comment by cokes518** [comment]
The URL is working fine for me. can you reproduce?
