### ISSUE TITLE
[Bug]: 500 error at URL: /hotspots/11iEn3sVLkzgu7sFPzFtov1xoDUNpBdYBHYobQZ9gjWdTWmH9r5/nearby

### ISSUE THREAD

**Issue by Tabti1973** [helium/explorer#635]
### What happened?

A bug happened!

### URL

https://explorer.helium.com/hotspots/112icEVD84azzCPHR3Sw8W7ruv9Su5eJDYYPRp6EqL2NsAp6gPSP

### What browsers are you seeing the problem on?

Microsoft Edge

### Do you see the issue on Mobile or Desktop?

Mobile

**Comment by rdmcolorz** [comment]
This works fine on chrome

**Comment by cokes518** [comment]
same.
