### ISSUE TITLE
[Bug]: 500 error at URL: /validators/11NAYiMbSaqqaW4YEonn8jr9bQLqrtkKJbyDg5W54Fsmi5mMzNB

### ISSUE THREAD

**Issue by ndlenifo** [helium/explorer#636]
### What happened?

It seems https://api.helium.io/v1/validators/ updates more frequently than the Explorer API.

### URL

https://explorer.helium.com/validators/11NAYiMbSaqqaW4YEonn8jr9bQLqrtkKJbyDg5W54Fsmi5mMzNB

### What browsers are you seeing the problem on?

Chrome, Safari, Brave, Firefox, Opera, Microsoft Edge

### Do you see the issue on Mobile or Desktop?

Mobile, Desktop

**Comment by shawaj** [comment]
Works fine for me on Chrome
![Screenshot_20210811-014514_Chrome](https://user-images.githubusercontent.com/3359418/128952827-a8e1230d-d480-4c64-b3bf-33114450b3bc.jpg)

**Comment by ndlenifo** [comment]
> Works fine for me on Chrome

My apologies, I should have been more clear: https://api.helium.io updates faster than https://explorer-api.helium.com. I mean that if you're subscribed to https://api.helium.io for updates, and then following up on Explorer, immediately after (~20 mins?), then a 500 error will be returned. After the Explorer API updates the link will work, yes.

Below is a 500 error fix, but the page might as well be a 500 error as there's not really anything to put inside of the Infobox outside of what's deterministic(`angry-purple-tiger`).
```diff
--- a/components/InfoBox/ValidatorDetailsInfoBox.js
+++ b/components/InfoBox/ValidatorDetailsInfoBox.js
@@ -30,12 +30,12 @@ const ValidatorDetailsInfoBox = () => {
       {
         iconPath: '/images/location-blue.svg',
         // path: `/cities/${hotspot.geocode.cityId}`,
-        title: <ValidatorFlagLocation geo={validator.geo} />,
+        title: <ValidatorFlagLocation geo={validator?.geo} />,
       },
       {
         iconPath: '/images/account-green.svg',
-        title: <AccountAddress address={validator.owner} truncate={5} />,
-        path: `/accounts/${validator.owner}`,
+        title: <AccountAddress address={validator?.owner} truncate={5} />,
+        path: `/accounts/${validator?.owner}`,
       },
     ]
   }, [isLoading, validator])
   ```
   
Alternatively if I were using the Explorer API then I wouldn't face this issue, but I am not aware if this is a public API or not. Thanks.

**Comment by cokes518** [comment]
explorer's update frequency is largely dependent on the peer-to-peer network. so it's expected that there's some time lag. the page also loads for me as well. 

we fixed the 500 error bug yesterday.
