### ISSUE TITLE
[Bug]: 404 error at URL: /cities/bG9uZG9uZW5nbGFuZHVuaXRlZCBraW5nZG9t

### ISSUE THREAD

**Issue by Psyic69** [helium/explorer#638]
### What happened?

Hi,
I have two Bobcat miners
(1) Overt Leather Camel &
(2)Round Gingham Wolverine

I initially had the two running of one IP address, this made the reward scale go down to 0.5, so I turned off the Round Gingham Wolverine, and got a separate ip/phone line, but this still made the scale go to 0.5 for the 2nd time on Overt Leather Camel, I updated the location twice on RGW Bobcat and paid fees. Despite Round Gingham Wolverine being switched on with dark green light is still shows a status as being off line, also the Overt Leather Camel running on it's on fibre optic cable line is still has a reward scale of 0.5. The time it takes for information to be relayed to Bobcats is frustratingly slow nobody to talk to for trouble shouting very very frustration I paid £2,500 each and it's this slow to Sync becoming a failed investment 

### URL

https://explorer.helium.com/accounts/14ALLf8czVbG1FJxFp5PMWSEcGK9KtZBL13oJ8bpQnBtAUgUucQ/hotspots

### What browsers are you seeing the problem on?

Safari

### Do you see the issue on Mobile or Desktop?

Desktop

### Relevant log output

```shell
Hi,
I have two Bobcat miners
(1) Overt Leather Camel &
(2)Round Gingham Wolverine

I initially had the two running of one IP address, this made the reward scale go down to 0.5, so I turned off the Round Gingham Wolverine, and got a separate ip/phone line, but this still made the scale go to 0.5 for the 2nd time on Overt Leather Camel, I updated the location twice on RGW Bobcat and paid fees. Despite Round Gingham Wolverine being switched on with dark green light is still shows a status as being off line, also the Overt Leather Camel running on it's on fibre optic cable line is still has a reward scale of 0.5. The time it takes for information to be relayed to Bobcats is frustratingly slow nobody to talk to for trouble shouting very very frustration I paid £2,500 each and it's this slow to Sync becoming a failed investment
```

**Comment by cokes518** [comment]
the page loads fine. I see you've filed a lot of bugs and are frustrated, but this is not the place to resolve it. you need to contact bobcat or figure out ways to place your hotspot better.
