### ISSUE TITLE
[Bug]: Helium taking too long for status updates

### ISSUE THREAD

**Issue by Psyic69** [helium/explorer#639]
### What happened?

Bobcat light has been dark Green for six hours but still showing as offline on Helium explorer 

### URL

https://explorer.helium.com/hotspots/11kcwwoQJ7FzABdGkB4bwTFjRrRgNjCcLdhFLfRfZ3j2ooTBJg9

### What browsers are you seeing the problem on?

Safari

### Do you see the issue on Mobile or Desktop?

Desktop

### Relevant log output

```shell
Transmit Scale 0.50
Synch Status is OFF LINE
Next MileStone Hotspot Status
```

**Comment by cokes518** [comment]
hi there, explorer takes time to update due to the peer-to-peer network. the best way to understand your hotspot's status is to run a diagnostic report, or use bobcat's Diagnoser.

this isn't a bug.
