### ISSUE TITLE
[Bug]: Round Gingham Wolverine Status Offline, even thou this is plugged in with internet connection

### ISSUE THREAD

**Issue by Psyic69** [helium/explorer#641]
### What happened?

[Bug]: Round Gingham Wolverine Status Offline, even thou this is plugged in with electricity & internet connection

### URL

https://explorer.helium.com/hotspots/11kcwwoQJ7FzABdGkB4bwTFjRrRgNjCcLdhFLfRfZ3j2ooTBJg9

### What browsers are you seeing the problem on?

Safari

### Do you see the issue on Mobile or Desktop?

Desktop

### Relevant log output

```shell
Synch Status OFFLINE
```

**Comment by cokes518** [comment]
this is not an explorer bug. please contact your hotspot manufacturer.
