### ISSUE TITLE
[Bug]: 500 error at URL: /hotspots/hex/881942765bfffff

### ISSUE THREAD

**Issue by Haider-w** [helium/explorer#642]
### What happened?

A bug happened!
When I want to show someone rewards per week or month, the website tells me there is something wrong (error)
![027E26A2-4129-4B07-A3FE-6777FAC75FED](https://user-images.githubusercontent.com/88796949/129084132-d59ba426-0947-4e02-ae1e-15adf2d17181.png)

### URL

https://explorer.helium.com/hotspots/hex/881942765bfffff
![1DAB5589-B8BE-4E98-BE33-873E102F4D23](https://user-images.githubusercontent.com/88796949/129083320-8ee7dcac-a94e-4468-816f-3c073e57f995.png)

### What browsers are you seeing the problem on?

Chrome

### Do you see the issue on Mobile or Desktop?

Mobile, Desktop

**Comment by cokes518** [comment]
hey @Haider-w I tried it myself on chrome and it works fine. could it be because you're on VPN? can you try again with that turned off?

**Comment by Haider-w** [comment]
Hi! 
Thanks for responding to my message. 

I try to turn off the VPN But the problem is still there

**Comment by Haider-w** [comment]
Hi, In addition to the previous email,
 the number of times the error appears has decreased

**Comment by cokes518** [comment]
Can you right click and inspect the webpage to show what errors you see? 

Right click > inspect > select "Console" tab, and take a screenshot.

**Comment by Haider-w** [comment]
Hi,
I think the problem is solved 
error message no longer appears on my iPad in Chrome

Thank you for responding

**Comment by cokes518** [comment]
👍🏼
