### ISSUE TITLE
[Bug]: 404 error at URL: /cities/ZWRnd2FyZWVuZ2xhbmR1bml0ZWQga2luZ2RvbQ

### ISSUE THREAD

**Issue by Psyic69** [helium/explorer#646]
### What happened?

I am getting invalid bacon due to being to close to another Bobcat that does not belong to me

Witnessed Beacon (Invalid)

8h ago

12 Aug 2021, 12:23pm

Edgware

25

### URL

https://explorer.helium.com/hotspots/11kcwwoQJ7FzABdGkB4bwTFjRrRgNjCcLdhFLfRfZ3j2ooTBJg9/activity

### What browsers are you seeing the problem on?

Safari

### Do you see the issue on Mobile or Desktop?

Mobile

### Relevant log output

```shell
Witnessed Beacon (Invalid)
8h ago

12 Aug 2021, 12:23pm

Edgware


25
```

**Comment by cokes518** [comment]
@Psyic69 please stop reporting issues unrelated to explorer here. this is not a bug and nothing we can do to resolve.
