### ISSUE TITLE
Explorer caching might be wonky 

### ISSUE THREAD

**Issue by densone** [helium/explorer#648]
# issue 
Validators in explorer are not showing up to date penalties even though the api shows the latest data. 

# example 
https://explorer.helium.com/validators/112ehJ1mzEx2DBM8ixK1QkuZSzTQUxhduSpsfjz86aMXR7r2faxt/penalties

the preceding validator acquired tenure in 961000 blocks. Api shows this but explorer does not reflect it. 

This leads me to believe something is off with caching in explorer.

**Comment by ndlenifo** [comment]
https://github.com/helium/explorer/issues/636 related, which is still an issue.

**Comment by densone** [comment]
This is an over 24hr delay btw.

**Comment by cokes518** [comment]
we fixed this up and should be closed.
