### ISSUE TITLE
Looks like Explorer Heartbeat data is wonky

### ISSUE THREAD

**Issue by jkowalcz** [helium/explorer#649]
### What happened?

All Validators heartbeat info is ~1750 blocks ago.

### URL

https://explorer.helium.com/validators/1125ovREGMNQ6ZEVw1QGenh1ChTKds6sD5wUGFLUuMp2iVj6iNhy

### What browsers are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### Do you see the issue on Mobile or Desktop?

Desktop

**Comment by jkowalcz** [comment]
![image](https://user-images.githubusercontent.com/68242037/129380762-c7b5c28f-c4a4-4f74-9561-cdbddeb90f5b.png)

**Comment by jkowalcz** [comment]
Reports of the Penalty scores being off as well from @whosawfish on discord.

**Comment by cokes518** [comment]
should be fixed now.
