### ISSUE TITLE
Lack of csv export and no other tools available

### ISSUE THREAD

**Issue by mfalkvidd** [helium/explorer#653]
### What happened?

CSV export was removed and we're not getting any useful feedback.

### URL

https://github.com/helium/explorer/issues/23

### What browsers are you seeing the problem on?

Chrome, Safari, Brave, Firefox, Opera, Microsoft Edge

### Do you see the issue on Mobile or Desktop?

Mobile, Desktop

**Comment by mfalkvidd** [comment]
@jiceman might be interested in this

**Comment by cokes518** [comment]
Hi there, please check the pinned message in the #explorer channel for the goals of explorer v2 and alternatives. TLDR: There are no plans to port over csv export to explorer v2.

explorer.helium.com/tools also lists data export alternatives.

**Comment by j3rm** [comment]
FWIW, you can convert json to csv using free online tools. You can also export data daily using popular free tools like postman and then send those results to google sheets. Hope that helps.

**Comment by mfalkvidd** [comment]
Thanks. The location of the tools page was what we were asking for in the closed issue.
