### ISSUE TITLE
[Bug]: Relayed status not showing for validator

### ISSUE THREAD

**Issue by PaulVMo** [helium/explorer#657]
### What happened?

The status of relayed validators is show as online rather than relayed.

For example, 
![image](https://user-images.githubusercontent.com/5673441/129827953-112e9156-962a-4699-85e9-b75fb978be3c.png)

While the Explorer API is showing a p2p-circuit address as the only listen address: https://api.helium.io/v1/validators/14ZNwtMSXRiSgMVxLy7TJmkipYEuzjDZBmh5ZFqmZA3y2uX6kDa

![image](https://user-images.githubusercontent.com/5673441/129828349-2a3c4e03-7e73-4784-aa9f-31f8274a47d1.png)

A list of relayed validators is included on the DeWi validator dashboard:, all of these show as online instead of relayed https://explorer.helium.com/validators/112u5ePmeCAiUdFpJscfa6BM9JxkkunXshsDDHdh2MeXqkt1RXkB

### URL

https://explorer.helium.com/validators/112u5ePmeCAiUdFpJscfa6BM9JxkkunXshsDDHdh2MeXqkt1RXkB

### What browsers are you seeing the problem on?

Chrome

### Do you see the issue on Mobile or Desktop?

Desktop

**Comment by cokes518** [comment]
Thanks @PaulVMo we'll fix this up.

This hotspot is currently on a p2p circuit: https://explorer.helium.com/validators/112u5ePmeCAiUdFpJscfa6BM9JxkkunXshsDDHdh2MeXqkt1RXkB

https://api.helium.io/v1/validators/112u5ePmeCAiUdFpJscfa6BM9JxkkunXshsDDHdh2MeXqkt1RXkB

We should update the `Status` box from Online to Online: Relayed.
