### ISSUE TITLE
[Bug]: empty listen_addrs hotspots is not showed as relayed status

### ISSUE THREAD

**Issue by JiapengLi** [helium/explorer#658]
### What happened?

A bug happened!

### URL

NONE

### What browsers are you seeing the problem on?

Chrome

### Do you see the issue on Mobile or Desktop?

Desktop

**Comment by shawaj** [comment]
It's technically not relayed if it has no listen address because it's not even connected. To be relayed it has to be connected through a p2p connection I believe (but probably a status showing this would be useful)

**Comment by cokes518** [comment]
correct, an empty listen address is not relayed. it's not connected at all.
