### ISSUE TITLE
[Bug]: Hotspots tab showing 0 HNT for 24 hr rewards

### ISSUE THREAD

**Issue by gdanskgrom** [helium/explorer#662]
### What happened?

Results for all owned hotspots shows 0 HNT

### URL

At /accounts/..../hotspots/  

### What browsers are you seeing the problem on?

Chrome

### Do you see the issue on Mobile or Desktop?

Mobile, Desktop

**Comment by ItsCEED** [comment]
This issue has to be on your side, what is your Chrome version and do you run any adblockers etc?

**Comment by gdanskgrom** [comment]
Possibly.  I did verify on Safari, Chrome (Desktop and iOS) earlier but all looks fine now.  Closing.
No ad blockers running.  Desktop version Chrome 92.0.4515.131 earlier when seen.
