### ISSUE TITLE
[Bug]: 404 error at URL: /cities/ZWN1YmxlbnN2YXVkc3dpdHplcmxhbmQ

### ISSUE THREAD

**Issue by Tabti1973** [helium/explorer#665]
### What happened?

A bug happened!

### URL

**https://explorer.helium.com/cities/ZWN1YmxlbnN2YXVkc3dpdHplcmxhbmQ**

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Relevant log output

```shell
i can t get my position exact .
my real position gps 46.540394,6.572027
```

**Comment by madninja** [comment]
Note that the api returns a valid city at  https://api.helium.io/v1/cities/ZWN1YmxlbnN2YXVkc3dpdHplcmxhbmQ

**Comment by cokes518** [comment]
The URL must have changed recently. If you add /hotspots, it works as expected:

https://explorer.helium.com/hotspots/cities/ZWN1YmxlbnN2YXVkc3dpdHplcmxhbmQ
