### ISSUE TITLE
[Bug]: Single hotspot in hex but transmit scale is altered

### ISSUE THREAD

**Issue by KiDU911** [helium/explorer#666]
### What happened?

A bug happened,
Saw some hotspots, including mine, that is solo in a hex, but has transmit scale lower than 1. 

### URL

https://explorer.helium.com/hotspots/112GeujPB2XNRKakNBEaBPmD8a7LSKBU8UcTBNDVqSh5zmbqRGBd

### What browsers are you seeing the problem on?

Opera

### Do you see the issue on Mobile or Desktop?

Mobile, Desktop

**Comment by capjbadger007** [comment]
You res7 hex is overcrowded, which is why you are being scaled. As designed. 
![scale](https://user-images.githubusercontent.com/87449898/130319435-d428ad79-884d-464b-9abe-4bd8ace7082d.jpg)

**Comment by KiDU911** [comment]
Didn't know that. My bad. Is there any tool to see this in function of location? Thankx.

**Comment by abhay** [comment]
Feel free to continue discussion on discord.
