### ISSUE TITLE
[Bug]: Bookmarked validator URL encounters Application error: a client-side exception has occurred (developer guidance).

### ISSUE THREAD

**Issue by rootulp** [helium/explorer#669]
### What happened?

A bookmark I have for a validator page is now broken.

This works: https://explorer.helium.com/validators/13ArgkLfwf1Uqmont4CGfmpDTBctKtWBjGhQrxtaBZZqq9q6krX
This doesn't work: https://explorer.helium.com/validator/13ArgkLfwf1Uqmont4CGfmpDTBctKtWBjGhQrxtaBZZqq9q6kRX

The only difference is the second to last character `r` vs `R`.

### URL

https://explorer.helium.com/validators/13ArgkLfwf1Uqmont4CGfmpDTBctKtWBjGhQrxtaBZZqq9q6kRX

### What browsers are you seeing the problem on?

Firefox

### Do you see the issue on Mobile or Desktop?

Desktop

**Comment by cokes518** [comment]
the recommendation here is to update the bookmarked URL.

this follows the naming convention in the api. https://api.helium.io/v1/validators/13ArgkLfwf1Uqmont4CGfmpDTBctKtWBjGhQrxtaBZZqq9q6krX
