### ISSUE TITLE
[Bug]: 404 error at URL: /cities/b3JsYW5kb2Zsb3JpZGF1bml0ZWQgc3RhdGVz

### ISSUE THREAD

**Issue by xemlo** [helium/explorer#670]
### What happened?

404 Page - clicked on Orlando in the interface.

### URL

https://explorer.helium.com/cities/b3JsYW5kb2Zsb3JpZGF1bml0ZWQgc3RhdGVz

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by cokes518** [comment]
if you type in Orlando in the search box, it takes you to this URL instead, which works:
https://explorer.helium.com/hotspots/cities/b3JsYW5kb2Zsb3JpZGF1bml0ZWQgc3RhdGVz
