### ISSUE TITLE
[Bug]: Can't search for a city

### ISSUE THREAD

**Issue by KryptoMyner** [helium/explorer#673]
### What happened?

When searching for a city, suggestions pop up while / after typing.  Choosing any one of them that is labeled as a city results in the following error screen:

Application error: a client-side exception has occurred (developer guidance).

![image](https://user-images.githubusercontent.com/4517085/131018386-b2b37da2-3404-4375-88d3-db43f996263f.png)

### URL

https://explorer.helium.com/

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Do you see the issue on Mobile or Desktop?

Desktop

**Comment by danielcolinjames** [comment]
hey, thanks for reporting this. I noticed it yesterday as well, and it is fixed by this PR: https://github.com/helium/explorer/pull/633, which you can try out here: https://helium-explorer-pr-633.herokuapp.com/hotspots/cities

hoping to get that PR merged soon!

**Comment by KryptoMyner** [comment]
Great!  Thank you for the fast response!  Yes, it works with the link provided.
