### ISSUE TITLE
[Feature]:  Add frequency to beacon witnesses

### ISSUE THREAD

**Issue by vihu** [helium/explorer#674]
### What happened?

It would be good to add frequency to the witnesses for a beacon.

API response has the frequency available example: `http --body https://api.helium.io/v1/transactions/1MNgcYAt6cGEeG0BJjwk-Sn3Ioe4fQImZrNN7PL1J1w`

![freq](https://user-images.githubusercontent.com/3199183/131031361-c9e9a040-58f2-4d52-946a-74eebc8280d7.png)

### URL

https://explorer.helium.com/txns/1MNgcYAt6cGEeG0BJjwk-Sn3Ioe4fQImZrNN7PL1J1w

### What browsers are you seeing the problem on?

Firefox

### Do you see the issue on Mobile or Desktop?

Desktop

**Comment by danielcolinjames** [comment]
thoughts on what the "about" blurb should be when you hover? or it could be the only one in the list without a tooltip?
![Screen Shot 2021-09-01 at 12 21 27 PM](https://user-images.githubusercontent.com/10648471/131731286-3cb3639f-0fbd-492b-b86d-829f7d8f87d7.png)

**Comment by vihu** [comment]
> thoughts on what the "about" blurb should be when you hover? or it could be the only one in the list without a tooltip?
> ![Screen Shot 2021-09-01 at 12 21 27 PM](https://user-images.githubusercontent.com/10648471/131731286-3cb3639f-0fbd-492b-b86d-829f7d8f87d7.png)

"The frequency at which the signal was received" or something along those lines?
