### ISSUE TITLE
Hotspot sync info delayed by several hours

### ISSUE THREAD

**Issue by bschreck** [helium/explorer#679]
I’ve noticed that it takes many hours for hotspot changes to register in the explorer. Not sure if this is a more fundamental blockchain issue or related to the explorer  itself, but I’m pretty sure it’s the explorer. Hotspots that go offline will take hours to register as such, and when the go back online (show a green light) the same thing happens.

Why is this the case? Has any thought been put into speeding this up?

**Comment by cokes518** [comment]
this is a symptom of libp2p and slow gossip around the network. as more hotspots come online, some with poor or sub-par internet connection, it can greatly affect how hotspot status updates.

the next generation of light hotspots will remove dependency on libp2p and gossip.
