### ISSUE TITLE
[Bug]: Sync stuck or coming down after update

### ISSUE THREAD

**Issue by wassu77u** [helium/explorer#687]
Everything worked fine until the last firmware update. Now the hotspot doesn`t sync beyond 998229. 
Apparently this was solved for another colleague with a factory reset.
Everything else in diagnostics seems fine. It`s connected to Ethernet, ECC detected etc. all ok.
My ticket no is 273763.
![1](https://user-images.githubusercontent.com/90269039/132398532-865e3754-c904-4043-b28c-b81bc30c69d4.JPG)
![2](https://user-images.githubusercontent.com/90269039/132398536-904835a9-9c0d-49f4-9514-621fec98eb99.JPG)
![3](https://user-images.githubusercontent.com/90269039/132398537-e6ce2b8e-d794-4a42-af7e-9589f64d6ed1.JPG)

**Comment by cokes518** [comment]
Hi, you may have filed this bug against the wrong team. This is 1) for explorer.helium.com and 2) looks like a maker problem. I'd recommend you reach out to them directly. 

Neither the app nor explorer can help you with a hotspot sync issue.
