### ISSUE TITLE
Reverse validator versioning visual color coding

### ISSUE THREAD

**Issue by cvolkernick** [helium/explorer#694]
On the main validators page (https://explorer.helium.com/validators), the "Validators Version" infographic seems to be a bit misleading / counterintuitive in terms of the color coding. Since the vast majority of validators aren't going to be on the latest version plenty of the time (unstable releases, optional, etc.) it gives the impression from a UX standpoint that most of the validators are running on "dated" (for lack of a better term) or otherwise unstable or not current standards. It seems as if perhaps the colors could be reversed to indicate that the most recent cutting edge updates are yellow as in "unstable" or "beta" and green as in "stable" (choose your particular terminology, "stable" may not be the right way to think about it).

**Comment by philltran** [comment]
Might need to make an upstream change with the API as there is no indication if a release in a beta release 

```
export const formatVersion = (versionHeartbeat) => {
  if (!versionHeartbeat) return

  const versionString = versionHeartbeat.toString().padStart(10, '0')
  const major = parseInt(versionString.slice(0, 3))
  const minor = parseInt(versionString.slice(3, 6))
  const patch = parseInt(versionString.slice(6, 10))

  return [major, minor, patch].join('.')
}


```
