### ISSUE TITLE
[Bug]: Status dot not showing relayed

### ISSUE THREAD

**Issue by PaulVMo** [helium/explorer#697]
### What happened?

For validators (and hotspots), the detail page for an individual hotspot/validator is showing the relayed message. However, the status dot is showing Online. This applies in the detail page for the validator as well as the validator list.

For example, the relayed message shows but the status shows online when it should be a yellow dot and say Relayed.
![image](https://user-images.githubusercontent.com/5673441/133629911-2a5c0c9f-e2f7-41d5-a5e8-87de3b09602b.png)

And, when used in a list, the status dot is showing green/online instead of related as expected.
![image](https://user-images.githubusercontent.com/5673441/133630095-47f06f2f-c287-4dac-837f-0584bb826821.png)

### URL

https://explorer.helium.com/validators/1125q8k9gshwMQSPXintKez2pXc3xWx85JL25WjMtZYeurJMcQ3M

### What browsers are you seeing the problem on?

Microsoft Edge

### Do you see the issue on Mobile or Desktop?

Desktop

**Comment by PaulVMo** [comment]
This is related to previous issue #657. The fix for that added the warning information text box but does not appear to have fixed the status dot.

**Comment by cokes518** [comment]
Not sure if this is really a bug. The validator is online and connected. Whether it's relayed or not doesn't factor into that status.

**Comment by PaulVMo** [comment]
Fair. At one point, relayed hotspots showed with a yellow status bubble and "relayed" as the status. I thought it would be good to emulate that for validators for more attention on relayed status which is especially bad for validators. But, yeah makes sense that relayed isn't really an online status and you've moved away from that.
Nonetheless, it think it would be useful in the validator list view to show some indicator that a validator is relayed. If not through changing the status dot color, maybe some other visual/icon that is part of the list.
![image](https://user-images.githubusercontent.com/5673441/139709722-0d02833c-facf-4cc9-bad4-f1a44b09bb2f.png)

**Comment by PaulVMo** [comment]
I'll also point out that the code is attempting to set the status as Relayed, it just doesn't seem to work: 
https://github.com/helium/explorer/blob/b9764f208d7170191601a81491f953db6c5d0908/components/Validators/ValidatorStatusDot.js#L20

https://github.com/helium/explorer/blob/b9764f208d7170191601a81491f953db6c5d0908/components/Validators/ValidatorStatusPill.js#L26
