### ISSUE TITLE
Remove remaining online/offline statuses from data-only hotspots.

### ISSUE THREAD

**Issue by jthiller** [helium/explorer#703]
* "online/offline" circle appears on hotspot list in wallet.
e.g. `Bent Heather Condor` here: https://explorer.helium.com/accounts/13CYRHKKoFUNQ441sfsAnePvJNmwJVxxz8v3r6gQRMEeXoq1F1c/hotspots
<img width="481" alt="image" src="https://user-images.githubusercontent.com/19331274/134941900-882025a3-e070-4de0-a83c-16efcefc40a9.png">
(edited to include screenshot. the mode is `dataonly` so it's not related to the discussion on miner below.

* "online/offline" circle appears on hotspot list in hex.
e.g. "Bent Heather Condor` here:
https://explorer.helium.com/hotspots/hex/8829b6c133fffff

<img width="479" alt="image" src="https://user-images.githubusercontent.com/19331274/134942083-5919ca3b-e84b-4879-a0e0-b67412018805.png">

**Comment by PaulVMo** [comment]
This might be tricker than it seems. Technically a data only hotspot can use the miner (instead of gateway-rs). This means it will gossip sync status and have a valid online/offline status for Explorer to display.

**Comment by dtischler** [comment]
`Bent Heather Condor` doesn't have the miner installed, just gateway-rs.  I can certainly install Docker and the miner, if you need it, for any testing / troubleshooting purposes.   Thanks!

**Comment by PaulVMo** [comment]
> `Bent Heather Condor` doesn't have the miner installed, just gateway-rs. I can certainly install Docker and the miner, if you need it, for any testing / troubleshooting purposes. Thanks!

FYI, there are already 9 dataonly hotspots that are currently gossiping status:
|address | name|
|---------|-------|
|14WVFUpWQWf1pRRLsdji7mdwFTKqhw4P9FSXYV9KnunzoFpoFqz | able-pickle-goldfish|
|112QWL5jauuzKcQUnN7CmW5kom2WFNP7JUxtmFxDnWqXPN7DBZWZ | agreeable-lace-sealion|
|14JjrGkSVgkK76oBSVomomvLg7uG16W8mTD2fqLatTvbcbnpZWH | fun-cherry-leopard|
|1126FyZCCFDgLWEdxJbaYxQDYjnh3AF4yCcaYrPX2iBYEoH3cz7j | orbiting-violet-perch|
|112oTtA4B9bULBWM2TnH84C8Y5csoQNcmmPg2DigGvJ24j5Nd6zE | old-walnut-anteater|
|13h38nFNqM6a2XzaR99k8CVG6S6vhiLR11zd5UEnZJLGmHhoN9b | bumpy-indigo-duck|
|14T6gfkT2nsVxKQ7jFH4Bj1Q5VRsBgEM36q1JcBTK8pHhG4XrVX | brisk-neon-guppy|
|14ahqv7JRKM9WB1Pa8b8o6kMKJZ2eEreXDJ9aV9VqsQfQTGbNVZ | cheesy-indigo-seahorse|
|14hKfXzq22QiaY2BPEd3WSxXteSDHAc27j1YJ5aoWqJh6As3S6a | cheesy-vermilion-anteater|

**Comment by dtischler** [comment]
I should clarify, this `gateway_key` has been recycled several times over, and *in the past* has had the docker container for the miner on it.  But, this SD Card was freshly formatted and RaspPi OS re-installed, then only `gateway-rs` installed, about a week ago.   Currently SSH'ed:

```
pi@raspberrypi:~ $ docker ps -a
-bash: docker: command not found
```

You mentioned "currently gossiping status"...if by current you mean literally within the past ~12 hours, then it is happening via gateway-rs.        :-)

If those gossips occurred further in the past, perhaps ~2 weeks ago, then that could have been via a miner container that was running at that time.

Thanks!
