### ISSUE TITLE
Display hotspot locations with international friendly data.

### ISSUE THREAD

**Issue by philltran** [helium/explorer#71]
[As reported by Finita la commedia in discord](https://discord.com/channels/404106811252408320/750533049623773304/772810297936707584). 

Currently, explorer and app show "City, State" for US locations and "City, City" for international locations. 
![image](https://user-images.githubusercontent.com/812816/97886753-01585c80-1cf7-11eb-93f2-e8c8f7e71637.png)

I suggest displaying "City, State / Province, Country"

**Comment by philltran** [comment]
Adding the country looks easy enough since there is a data.long_country field. 

The issue of not showing the international province may be an upstream issue. 

```
    {
      "address": "112kSXBK6iJReNq2iihxGE9gwGymPTcfYnJ9yn4ucGvYkCqYq1HW",
      "id": 4102,
      "lat": 52.536173153662375,
      "lng": 13.406815834090017,
      "location": "8c1f1d4899751ff",
      "long_city": "Berlin",
      "long_country": "Germany",
      "long_state": "Berlin",
      "long_street": "Schwedter Straße",
      "name": "Passive Golden Ape",
      "owner": "13LB84v8EpPPWbnscH8sd6RbfPjWU8YLoLWuqMKrwwqx6qxxhiT",
      "score": 0.25,
      "score_update_height": 357111,
      "short_city": "Berlin",
      "short_country": "DE",
      "short_state": "Berlin",
      "short_street": "Schwedter Str."
    },
```

**Comment by abhay** [comment]
Looks like the duplicate is due to the fact that the province is also called Berlin. @madninja any generalized advice here? Should the API provide a "formatted city" instead?

**Comment by philltran** [comment]
Ah. Sorry for my lack of world geography knowledge. lol

Thanks for looking in to that.

**Comment by madninja** [comment]
This is what the geocoder returns for various localities @abhay. I'd rather not have any API include "display" strings since that is extremely app specific?

**Comment by abhay** [comment]
Generally agree on not prescribing display but we already are with a locale assumption. Other option could be for us to geocode live in the app with the user's browser locale.

**Comment by madninja** [comment]
> Generally agree on not prescribing display but we already are with a locale assumption. Other option could be for us to geocode live in the app with the user's browser locale.

Are we? because what locale are we assuming? you mean English? try some of the Eastern European cities for a change in utf8 scenery

**Comment by abhay** [comment]
I don't have a strong preference but as we enter more locales, It'd be nice to use the browser's hints to determine how to format.
