### ISSUE TITLE
[Bug]: Explorer Status not synced with Miners

### ISSUE THREAD

**Issue by bitlite** [helium/explorer#731]
### What happened?

Miners: All are up to date, Synced up and working.

Explorer: Sync Status is still syncing last updated 3 days ago

Expected: Sync Status to be updated once Miner has Synced already.  It is currently not up dated and therefore should be updated.

### URL

[Proper Carrot Jay](https://explorer.helium.com/hotspots/11w67fHJDdGiNVRR1b8jrwLDcT1ZSMTW6erqN4acFcLb693LPd9)

[Ripe Pine Chameleon](https://explorer.helium.com/hotspots/11zCzBYruLVXPNJfmXbRxdkSYtQnAEXEujHA4A8NDM6UoCv9kM1)

### What browsers are you seeing the problem on?

Chrome, Safari, Microsoft Edge

### Do you see the issue on Mobile or Desktop?

Mobile, Desktop

**Comment by cokes518** [comment]
is this still an issue?

**Comment by cokes518** [comment]
closing as stale
