### ISSUE TITLE
UX: Remove inactive hotspots (not online for multiple consecutive months) from explorer interface

### ISSUE THREAD

**Issue by taoteh1221** [helium/explorer#734]
I think your explorer is really only missing one thing for a great UX (on the current feature set): Don't show hotspots that have been offline for multiple consecutive months. 

I'm seeing hotspots that have been inactive for 5 consecutive months on the explorer. It doesn't give a true 'feel' for live hotspots in one's locality. Hotspotty does a great job of letting you filter what shows on the map, and it really gives insightful info that way.

One possible solution that may integrate easily for you: 

1) A new database var "last_hotspot_activity", with timestamp as a value overwritten after every last hotspot's activity

2) Have your database query that loads the interface never load any hotspots with "last_hotspot_activity" timestamp older than 30 days

**Comment by ghost** [comment]
Yeah having an offline / online filter would be outstanding! :)
