### ISSUE TITLE
[Bug]: Asserting Location

### ISSUE THREAD

**Issue by xGlobalShock** [helium/explorer#740]
### What happened?

I have a strange bug on explorer when it comes to asserting location to my device.

{ https://explorer.helium.com/hotspots/112P8fMQyAr4t8ehFBoVHw4zu44yg4AUmMLJzr3FiNG19gBqn8TP }

Im not sure what's the wrong...

The first time i asserted location i waited around 4-5 days,  the device didn't show on the hex.
Then i received a notification on the helium app saying:

`Failed Transaction `
`Unable to assert Location for Amusing Inky Kangaroo for reason: Invalid, Wrong staking free.`

Then i tried asserting again, but the device is not showing on a hexagon still, been waiting for 2 days now and im a little worried, confused..

### URL

Its been almost a week now.

### What browsers are you seeing the problem on?

Chrome

### Do you see the issue on Mobile or Desktop?

Mobile, Desktop

### Relevant log output

```shell
Failed Transaction
Unable to assert Location for Amusing Inky Kangaroo for reason: {Invalid, Wrong staking free}
```

**Comment by cokes518** [comment]
is this still an issue?
