### ISSUE TITLE
Funds were transferred to Gate.io and the it was taken out without showing in the wallet history of gate.io

### ISSUE THREAD

**Issue by shadid26** [helium/explorer#748]
I transferred HNT to Gate io and in the block it shows transferred to the wallet address and then it was taken out to an unknown address. But in the Gate io platform deposit history doesn't show anything, not in or out. I've doubled checked the address and have previously sent to the same address but my last transfer is not there. I've contacted them via email and ticket but they have not responded for over a month. Seems very fishy, does it make sense for gate.io to be able to do this? Can anyone help or suggest anything?

**Comment by moejonzo** [comment]
Hey!

I have you tried accelerating the transaction via gate.io? Just did this today after my HNT disappeared into space for about 6 hours.

Go to deposits on gate.io and find self-help acceleration. Then you'll find the transaction code in helium explorer. (Click on your wallet, find the transaction, then find the transaction code.

After I did this, the funds came through in about 45 minutes.

**Comment by shadid26** [comment]
Hey Moe, the issue is that the funds were sent on the HNT explorer block - it was sent to the address then taken out. but in gate io, there is no history of this transaction.
