### ISSUE TITLE
[Bug]: helium-api.stakejoy.com requests blocked by CORS policy: No 'Access-Control-Allow-Origin'

### ISSUE THREAD

**Issue by kamlotsf** [helium/explorer#752]
### What happened?

Your new site is making cross-domain calls which are not allowed by security in many browsers.  This is not allowing any of the actual pages to come up.  Below is an example of the errors I am getting.  

Access to XMLHttpRequest at 'https://helium-api.stakejoy.com/v1/hotspots/112i7xYBHuPCmaXyDd1tpBXXZ2oSXofsVAyfCTVYByTBooSqWnoY' from origin 'https://explorer.helium.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

While I could remove this browser policy, it would allow for cross-domain attacks - https://medium.com/@dtkatz/3-ways-to-fix-the-cors-error-and-how-access-control-allow-origin-works-d97d55946d9

### URL

https://explorer.helium.com/hotspots/112i7xYBHuPCmaXyDd1tpBXXZ2oSXofsVAyfCTVYByTBooSqWnoY

### What browsers are you seeing the problem on?

Chrome, Safari

### Do you see the issue on Mobile or Desktop?

Desktop

### Relevant log output

```shell
Access to XMLHttpRequest at 'https://helium-api.stakejoy.com/v1/hotspots/112i7xYBHuPCmaXyDd1tpBXXZ2oSXofsVAyfCTVYByTBooSqWnoY' from origin 'https://explorer.helium.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

....

**Comment by eaglecreekminingco** [comment]
Did you find a fix for this?

**Comment by kamlotsf** [comment]
It now appears to be working.  I am guessing someone else addressed this issue?
