### ISSUE TITLE
Beacons tab empty

### ISSUE THREAD

**Issue by gshepperd** [helium/explorer#782]
I've had my RAK miner set up for about a week, and the beacons tab is completely empty. The beacons, challenges, witnesses do show up in the all activity tab. sweet powder mouse

**Comment by gshepperd** [comment]
I also noticed that it just seems to have disappeared off the explorer map. But it's still working witnessing, challenging, etc

**Comment by cokes518** [comment]
<img width="479" alt="image" src="https://user-images.githubusercontent.com/19331274/146271886-10f5a8b5-98ab-4fb9-937f-895bb281b59e.png">

we started investigating this the other day with @danielcolinjames. the data is there, just something is blocking your connection to the api to get that data.

**Comment by gshepperd** [comment]
Ok thanks. I moved my hotspot about 5 days ago, and it's still displaying the old ip when I do a status check on hotspotty.io. it's also showing port 44159 instead of 44158. Maybe that has something to do with it?

**Comment by cokes518** [comment]
no, that's entirely unrelated. if you moved it, double check your network configuration.

**Comment by indexample** [comment]
Glad to see i am not the only one with this. I dont see any beacons or activity, but other people have seen jt for my miner. I tried different browsers, devices, internet connection. Could not find the reason.

**Comment by indexample** [comment]
Yeah i was also suspecting some cache or cdn because i dont see activities for my miner but someone else sees them for my miner

**Comment by cokes518** [comment]
closing as this has gone stale. if this is still a problem, please open another issue.

and you're right. it's because of cache.
