### ISSUE TITLE
Back button mixes statistics from one hotspot with another.

### ISSUE THREAD

**Issue by ke6jjj** [helium/explorer#791]
### What happened?

# Summary

Hitting the back button while viewing one hotspot's statistics will cause those statistics to "stick", incorrectly displaying them against another hotspot's title.

# Steps to reproduce

1. Open explorer and search for a hotspot by name. E.g. "`long tortilla bee`"
2. Click on Long Tortilla Bee in the search results.
3. Note Long Tortilla Bee's statistics. (Currently 7D earnings of 2.325 HNT)
4. Search for a new hotspot. E.g. "`energetic lime lizard`"
5. Click on "Energetic Lime Lizard" in the search results.
6. Note Energetic Lime Lizards statistics. (Currently 7D earnings of 0.379 HNT)
7. Click the back button in the browser.

Now notice that the hotspot information display changes back to "Long Tortilla Bee", but the statistical data remains frozen at Energetic Lime Lizard's results, which incorrectly show a 7D earnings of 0.379 HNT.

### URL

https://explorer.helium.com/

### What browsers are you seeing the problem on?

Chrome, Safari

### Do you see the issue on Mobile or Desktop?

Desktop

**Comment by cokes518** [comment]
likely due to routing, we can consider removing next since we're only using a small piece of it.
