### ISSUE TITLE
[Bug]: Explorer cannot render activities in Beacons and All activities  only averages

### ISSUE THREAD

**Issue by lucac74** [helium/explorer#797]
### What happened?

In the 

explorer shows an empty activity list in Beacons and  All activities. Not consistent with the actual status and the AVG stats. (only rewards is immune to the issue)
 
In particular looks related to the returned json API call
https://helium-api.stakejoy.com/v1/hotspots/11rXcumfewUaskPacjgNjSQuSNBeCqyUCrwttso5sBG4PiRLGz1/activity?filter_types=

if filter_types=                is present (empty or equal to any value except rewards)
the returned value is  {"data":[]}

otherwise a list is returned BUT on the last page the "cursor" label that should be available but set to null is not even present in the answer.

### URL

https://explorer.helium.com/hotspots/11rXcumfewUaskPacjgNjSQuSNBeCqyUCrwttso5sBG4PiRLGz1

### What browsers are you seeing the problem on?

Chrome, Firefox, Opera, Microsoft Edge

### Do you see the issue on Mobile or Desktop?

Mobile, Desktop

### Relevant log output

```shell
https://helium-api.stakejoy.com/v1/hotspots/11rXcumfewUaskPacjgNjSQuSNBeCqyUCrwttso5sBG4PiRLGz1/activity?filter_types=

related to ALL ACTIVITIES tab


returns
{"data":[]}
```

**Comment by indexample** [comment]
today its fixed? at least i can now finally see my beacons and activity!

**Comment by lucac74** [comment]
i guess not up to the moment it will be set as "done" in the upcoming sprints...as today the visualization is still  affected

**Comment by molinellinacho** [comment]
I see an empty "All activity" list on this hotspot:

https://explorer.helium.com/hotspots/1129JfVUtTJYSsn5kSC3JnRuu2tx1QPi7g8JJJ4KqbtTxRScrR5d/activity

I don't know if os the same bug. If you change to another tab, it works, but not "All Activity"

**Comment by cokes518** [comment]
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/19331274/152208095-6f6a42d8-6f16-48ae-9da7-24d2fe729447.png">

I see your full activity list. you probably have a browser cache issue. try another browser or incognito mode. closing as this isn't a bug.

**Comment by indexample** [comment]
It was fixed a few weeks ago, no issues since. On Feb 2, 2022 18:43, Coco Tang ***@***.***> wrote:

I see your full activity list. you probably have a browser cache issue. try another browser or incognito mode. closing as this isn't a bug.
