### ISSUE TITLE
[Bug]: Hotspot 'count' goes up in 20s as loaded

### ISSUE THREAD

**Issue by davetapley** [helium/explorer#803]
### What happened?

The hotspot count on city page is wrong, it's the count of loaded (with pagination), not total.

https://user-images.githubusercontent.com/48232/147788739-614a3737-95b7-4d59-a0ba-5f94d8bc3d9b.mov

### URL

https://explorer.helium.com/hotspots/cities/bG9zIGFuZ2VsZXNjYWxpZm9ybmlhdW5pdGVkIHN0YXRlcw/hotspots

### What browsers are you seeing the problem on?

Chrome

### Do you see the issue on Mobile or Desktop?

Desktop

**Comment by cokes518** [comment]
it looks like the hotspot count that shows 60 is reporting just 1 hex. we'll have to figure out how to include all hexes within a geographical boundary of a city but that's not exactly simple to calculate. 

thanks for reporting.

**Comment by davetapley** [comment]
@cokes518 I think it's actually a more general bug when `HotspotsList` is used with `useHotspots`'s `fetchMore` callback.

The symptom is that the count goes up in 20s as you scroll the list,
so I think it's the length of the `hotspots` array as `fetchMore` is called to paginate.

You can also see it on https://explorer.helium.com/hotspots/latest:

https://user-images.githubusercontent.com/48232/147789329-210cb577-bf17-49f5-ac47-22fb3e9ffcc3.mov

**Comment by danielcolinjames** [comment]
thanks for the report @davetapley, this is fixed in #810
