### ISSUE TITLE
Show Sunset date for explorer-v1

### ISSUE THREAD

**Issue by cokes518** [helium/explorer#822]
Add a permanent banner on explorer-v1 to communicate its sunset date. In addition to some API calls no longer functional, explorer-v1 uses activity_v1 route that will also be deprecated in the near future. 

"Explorer-v1 will no longer be accessible after Feb-18-2022. New Explorer can be found at explorer.helium.com."

Before we sunset, we should make sure the redirects are in place and any missing details be brought over to explorer.helium.com.

- [ ] - v2 is missing meta data previews
- [ ] - let some twitter accounts know that v1 will be going away (some bots still use v1 links)

**Comment by cameronnili5** [comment]
Hi @cokes518 , appreciate the update. Could you please comment on how users may extract .csv files with rewards data in the v2 explorer? Is this an expected feature on the roadmap? I know external tools (DeWi.org, HottySpot) provide this service but we lose the transaction ID usually.
