### ISSUE TITLE
[Bug]: activity tab no longer shows witnesses

### ISSUE THREAD

**Issue by biohazd** [helium/explorer#827]
### What happened?

the latest update has stopped us easily seeing the Activity tab and witnesses.

You have to click into each one to view them which is not good.

I know it was done to speed up the website, but now you are hiding the vital information.

please roll it back or update to do it shows the number of witnesses in the Activity tab.

or even show the witnesses on the first page of the activity tab.

### URL

https://explorer.helium.com/hotspots/112n4XciwTW3WraNBtXgc83g2t5zLtL1o12HQPLsuohed2zdVFbS/activity

### What browsers are you seeing the problem on?

Chrome

### Do you see the issue on Mobile or Desktop?

Mobile

**Comment by biohazd** [comment]
![33DCB6E9-5EDC-4428-8C16-3632C7C0EEE1](https://user-images.githubusercontent.com/986551/150633197-9e07936f-bb5a-4737-a978-f732010f0135.jpeg)

please bring back the small icons and the number of witnesses

**Comment by biohazd** [comment]
Take a look at the Helium Discord. A lot of people are not happy and want this rolled back or fixed so we can easily see witnesses.

**Comment by danielcolinjames** [comment]
feel free to test out a preview of a fix for this here: https://helium-explorer-pr-834.herokuapp.com/

**Comment by biohazd** [comment]
Wow that looks great. It’s nice to be able to see how many Witnesses at a glance. Thanks. 

> feel free to test out a preview of a fix for this here: https://helium-explorer-pr-834.herokuapp.com/
