### ISSUE TITLE
[Bug]: Incorrect address showing under the Activity Tab for payments transactions

### ISSUE THREAD

**Issue by andreiguzga** [helium/explorer#849]
### What happened?

If you go to the Activity Tab and look for payment transactions the address you sent to is in fact your wallet address. It should show the wallet address of the wallet you sent to.

This is only for when the list is minimised. If you click on the activity to show more info, the correct wallets are shown. See the pictures below:
<img width="539" alt="Screenshot 2022-02-09 at 12 36 50" src="https://user-images.githubusercontent.com/883344/153182228-89b06921-1fa4-465d-971c-4c4c7d4ca695.png">

<img width="540" alt="Screenshot 2022-02-09 at 12 37 02" src="https://user-images.githubusercontent.com/883344/153181993-c2e2f809-a4cd-45d5-acb9-64e8f4b3446d.png">

### URL

https://explorer.helium.com/accounts/133o8XoDfuMXwqhz9K6vrNaR2PUbAZLPAXXFvffw1F9tzTjqa3Y/activity

### What browsers are you seeing the problem on?

Chrome

### Do you see the issue on Mobile or Desktop?

Desktop

**Comment by andreiguzga** [comment]
I've created a pull request that fixes the issue. https://github.com/helium/explorer/pull/850

**Comment by cokes518** [comment]
submitted fixed own issue - thank you!
