### ISSUE TITLE
[Bug]: 404 error at URL: /txns/GMOt1X5J6b3LV8QzmQ7NAkJZpPCf_C0zUb8TXihyFdI

### ISSUE THREAD

**Issue by jkkPhan** [helium/explorer#873]
### What happened?

A bug happened! Pending transaction is not being cleared on the Helium app. Unable to send tokens to wallet.

### URL

https://explorer.helium.com/txns/GMOt1X5J6b3LV8QzmQ7NAkJZpPCf_C0zUb8TXihyFdI

### What browsers are you seeing the problem on?

Chrome

**Comment by cokes518** [comment]
this looks fixed
