### ISSUE TITLE
[Bug]: 404 error at URL: /txns/YG2JkQxLv08u5o9Pq4CBki2fb9U8KHayxRxmKZTUcYA

### ISSUE THREAD

**Issue by Zukersfg** [helium/explorer#874]
### What happened?

No se transfirió el monto a mi cartera 

### URL

![A63200EA-2039-4334-B52A-F22E671BB531](https://user-images.githubusercontent.com/100496430/155862641-cdecedb2-97de-491d-940a-1981e41c8990.png)
![9715473D-0227-48C4-8859-43984D6E1247](https://user-images.githubusercontent.com/100496430/155862642-d6728bfe-25cf-403c-998f-dea2bfa96f49.png)

### What browsers are you seeing the problem on?

Safari

**Comment by cokes518** [comment]
this looks fixed.
