### ISSUE TITLE
[Bug]: 404 error at URL: /txns/GF1qDSdIUZsafzrEs---vqkiArQMcM0lzOjs_gXqS0A

### ISSUE THREAD

**Issue by hennysch1** [helium/explorer#875]
### What happened?

A bug happened! I updated the antenna gain and hight but it is not showing on app or in explorer 

### URL

https://explorer.helium.com/txns/GF1qDSdIUZsafzrEs---vqkiArQMcM0lzOjs_gXqS0A

### What browsers are you seeing the problem on?

Brave

### Do you see the issue on Mobile or Desktop?

Mobile

**Comment by cokes518** [comment]
this looks fixed.
