### ISSUE TITLE
[Bug]: Asserted new bobcat (Chilly Ash Wren) location and still reflecting old location in explorer

### ISSUE THREAD

**Issue by yomijust** [helium/explorer#878]
### What happened?

Chilly Ash Wren (Bobcat Miner) still reflects old location.  Asserted new location and no change

### URL

Change was implemented on IOS application

### What browsers are you seeing the problem on?

Safari

### Do you see the issue on Mobile or Desktop?

Mobile

**Comment by cokes518** [comment]
The database that checks new hotspot locations went down. We brought it back up, but it can take 9 hours for it to reflect the new hotspot location on explorer and in the app.
