### ISSUE TITLE
[Bug]: 404 error at URL: /txns/MqZoG1Jl7vVwoWBNeht3khJ_iqoh_AENUGZ3jB21VaI

### ISSUE THREAD

**Issue by mattymomo1993** [helium/explorer#882]
### What happened?

A bug happened!im trying to move my helium to the right hex and it says the transaction is error 40s when checking hash block =

### URL

: /txns/MqZoG1Jl7vVwoWBNeht3khJ_iqoh_AENUGZ3jB21VaI

### What browsers are you seeing the problem on?

Chrome

**Comment by cokes518** [comment]
looks like it worked, no 404 errors on this side.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/19331274/158043721-6f5b85a8-fb81-4d97-941a-58b3a95d530d.png">

**Comment by cokes518** [comment]
probably due to an API lag if you just asserted.

**Comment by mattymomo1993** [comment]
thanks!
