### ISSUE TITLE
[issue]: 404 error at URL: /txns/11PHivNJG7T6gcLXQJvytfV7PJgDoM6YKganyZ4dHcmqw68ruK9

### ISSUE THREAD

**Issue by MyRemember** [helium/explorer#884]
### What happened?

A bug happened!

After miner update, I can't connect to blockchain

[Miner A](https://explorer.helium.com/hotspots/11PHivNJG7T6gcLXQJvytfV7PJgDoM6YKganyZ4dHcmqw68ruK9/activity)

### URL

https://explorer.helium.com/hotspots/11PHivNJG7T6gcLXQJvytfV7PJgDoM6YKganyZ4dHcmqw68ruK9/activity

### What browsers are you seeing the problem on?

Chrome, Safari, Brave, Firefox, Opera, Microsoft Edge

### Do you see the issue on Mobile or Desktop?

Mobile, Desktop

### Relevant log output

```shell
Miner Update,After not connection blockchain
```

**Comment by madninja** [comment]
The explorer activity feed shows that it has had normal activity.

**Comment by MyRemember** [comment]
but ,  Miner update after no witness and no beacon ?

**Comment by madninja** [comment]
you received challenger rewards but apparently you are not witnessing anything. This is not an explorer issue but something in your hotspot or networking setup.

**Comment by MyRemember** [comment]
but i check p2p book , i think helium validator not feedback my rates

IP4 Ping-Check: Starting Ping Check

IP4 Ping-Check: Successfully pinged /ip4/188.119.38.198/tcp/44158

P2P Peer Book: Checking P2P Peer Book

P2P Peer Book: Peer Book updated: Listen Addresses: ["/ip4/188.119.38.198/tcp/44158"] 7 Connections

Online Status: Hotspot is not relayed. IP4 connection & P2P connection established.

**Comment by madninja** [comment]
really unrelated to explorer so let's stop putting it here.. If you need help with your hotspot connectivity go to Discord and ask in #hotspot-issues

**Comment by MyRemember** [comment]
Thank you so Much
