### ISSUE TITLE
[Bug]: 404 error at URL: /txns/uLFc_1HGJ8bVw0Tk5G7cy_Jc98MNAUeinCvZ1QyG9xM

### ISSUE THREAD

**Issue by atalayaktas** [helium/explorer#885]
### What happened?

A bug happened!

### URL

uLFc_1HGJ8bVw0Tk5G7cy_Jc98MNAUeinCvZ1QyG9xM

### What browsers are you seeing the problem on?

Chrome

**Comment by cokes518** [comment]
this looks fixed.
