### ISSUE TITLE
[Bug]: 404 error at URL: /txns/Fpy-AaTrrGSU8yyN1Z5tZ7xEfUlVwii5ycPcte4m6EU

### ISSUE THREAD

**Issue by Mirojellan93** [helium/explorer#888]
### What happened?

A bug happened! i don't find the tx id of the transaction

### URL

https://explorer.helium.com/txns/Fpy-AaTrrGSU8yyN1Z5tZ7xEfUlVwii5ycPcte4m6EU

### What browsers are you seeing the problem on?

Chrome

**Comment by madninja** [comment]
@Mirojellan93 please explain what you were actually doing? Where did you get this transaction hash?

**Comment by Mirojellan93** [comment]
Hello i was transfering some helium in order to change the location of my hotspot so i transfer from binance to my helium wallet but since 1 hour now it still not transfering

**Comment by madninja** [comment]
This is a binance transaction id and unrelated to the helium blockchain. We can't help you with that. Please contact Binance support
