### ISSUE TITLE
[Bug]: 404 error at URL: /txns/-Z94TmKvmaHXARctCU6tDJsd1B5bJJPezhb3omKGwvA

### ISSUE THREAD

**Issue by Kattydoll** [helium/explorer#889]
### What happened?

A bug happened!

### URL

https://explorer.helium.com/txns/-Z94TmKvmaHXARctCU6tDJsd1B5bJJPezhb3omKGwvA

### What browsers are you seeing the problem on?

Safari

### Do you see the issue on Mobile or Desktop?

Mobile

**Comment by madninja** [comment]
> ### What happened?
> A bug happened!
> 
> ### URL
> https://explorer.helium.com/txns/-Z94TmKvmaHXARctCU6tDJsd1B5bJJPezhb3omKGwvA
> 
> ### What browsers are you seeing the problem on?
> Safari
> 
> ### Do you see the issue on Mobile or Desktop?
> Mobile
> 
> ### Relevant log output
> _No 


If this is a transaction from an exchange you are waiting for, this is not the place to report it. Please contact the exchange
