### ISSUE TITLE
Recent Activity not correct on Statistics page on Warm Brick Squid

### ISSUE THREAD

**Issue by jondow72** [helium/explorer#891]
Recent Activity not correct on Statistics page on Warm Brick Squid
it only shows
Recent Activity
Asserted Location 7 days ago
Added to Blockchain 7 days ago

https://explorer.helium.com/hotspots/11vPJ15HMNxxCJcqAFsSiJM2oY7tTcNqK4xa6CeRG8zgs5LwubD

**Comment by Jhobean** [comment]
Duplication of #892

**Comment by timvak** [comment]
@jondow72 It looks te be resolved.. please close your ticket.
