### ISSUE TITLE
Recent Activity and Activity tabs not shown correctly - Young Canvas Raccoon

### ISSUE THREAD

**Issue by P3Dr076** [helium/explorer#892]
### What happened?

In the explorer the Recent Activity and Activity tabs not shown things correctly (They shows nothing) - Young Canvas Raccoon

### URL

https://explorer.helium.com/hotspots/11wauEsttUowGeGV3hMRTRYGFoShzURHWjnY2XJFvcLNcY37fVN

### What browsers are you seeing the problem on?

Safari, Firefox, Opera, Microsoft Edge

### Do you see the issue on Mobile or Desktop?

Mobile, Desktop

**Comment by Jhobean** [comment]
I had the same problem on one on my hotspot.

It fixe automatic after few day. You will see correctly on a different pc/ cellphone. It's look like the cache keep always the old version.

![image](https://user-images.githubusercontent.com/51728381/163291072-ac80a4d4-9005-4462-a178-c30678112771.png)

**Comment by raspu** [comment]
Seeing a similar issue for [Joyous Carbon Tarantula](https://explorer.helium.com/hotspots/112WYm97KEZZvwvKdvrJk2oT91LHxdWSohuqV1KwrYnEiSrrZSCu/activity)
