### ISSUE TITLE
[Bug]: Hotspot "Total Witnessed" section description should be "within past 3 days"

### ISSUE THREAD

**Issue by riobah** [helium/explorer#894]
### What happened?

`blockchain-http` module is updated to report the last 3 days witnessed counts, instead of 5 days with release 1.2.121 https://github.com/helium/blockchain-http/releases/tag/1.2.121

The description for witnessed block should be updated to reflect this change

### URL

Just check a random hotspot on Explorer. 

Explorer: https://explorer.helium.com/hotspots/11wu65LGrmmSsAMwoGtzDg2xTjs4iPZfNvuXQJrGb41e5AVRVDT
API server: https://api.helium.io/v1/hotspots/11wu65LGrmmSsAMwoGtzDg2xTjs4iPZfNvuXQJrGb41e5AVRVDT/witnessed

HTTP API change: https://github.com/helium/blockchain-http/commit/49ee76c5602a6271526bc0ce0582f8a208890a0a#diff-d8093e0584440e6498640985e7b519129691d9e4df4a2d8db197332208142170L394

### What browsers are you seeing the problem on?

Chrome, Safari, Brave, Firefox, Opera, Microsoft Edge

### Do you see the issue on Mobile or Desktop?

Mobile, Desktop

**Comment by cokes518** [comment]
this is fixed
