### ISSUE TITLE
[Bug]: 404 error at URL: /txns/SwqdnHlPXK_0Bvmqty_aey-O4vC-GTh5ORSlQ5n1KJ8

### ISSUE THREAD

**Issue by Hamedroshanpour** [helium/explorer#896]
### What happened?

A bug happened!

### URL

Transaction hash didn't match any transactions

### What browsers are you seeing the problem on?

Chrome

### Do you see the issue on Mobile or Desktop?

Mobile

### Relevant log output

```shell
Transaction hash didn't match any transactions
```

**Comment by cokes518** [comment]
this isn't a transaction on our blockchain. you'll have to check with whoever provided you this hash.
