### ISSUE TITLE
Mia aoarut acesta eroare dar nu stiu ce ansemna, poate ma lamureste si pe mine cineva. 

### ISSUE THREAD

**Issue by Crisatian** [helium/explorer#897]
### What happened?

A bug happened!failed to get peer book. Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.29/containers/fd674192cbe98c3bd673d4f4bab6021577080bef8660f12855ed171e4052df69/exec": context deadline exceeded

### URL

Https 

### What browsers are you seeing the problem on?

Chrome

### Do you see the issue on Mobile or Desktop?

Mobile

### Relevant log output

```shell
failed to get peer book. Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.29/containers/fd674192cbe98c3bd673d4f4bab6021577080bef8660f12855ed171e4052df69/exec": context deadline exceeded
```

**Comment by Crisatian** [comment]
Ok, scuze de stres dar ce ansemna că nu a reusit sa optina carte dde la ega, sunt ancepator si nu cunos foarte bine termeni!?

**Comment by cokes518** [comment]
I don't know what you're asking but your output has nothing to do with explorer. sorry!
