### ISSUE TITLE
[Bug]: 404 error at URL: /txns/nN1Cw513bDXAzSulbq-_7mjcIdfJO0wE0MQxn8_pwZ4

### ISSUE THREAD

**Issue by deliborann** [helium/explorer#899]
### What happened?

Hi, I sent hnt to my binance wallet via Helium app, but it still shows as not gone.

### URL

https://explorer.helium.com/txns/nN1Cw513bDXAzSulbq-_7mjcIdfJO0wE0MQxn8_pwZ4

### What browsers are you seeing the problem on?

Chrome

### Do you see the issue on Mobile or Desktop?

Mobile

### Relevant log output

```shell
Transaction hash didn't match any transactions.
```

**Comment by cokes518** [comment]
this isn't a transaction on the helium chain. you'll have to ask binance
