### ISSUE TITLE
[Bug]: 404 error at URL: /txns/ilQ1XdkyZILh6V4jpd3ote3BGV3YhQLqx9gkUgiRzow

### ISSUE THREAD

**Issue by Kattydoll** [helium/explorer#900]
### What happened?

A bug happened!

### URL

https://explorer.helium.com/txns/ilQ1XdkyZILh6V4jpd3ote3BGV3YhQLqx9gkUgiRzow

### What browsers are you seeing the problem on?

Chrome

### Do you see the issue on Mobile or Desktop?

Mobile

**Comment by cokes518** [comment]
this is no longer an issue
