### ISSUE TITLE
[Bug]: 404 error at URL: /txns/5qdHQpGNQ55PmK0aDO32S4zZsEZGOehjtvhMH7QMG_w

### ISSUE THREAD

**Issue by viktorbaker** [helium/explorer#913]
### What happened?

Was trying to do a transfer to hnt 

### URL

https://explorer.helium.com/txns/5qdHQpGNQ55PmK0aDO32S4zZsEZGOehjtvhMH7QMG_w

### What browsers are you seeing the problem on?

Chrome

### Do you see the issue on Mobile or Desktop?

Desktop

**Comment by cokes518** [comment]
transaction loads. closing
