### ISSUE TITLE
[Bug]: 404 error at URL: /txns/a_-Kq43gP10-KpuvWvl-pKiR64DQiD4h-Zb84RtRC3M

### ISSUE THREAD

**Issue by Ebolivar001** [helium/explorer#916]
### What happened?

My antenna seems to not be upgraded after several requests being placed, the antenna on my dashboard is still showing as default (1,2dbi) and I’m trying to update it to 5,8dbi which is the one that I’m using on my sense cap

### URL

The app

### What browsers are you seeing the problem on?

Chrome

**Comment by cokes518** [comment]
transaction doesn't exist. please try again.
