### ISSUE TITLE
[Bug]: 404 error at URL: /txns/kxp28AQD54vB5ISS6QISAVbyZL4cWPBmO3yUEou4qao

### ISSUE THREAD

**Issue by Celtichazard** [helium/explorer#917]
### What happened?

A bug happened!
I send HNT  to my wallet to relocate assortment of my hotspot and don’t appear my hnt on my wallet .already have the confirmation from Binance of the transaction 

‘this sis my TxId  kxp28AQD54vB5ISS6QISAVbyZL4cWPBmO3yUEou4qao

![CADFEFAE-3CC5-4EE7-81F7-D3A400E8778B](https://user-images.githubusercontent.com/104096965/164298378-8646de5d-d285-4255-b6ac-c0d2205a3910.jpeg)
![C5CF1E03-6402-42A3-99CE-CAE82A121BE5](https://user-images.githubusercontent.com/104096965/164298382-ec8f7792-777f-4729-8f85-3be438a47308.png)
![4C3D2D4D-2ED5-4C04-B55A-50F140F2B6A3](https://user-images.githubusercontent.com/104096965/164298389-2d1182a9-26e5-4ca4-b4c4-657f64942314.png)
![92A03911-8161-4705-BD84-FFA1C5DA1FBB](https://user-images.githubusercontent.com/104096965/164298392-a17c04cc-2bd6-4e64-b692-1de71236944f.png)

### URL

kxp28AQD54vB5ISS6QISAVbyZL4cWPBmO3yUEou4qao

### What browsers are you seeing the problem on?

Chrome

**Comment by Ryan-Goldstein** [comment]
There's an ongoing API issue reported in #announcements on the Helium Discord:

![image](https://user-images.githubusercontent.com/8300089/164299089-adc388bc-3025-4405-ae8d-047e17e81ccd.png)

**Comment by Celtichazard** [comment]
> There's an ongoing API issue reported in #announcements on the Helium Discord:
> 
> ![image](https://user-images.githubusercontent.com/8300089/164299089-adc388bc-3025-4405-ae8d-047e17e81ccd.png)

Thanks  for the advice …:)

**Comment by Ryan-Goldstein** [comment]
> > There's an ongoing API issue reported in #announcements on the Helium Discord:
> > ![image](https://user-images.githubusercontent.com/8300089/164299089-adc388bc-3025-4405-ae8d-047e17e81ccd.png)
> 
> Thanks for the advice …:)

No problem, and an incident was just posted about this as well: https://status.helium.com/incidents/d9zng11sv077

**Comment by cokes518** [comment]
works now, closing.
