### ISSUE TITLE
[Bug]: 404 error at URL: /txns/oES7Z_SjZkawiFqbMtpCr7krjAl8nGkDPN1kiETvLME

### ISSUE THREAD

**Issue by shotbyjerry** [helium/explorer#918]
### What happened?

A bug happened! I cashed out of my earnings 10 hours ago and when I looked it up on the explorer this showed up please help

### URL

https://explorer.helium.com/txns/oES7Z_SjZkawiFqbMtpCr7krjAl8nGkDPN1kiETvLME

### What browsers are you seeing the problem on?

Safari

**Comment by cokes518** [comment]
works now, closing.
