### ISSUE TITLE
[Bug]: 404 error at URL: /txns/105067447252

### ISSUE THREAD

**Issue by danmusa771110** [helium/explorer#926]
### What happened?

A bug happened!

### URL

https://explorer.helium.com/accounts/13cEmaogbLM6zdwpd2J93JnKjMADh5KzDU9W7YppCJcujNAP7uQ

### What browsers are you seeing the problem on?

Chrome

**Comment by cokes518** [comment]
that is not a valid transaction on the helium blockchain. please double check.
