### ISSUE TITLE
[Bug]: 404 error at URL: /txns/HoQC6fBhawHWxKamXpGfp4bs-CrPxBhr6-cjluhhvAg

### ISSUE THREAD

**Issue by okradb** [helium/explorer#930]
### What happened?

A bug happened!

### URL

https://explorer.helium.com/txns/HoQC6fBhawHWxKamXpGfp4bs-CrPxBhr6-cjluhhvAg

### What browsers are you seeing the problem on?

Chrome

### Do you see the issue on Mobile or Desktop?

Desktop

**Comment by cokes518** [comment]
works now, closing.
