### ISSUE TITLE
[Bug]: 404 error at URL: /txns/0ULlmyNB-Yl6vVeYrsfbQAjTSLvfAO-qVQltBemvKg8

### ISSUE THREAD

**Issue by tomi2580** [helium/explorer#931]
### What happened?

A bug happened!

### URL

https://explorer.helium.com/hotspots/112Kj3npdY9kjy9eAA2bGw2TQ6wGVJAtYRVhh19CaPZ4hDVaxMLP

### What browsers are you seeing the problem on?

Safari

### Do you see the issue on Mobile or Desktop?

Mobile

**Comment by cokes518** [comment]
works now, closing.
