### ISSUE TITLE
[Bug]: 404 error at URL: /txns/vWEC2NG2Jw9se8uxi5dujTBPUhVQOBcMnl4P7fU_uh0

### ISSUE THREAD

**Issue by sener54** [helium/explorer#932]
### What happened?

A bug happened!

### URL

882d3508d5fffff

[Sakarya, Turkey](https://explorer.helium.com/hotspots/cities/c2FrYXJ5YXR1cmtleQ)

### What browsers are you seeing the problem on?

Chrome

### Do you see the issue on Mobile or Desktop?

Mobile

**Comment by cokes518** [comment]
works now, closing.
