### ISSUE TITLE
[Bug]: 404 error at URL: /txns/AB9Is3P_jKjkOmE23Kaw6Gn1-nuvddNvr_m_bidGR-g

### ISSUE THREAD

**Issue by DinZhuta** [helium/explorer#933]
### What happened?

A bug happened!

### URL

14Q24hLMk7sXAJtZE99iknsNafm5XDvNkLDNfTjkBFD5UZDk7dx

### What browsers are you seeing the problem on?

Safari

### Do you see the issue on Mobile or Desktop?

Mobile

**Comment by cokes518** [comment]
API is undergoing maintenance https://status.helium.com/incidents/8mq3rk5xphcf

this is expected to fail. Please try again when maintenance is complete.
