### ISSUE TITLE
[Bug]: 404 error at URL: /txns/nblANff7NS8mpJ7dmKDPQJDWjdfYmXdFDoZPSoanhFk

### ISSUE THREAD

**Issue by Superfly2017** [helium/explorer#934]
### What happened?

A bug happened!

### URL

404 error

### What browsers are you seeing the problem on?

Chrome

### Do you see the issue on Mobile or Desktop?

Mobile

### Relevant log output

```shell
404 error
```

**Comment by cokes518** [comment]
API is undergoing maintenance https://status.helium.com/incidents/8mq3rk5xphcf

this is expected to fail. Please try again when maintenance is complete.
