### ISSUE TITLE
[Bug]: Mining reward field hangs -> client-side application error page

### ISSUE THREAD

**Issue by Talitrus** [helium/explorer#940]
### What happened?

Page opens as expected except for a "Received Mining Rewards" activity, which tries to load the HNT mining reward value, fails then crashes the page to "Application error: a client-side exception has occurred (see the browser console for more information)."

Able to reproduce with URL on Chrome.

### URL

https://explorer.helium.com/hotspots/11diTcahv7ZGewtXon6RxryWYZAzZS5CSsNAAP6a6QSPHPGUx7u/activity

### What browsers are you seeing the problem on?

Chrome

### Do you see the issue on Mobile or Desktop?

Desktop

### Relevant log output

```shell
main-0ef846fce14dfb95.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
```

**Comment by cokes518** [comment]
works now, closing.

**Comment by Talitrus** [comment]
Still seeing this crash. Scroll to 5d ago, ~May 11th 8 PM activity data.

**Comment by Talitrus** [comment]
Here's another example as well. The problematic reward event is also from May 11th. https://explorer.helium.com/hotspots/11LtW3WF2AbeeHjX8AnCqiNGPcJSkwzgkNntkhFRrjGDVGnJSGD/activity
