### ISSUE TITLE
[Bug]: 404 error at URL: /txns/ShlFoN4yUgmkw3oJY520pekkahosK3yzW39-pn6lv3Y

### ISSUE THREAD

**Issue by marcinrc** [helium/explorer#941]
### What happened?

A bug happened! I don't see this reward on my wallet

### URL

https://explorer.helium.com/txns/ShlFoN4yUgmkw3oJY520pekkahosK3yzW39-pn6lv3Y

### What browsers are you seeing the problem on?

Chrome

**Comment by soulja57** [comment]
This transaction is from block 1353627. At the time of writing this comment explorer has only seen blocks up to 1353609. The transaction should be visible once the explorer API catches up.

**Comment by cokes518** [comment]
works now, closing.
