### ISSUE TITLE
[Bug]: 404 error at URL: /txns/j5OgxtlGiKLuE72O7ALC8w2ANbmBUc6qP81bl4DyqzY

### ISSUE THREAD

**Issue by MartynRobinson** [helium/explorer#942]
### What happened?

My miner witnessed a, beacon, but when I go to look at it via Helium Geek app on Explorer, it cannot be found. 

### URL

https://explorer.helium.com/txns/j5OgxtlGiKLuE72O7ALC8w2ANbmBUc6qP81bl4DyqzY

### What browsers are you seeing the problem on?

Chrome

### Do you see the issue on Mobile or Desktop?

Mobile

### Relevant log output

```shell
https://explorer.helium.com/txns/j5OgxtlGiKLuE72O7ALC8w2ANbmBUc6qP81bl4DyqzY
```

**Comment by soulja57** [comment]
This transaction is from block 1353806. At the time of writing this comment explorer has only seen blocks up to 1353609. The transaction should be visible once the explorer API catches up.

**Comment by cokes518** [comment]
works now, closing.
