### ISSUE TITLE
[Bug]: 404 error at URL: /txns/gBhkex-VQ1VN58ApgDIOmx5kiY5lPcReqth51MCMep4

### ISSUE THREAD

**Issue by Arashhit** [helium/explorer#961]
### What happened?

A bug happened!

### URL

https://explorer.helium.com/txns/gBhkex-VQ1VN58ApgDIOmx5kiY5lPcReqth51MCMep4

### What browsers are you seeing the problem on?

Brave

### Do you see the issue on Mobile or Desktop?

Mobile, Desktop

**Comment by kellybyrd** [comment]
As of 06:51PM on 2022-05-36, that URL works for me in Chrome.

**Comment by cokes518** [comment]
same. closing.
