### ISSUE TITLE
[Bug]: 404 error at URL: /txns/dzcq5-vDNvbUpSsbJ-3L7cgThRf6mhHPLJOPO3XZnaU

### ISSUE THREAD

**Issue by RICHBLOOM1** [helium/explorer#962]
### What happened?

when trying to register the hotspot within the helium network does the transaction it throws me a ded hash because the transaction is canceled and it says not find a transaction with that hash.

### URL

https://explorer.helium.com/txns/dzcq5-vDNvbUpSsbJ-3L7cgThRf6mhHPLJOPO3XZnaU

### What browsers are you seeing the problem on?

Chrome

### Do you see the issue on Mobile or Desktop?

Mobile

### Relevant log output

```shell
404 — Transaction Not Found

Double check the transaction hash



Transaction hash didn't match any transactions
```

**Comment by cokes518** [comment]
working now. probably clicked on the transaction too quick and ETL did not see it yet.
