### ISSUE TITLE
[Bug]: Failing to Update Recent Activity

### ISSUE THREAD

**Issue by Fqmny1** [helium/explorer#963]
### What happened?

My bobcat 300 was added to the blockchain 2 days ago. I am witnessing and getting rewards ever since, but Explorer incorrectly shows, when I use Chrome, under the “Status” and “Recent Activity” tabs, that my hotspot was last active 2 days ago (i.e., when it was added to the blockchain). When I use Safari, Explorer correctly shows, under the “Status” and “Recent Activity” tabs, that my hotspot was last active 10 minutes ago. 

### URL

explorer.helium.com

### What browsers are you seeing the problem on?

Chrome

### Do you see the issue on Mobile or Desktop?

Mobile, Desktop

**Comment by just-jase** [comment]
I have exactly the same issue with one i added 6 days ago. The problem is only with the Chrome browser and does not exist when using Firefox.

**Comment by cokes518** [comment]
it's a caching issue as just-jase is alluding to. solution is to try a new browser, clear cache, or incognito mode.
