### ISSUE TITLE
[Bug]: 404 error at URL: /txns/txUrty4enw7BJ6CrRU0zwRIgfJVUY_AYLe741lUr7Wc

### ISSUE THREAD

**Issue by tmackic** [helium/explorer#965]
### What happened?

A bug happened!

### URL

txUrty4enw7BJ6CrRU0zwRIgfJVUY_AYLe741lUr7Wc

### What browsers are you seeing the problem on?

Chrome

### Do you see the issue on Mobile or Desktop?

Mobile

**Comment by cokes518** [comment]
this transaction does not exist. did you copy this from an exchange? if so, they have their own way to tracking and is unrelated to helium blockchain.
