### ISSUE TITLE
[Bug]: 404 error at URL: /txns/KU_u7HrkLcub99lZyUpAj_O9D7S-LFhrWfClkf-2BW8

### ISSUE THREAD

**Issue by Blitzz55** [helium/explorer#966]
### What happened?

A bug happened! The transaction was not recognised for some reason. Error 404 Transaction hash didn't match any transactions

### URL

https://explorer.helium.com/txns/KU_u7HrkLcub99lZyUpAj_O9D7S-LFhrWfClkf-2BW8

### What browsers are you seeing the problem on?

Chrome

### Do you see the issue on Mobile or Desktop?

Mobile

### Relevant log output

```shell
404 — Transaction Not Found

Double check the transaction hash



Transaction hash didn't match any transactions
```

**Comment by cokes518** [comment]
working now.
