### ISSUE TITLE
Activity does not update after added to blockchain on explorer. But earning :)

### ISSUE THREAD

**Issue by s-areal** [helium/explorer#978]
info about asserted location, beacons and rewards, doesn't show up on explorer on All Activity tab.
You can get the becons and rewards info on the corresponding tabs.

![Captura de ecrã 2022-06-17, às 00 19 26](https://user-images.githubusercontent.com/49781569/174193713-bf479470-418c-4ebb-b6ce-eb92c21b7456.png)

![Captura de ecrã 2022-06-17, às 00 19 53](https://user-images.githubusercontent.com/49781569/174193759-476c23ca-13a7-485a-ab10-2ad0c34a7ecb.png)

**Comment by s-areal** [comment]
I have tried clearing the cache, tried chrome and brave on the mac and IOS. still the same after 6 days

https://explorer.helium.com/hotspots/112aL5FzwJYGUT9UoFqMBJsYe82K1t5YdAUdgs4C7qYUMbkGb7ce/activity

![Captura de ecrã 2022-06-20, às 23 19 10](https://user-images.githubusercontent.com/49781569/174683982-257f6067-1a6d-4531-b6bf-23c85290bd06.png)
![Captura de ecrã 2022-06-20, às 23 19 41](https://user-images.githubusercontent.com/49781569/174684018-e9189ac6-f3f1-42ee-82f6-e6953fd4d62d.png)

**Comment by rhenium2** [comment]
I had the same issue, however it got fixed after exactly 10 days
