### ISSUE TITLE
Hotspot Earnings Chart

### ISSUE THREAD

**Issue by cokes518** [helium/explorer#98]
Similar to Sitebots and Mylar's earnings chart, graph a hotspot's daily and weekly earnings. An ideal interaction would be to hover over the chart and see detailed numbers with a timestamp.

Earnings change week over week (%) or period over period

**Comment by abhay** [comment]
This is mostly implemented. Now all we need is comparisons vs equivalent periods as discussed this morning @cokes518 @allenan
