### ISSUE TITLE
[Enhancement]: Add empty message to hotspots tab

### ISSUE THREAD

**Issue by Perronef5** [helium/explorer#982]
It is a bit confusing when you click on a maker and no hotspots show up. At first glance, I thought I was filtering through makers and it would show me all hotspots from that maker. I then realized it was showing which hotspots that maker owned. I think an empty message with a clear description would help with this.

Link to maker I was looking at:
https://explorer.helium.com/accounts/13daGGWvDQyTyHFDCPz8zDSVTWgPNNfJ4oh31Teec4TRWfjMx53/hotspots

**Comment by cokes518** [comment]
we can possibly tie this with the map layer request from #983
