### ISSUE TITLE
[Enhancement]: Add hotspot vendor colourise layer

### ISSUE THREAD

**Issue by mcauser** [helium/explorer#983]
We can currently colourise hexes with Transmit Scales and Earnings.
Would be nice if there was one for colourising by hotspot Vendor.

**Comment by cokes518** [comment]
We can likely do this, but a user would have to select the specific hotspot maker in order to see the hexes. reason for this is that we can have multiple makers for each hex.

**Comment by mcauser** [comment]
Yeah, I wasn't sure the best way to handle multiple vendors per hex.
Highlighting / filtering to a single vendor may help with revealing possible self-witnessing gaming clusters.
