### ISSUE TITLE
[Bug]: 404 error at URL: /txns/0ieap550Y38jDLUX3vDtBzFeiwg83RSR0uOuWK1Eq7s

### ISSUE THREAD

**Issue by PepeRender** [helium/explorer#984]
### What happened?

A bug happened! I can't change my hotspot location

### URL

https://explorer.helium.com/txns/0ieap550Y38jDLUX3vDtBzFeiwg83RSR0uOuWK1Eq7s

### What browsers are you seeing the problem on?

Firefox

### Do you see the issue on Mobile or Desktop?

Mobile

**Comment by cokes518** [comment]
did you try changing location again? the transaction doesn't exist.

**Comment by cokes518** [comment]
closing as stale.
