### ISSUE TITLE
[Bug]: 404 error at URL: /txns/CozozeeT2GU_lhQcCiY1hn3q_Nzsx8fMz4_k5a61RfY

### ISSUE THREAD

**Issue by MrBabyPicasso** [helium/explorer#985]
### What happened?

A bug happened!

### URL

simpleswap.io

### What browsers are you seeing the problem on?

Brave

### Do you see the issue on Mobile or Desktop?

Desktop

**Comment by cokes518** [comment]
this is not a valid transaction hash for our blockchain. please check your source
