### ISSUE TITLE
[Bug]: 404 error at URL: /txns/5-IXeA9XuYEwsQYC1Vxw2uSuEcbE_QVvV3huYzma0m0

### ISSUE THREAD

**Issue by Roush27** [helium/explorer#989]
### What happened?

A bug happened! I keep trying to assert location but it keeps giving me a 404 error. 

### URL

https://explorer.helium.com/hotspots/112MnPjQJYrpn3xEQSs6XJaTMrn3V4P756M1yuV2jDUKqnxrs8kv 
![31FC78B0-B7A1-48E4-9F9A-A1CFADCB6959](https://user-images.githubusercontent.com/108941994/178012231-e53b531d-acf4-4a16-8d67-646f6abb516d.png)

### What browsers are you seeing the problem on?

Chrome

### Do you see the issue on Mobile or Desktop?

Mobile

**Comment by cokes518** [comment]
Hi @Roush27 The manufacturer has run out of credits to onboard and assert location. There's nothing for you to do except to wait a few days. 

you can see that this is at "0 Onboards Remaining", which also includes the fees for assert location.

<img width="329" alt="image" src="https://user-images.githubusercontent.com/19331274/178063812-97163ee8-5dfd-4241-8484-99a4ca16988f.png">

**Comment by cokes518** [comment]
the link to track how many credits a manufacturer has is here: https://explorer.helium.com/hotspots/makers

**Comment by Roush27** [comment]
Oh ok thank you for dropping some knowledge on me appreciate it. Do you know if I can pay it myself just to onboard it as soon as possible? I don’t mind paying the $10
