### ISSUE TITLE
[Bug]: 404 error at URL: /txns/Af_N14-T_OIyCEfHYHzkG0gzsWagEQ62gG9ruq50FE4

### ISSUE THREAD

**Issue by ashulman2000** [helium/explorer#990]
### What happened?

A bug happened!

404 — Transaction Not Found

Transaction hash didn't match any transactions.

### URL

https://explorer.helium.com/txns/Af_N14-T_OIyCEfHYHzkG0gzsWagEQ62gG9ruq50FE4

### What browsers are you seeing the problem on?

Chrome

### Do you see the issue on Mobile or Desktop?

Desktop

### Relevant log output

```shell
404 — Transaction Not Found

Transaction hash didn't match any transactions.
```

**Comment by cokes518** [comment]
did you receive this transaction hash from an exchange? if so, then their hashes are not the same as ours.
