### ISSUE TITLE
[Bug]: 404 error at URL: /txns/_UWXGPrnglfMmmQFyw46Ij9jDEPFDociA72n-iFnMhA

### ISSUE THREAD

**Issue by Valentim123** [helium/explorer#991]
### What happened?

A bug happened! No pay

### URL

https://explorer.helium.com/hotspots/112f4CVPPv7nfkUhereQNgU6FFzTwCkQPBq4ynr5Q5b4QYKs7ZwA/activity

### What browsers are you seeing the problem on?

Chrome

### Do you see the issue on Mobile or Desktop?

Mobile

**Comment by cokes518** [comment]
The transaction hash doesn't look like it's valid. can you double check where you got the transaction hash from?

**Comment by cokes518** [comment]
if it's from an exchange, you'll have to reach out to them.
