### ISSUE TITLE
Hotspot assertion pending

### ISSUE THREAD

**Issue by charlee-dr** [helium/explorer#996]
### What happened?

I asserted a hotspot and the transaction is still pending, when I try to check txns on explorer I get a 404 error not found (Txns: IGpRNimHrS7616_WaghVXZ3gA1WSeok11kBS1qz9T9Q)

### URL

https://explorer.helium.com/txns/IGpRNimHrS7616_WaghVXZ3gA1WSeok11kBS1qz9T9Q

### What browsers are you seeing the problem on?

Brave

### Do you see the issue on Mobile or Desktop?

Mobile

### Relevant log output

```shell
404 — Transaction Not Found

Double check the transaction hash
```

**Comment by cokes518** [comment]
This has cleared.
